/*
Rally WebService API

Rally Open API docs

API version: v2.0
Contact: support@rallydev.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)


// AllowedQueryOperatorAPIService AllowedQueryOperatorAPI service
type AllowedQueryOperatorAPIService service

type ApiAllowedQueryOperatorReadRequest struct {
	ctx context.Context
	ApiService *AllowedQueryOperatorAPIService
	objectId string
	compact *bool
	fetch *string
}

// 
func (r ApiAllowedQueryOperatorReadRequest) Compact(compact bool) ApiAllowedQueryOperatorReadRequest {
	r.compact = &compact
	return r
}

// fetch
func (r ApiAllowedQueryOperatorReadRequest) Fetch(fetch string) ApiAllowedQueryOperatorReadRequest {
	r.fetch = &fetch
	return r
}

func (r ApiAllowedQueryOperatorReadRequest) Execute() (*AllowedQueryOperatorRead200Response, *http.Response, error) {
	return r.ApiService.AllowedQueryOperatorReadExecute(r)
}

/*
AllowedQueryOperatorRead AllowedQueryOperator Read

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param objectId objectId
 @return ApiAllowedQueryOperatorReadRequest
*/
func (a *AllowedQueryOperatorAPIService) AllowedQueryOperatorRead(ctx context.Context, objectId string) ApiAllowedQueryOperatorReadRequest {
	return ApiAllowedQueryOperatorReadRequest{
		ApiService: a,
		ctx: ctx,
		objectId: objectId,
	}
}

// Execute executes the request
//  @return AllowedQueryOperatorRead200Response
func (a *AllowedQueryOperatorAPIService) AllowedQueryOperatorReadExecute(r ApiAllowedQueryOperatorReadRequest) (*AllowedQueryOperatorRead200Response, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *AllowedQueryOperatorRead200Response
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AllowedQueryOperatorAPIService.AllowedQueryOperatorRead")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/slm/webservice/v2.0/allowedqueryoperator/{objectId}"
	localVarPath = strings.Replace(localVarPath, "{"+"objectId"+"}", url.PathEscape(parameterValueToString(r.objectId, "objectId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.compact != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "compact", r.compact, "form", "")
	} else {
        var defaultValue bool = true
        parameterAddToHeaderOrQuery(localVarQueryParams, "compact", defaultValue, "form", "")
        r.compact = &defaultValue
	}
	if r.fetch != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "fetch", r.fetch, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
