/*
Rally WebService API

Rally Open API docs

API version: v2.0
Contact: support@rallydev.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)

// ObjectiveConversationPostAPIService ObjectiveConversationPostAPI service
type ObjectiveConversationPostAPIService service

type ApiObjectiveConversationPostCreateRequest struct {
	ctx                               context.Context
	ApiService                        *ObjectiveConversationPostAPIService
	objectiveConversationPostMutation *ObjectiveConversationPostMutation
}

// ObjectiveConversationPost
func (r ApiObjectiveConversationPostCreateRequest) ObjectiveConversationPostMutation(objectiveConversationPostMutation ObjectiveConversationPostMutation) ApiObjectiveConversationPostCreateRequest {
	r.objectiveConversationPostMutation = &objectiveConversationPostMutation
	return r
}

func (r ApiObjectiveConversationPostCreateRequest) Execute() (*ObjectiveConversationPostCreate200Response, *http.Response, error) {
	return r.ApiService.ObjectiveConversationPostCreateExecute(r)
}

/*
ObjectiveConversationPostCreate ObjectiveConversationPost Create

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiObjectiveConversationPostCreateRequest
*/
func (a *ObjectiveConversationPostAPIService) ObjectiveConversationPostCreate(ctx context.Context) ApiObjectiveConversationPostCreateRequest {
	return ApiObjectiveConversationPostCreateRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return ObjectiveConversationPostCreate200Response
func (a *ObjectiveConversationPostAPIService) ObjectiveConversationPostCreateExecute(r ApiObjectiveConversationPostCreateRequest) (*ObjectiveConversationPostCreate200Response, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPost
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *ObjectiveConversationPostCreate200Response
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ObjectiveConversationPostAPIService.ObjectiveConversationPostCreate")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/slm/webservice/v2.0/objectiveconversationpost/create"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.objectiveConversationPostMutation == nil {
		return localVarReturnValue, nil, reportError("objectiveConversationPostMutation is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.objectiveConversationPostMutation
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiObjectiveConversationPostDeleteRequest struct {
	ctx        context.Context
	ApiService *ObjectiveConversationPostAPIService
	objectId   string
}

func (r ApiObjectiveConversationPostDeleteRequest) Execute() (*AllowedAttributeValueDelete200Response, *http.Response, error) {
	return r.ApiService.ObjectiveConversationPostDeleteExecute(r)
}

/*
ObjectiveConversationPostDelete ObjectiveConversationPost Delete

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param objectId objectId
	@return ApiObjectiveConversationPostDeleteRequest
*/
func (a *ObjectiveConversationPostAPIService) ObjectiveConversationPostDelete(ctx context.Context, objectId string) ApiObjectiveConversationPostDeleteRequest {
	return ApiObjectiveConversationPostDeleteRequest{
		ApiService: a,
		ctx:        ctx,
		objectId:   objectId,
	}
}

// Execute executes the request
//
//	@return AllowedAttributeValueDelete200Response
func (a *ObjectiveConversationPostAPIService) ObjectiveConversationPostDeleteExecute(r ApiObjectiveConversationPostDeleteRequest) (*AllowedAttributeValueDelete200Response, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodDelete
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *AllowedAttributeValueDelete200Response
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ObjectiveConversationPostAPIService.ObjectiveConversationPostDelete")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/slm/webservice/v2.0/objectiveconversationpost/{objectId}"
	localVarPath = strings.Replace(localVarPath, "{"+"objectId"+"}", url.PathEscape(parameterValueToString(r.objectId, "objectId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiObjectiveConversationPostReadRequest struct {
	ctx        context.Context
	ApiService *ObjectiveConversationPostAPIService
	objectId   string
	compact    *bool
	fetch      *string
}

func (r ApiObjectiveConversationPostReadRequest) Compact(compact bool) ApiObjectiveConversationPostReadRequest {
	r.compact = &compact
	return r
}

// fetch
func (r ApiObjectiveConversationPostReadRequest) Fetch(fetch string) ApiObjectiveConversationPostReadRequest {
	r.fetch = &fetch
	return r
}

func (r ApiObjectiveConversationPostReadRequest) Execute() (*ObjectiveConversationPostRead200Response, *http.Response, error) {
	return r.ApiService.ObjectiveConversationPostReadExecute(r)
}

/*
ObjectiveConversationPostRead ObjectiveConversationPost Read

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param objectId objectId
	@return ApiObjectiveConversationPostReadRequest
*/
func (a *ObjectiveConversationPostAPIService) ObjectiveConversationPostRead(ctx context.Context, objectId string) ApiObjectiveConversationPostReadRequest {
	return ApiObjectiveConversationPostReadRequest{
		ApiService: a,
		ctx:        ctx,
		objectId:   objectId,
	}
}

// Execute executes the request
//
//	@return ObjectiveConversationPostRead200Response
func (a *ObjectiveConversationPostAPIService) ObjectiveConversationPostReadExecute(r ApiObjectiveConversationPostReadRequest) (*ObjectiveConversationPostRead200Response, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *ObjectiveConversationPostRead200Response
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ObjectiveConversationPostAPIService.ObjectiveConversationPostRead")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/slm/webservice/v2.0/objectiveconversationpost/{objectId}"
	localVarPath = strings.Replace(localVarPath, "{"+"objectId"+"}", url.PathEscape(parameterValueToString(r.objectId, "objectId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.compact != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "compact", r.compact, "form", "")
	} else {
		var defaultValue bool = true
		r.compact = &defaultValue
	}
	if r.fetch != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "fetch", r.fetch, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiObjectiveConversationPostUpdateRequest struct {
	ctx                               context.Context
	ApiService                        *ObjectiveConversationPostAPIService
	objectId                          string
	objectiveConversationPostMutation *ObjectiveConversationPostMutation
}

// ObjectiveConversationPost
func (r ApiObjectiveConversationPostUpdateRequest) ObjectiveConversationPostMutation(objectiveConversationPostMutation ObjectiveConversationPostMutation) ApiObjectiveConversationPostUpdateRequest {
	r.objectiveConversationPostMutation = &objectiveConversationPostMutation
	return r
}

func (r ApiObjectiveConversationPostUpdateRequest) Execute() (*ObjectiveConversationPostRead200Response, *http.Response, error) {
	return r.ApiService.ObjectiveConversationPostUpdateExecute(r)
}

/*
ObjectiveConversationPostUpdate ObjectiveConversationPost Update

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param objectId objectId
	@return ApiObjectiveConversationPostUpdateRequest
*/
func (a *ObjectiveConversationPostAPIService) ObjectiveConversationPostUpdate(ctx context.Context, objectId string) ApiObjectiveConversationPostUpdateRequest {
	return ApiObjectiveConversationPostUpdateRequest{
		ApiService: a,
		ctx:        ctx,
		objectId:   objectId,
	}
}

// Execute executes the request
//
//	@return ObjectiveConversationPostRead200Response
func (a *ObjectiveConversationPostAPIService) ObjectiveConversationPostUpdateExecute(r ApiObjectiveConversationPostUpdateRequest) (*ObjectiveConversationPostRead200Response, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPost
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *ObjectiveConversationPostRead200Response
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ObjectiveConversationPostAPIService.ObjectiveConversationPostUpdate")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/slm/webservice/v2.0/objectiveconversationpost/{objectId}"
	localVarPath = strings.Replace(localVarPath, "{"+"objectId"+"}", url.PathEscape(parameterValueToString(r.objectId, "objectId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.objectiveConversationPostMutation == nil {
		return localVarReturnValue, nil, reportError("objectiveConversationPostMutation is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.objectiveConversationPostMutation
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
