/*
Rally WebService API

Rally Open API docs

API version: v2.0
Contact: support@rallydev.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the TimeEntryValue type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TimeEntryValue{}

// TimeEntryValue TimeEntryValue
type TimeEntryValue struct {
	// Creation Date
	CreationDate *string `json:"CreationDate,omitempty"`
	// Date Val
	DateVal *string `json:"DateVal,omitempty"`
	// Hours
	Hours *float32 `json:"Hours,omitempty"`
	// Last Updated
	LastUpdated *string `json:"LastUpdated,omitempty"`
	// Object ID
	ObjectID *int64 `json:"ObjectID,omitempty"`
	// ObjectUUID
	ObjectUUID *string `json:"ObjectUUID,omitempty"`
	RevisionHistory *RevisionHistoryRef `json:"RevisionHistory,omitempty"`
	Subscription *SubscriptionRef `json:"Subscription,omitempty"`
	TimeEntryItem *TimeEntryItemRef `json:"TimeEntryItem,omitempty"`
	// VersionId
	VersionId *string `json:"VersionId,omitempty"`
	Workspace *WorkspaceRef `json:"Workspace,omitempty"`
	Warnings []string `json:"Warnings,omitempty"`
	Errors []string `json:"Errors,omitempty"`
}

// NewTimeEntryValue instantiates a new TimeEntryValue object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTimeEntryValue() *TimeEntryValue {
	this := TimeEntryValue{}
	return &this
}

// NewTimeEntryValueWithDefaults instantiates a new TimeEntryValue object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTimeEntryValueWithDefaults() *TimeEntryValue {
	this := TimeEntryValue{}
	return &this
}

// GetCreationDate returns the CreationDate field value if set, zero value otherwise.
func (o *TimeEntryValue) GetCreationDate() string {
	if o == nil || IsNil(o.CreationDate) {
		var ret string
		return ret
	}
	return *o.CreationDate
}

// GetCreationDateOk returns a tuple with the CreationDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimeEntryValue) GetCreationDateOk() (*string, bool) {
	if o == nil || IsNil(o.CreationDate) {
		return nil, false
	}
	return o.CreationDate, true
}

// HasCreationDate returns a boolean if a field has been set.
func (o *TimeEntryValue) HasCreationDate() bool {
	if o != nil && !IsNil(o.CreationDate) {
		return true
	}

	return false
}

// SetCreationDate gets a reference to the given string and assigns it to the CreationDate field.
func (o *TimeEntryValue) SetCreationDate(v string) {
	o.CreationDate = &v
}

// GetDateVal returns the DateVal field value if set, zero value otherwise.
func (o *TimeEntryValue) GetDateVal() string {
	if o == nil || IsNil(o.DateVal) {
		var ret string
		return ret
	}
	return *o.DateVal
}

// GetDateValOk returns a tuple with the DateVal field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimeEntryValue) GetDateValOk() (*string, bool) {
	if o == nil || IsNil(o.DateVal) {
		return nil, false
	}
	return o.DateVal, true
}

// HasDateVal returns a boolean if a field has been set.
func (o *TimeEntryValue) HasDateVal() bool {
	if o != nil && !IsNil(o.DateVal) {
		return true
	}

	return false
}

// SetDateVal gets a reference to the given string and assigns it to the DateVal field.
func (o *TimeEntryValue) SetDateVal(v string) {
	o.DateVal = &v
}

// GetHours returns the Hours field value if set, zero value otherwise.
func (o *TimeEntryValue) GetHours() float32 {
	if o == nil || IsNil(o.Hours) {
		var ret float32
		return ret
	}
	return *o.Hours
}

// GetHoursOk returns a tuple with the Hours field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimeEntryValue) GetHoursOk() (*float32, bool) {
	if o == nil || IsNil(o.Hours) {
		return nil, false
	}
	return o.Hours, true
}

// HasHours returns a boolean if a field has been set.
func (o *TimeEntryValue) HasHours() bool {
	if o != nil && !IsNil(o.Hours) {
		return true
	}

	return false
}

// SetHours gets a reference to the given float32 and assigns it to the Hours field.
func (o *TimeEntryValue) SetHours(v float32) {
	o.Hours = &v
}

// GetLastUpdated returns the LastUpdated field value if set, zero value otherwise.
func (o *TimeEntryValue) GetLastUpdated() string {
	if o == nil || IsNil(o.LastUpdated) {
		var ret string
		return ret
	}
	return *o.LastUpdated
}

// GetLastUpdatedOk returns a tuple with the LastUpdated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimeEntryValue) GetLastUpdatedOk() (*string, bool) {
	if o == nil || IsNil(o.LastUpdated) {
		return nil, false
	}
	return o.LastUpdated, true
}

// HasLastUpdated returns a boolean if a field has been set.
func (o *TimeEntryValue) HasLastUpdated() bool {
	if o != nil && !IsNil(o.LastUpdated) {
		return true
	}

	return false
}

// SetLastUpdated gets a reference to the given string and assigns it to the LastUpdated field.
func (o *TimeEntryValue) SetLastUpdated(v string) {
	o.LastUpdated = &v
}

// GetObjectID returns the ObjectID field value if set, zero value otherwise.
func (o *TimeEntryValue) GetObjectID() int64 {
	if o == nil || IsNil(o.ObjectID) {
		var ret int64
		return ret
	}
	return *o.ObjectID
}

// GetObjectIDOk returns a tuple with the ObjectID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimeEntryValue) GetObjectIDOk() (*int64, bool) {
	if o == nil || IsNil(o.ObjectID) {
		return nil, false
	}
	return o.ObjectID, true
}

// HasObjectID returns a boolean if a field has been set.
func (o *TimeEntryValue) HasObjectID() bool {
	if o != nil && !IsNil(o.ObjectID) {
		return true
	}

	return false
}

// SetObjectID gets a reference to the given int64 and assigns it to the ObjectID field.
func (o *TimeEntryValue) SetObjectID(v int64) {
	o.ObjectID = &v
}

// GetObjectUUID returns the ObjectUUID field value if set, zero value otherwise.
func (o *TimeEntryValue) GetObjectUUID() string {
	if o == nil || IsNil(o.ObjectUUID) {
		var ret string
		return ret
	}
	return *o.ObjectUUID
}

// GetObjectUUIDOk returns a tuple with the ObjectUUID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimeEntryValue) GetObjectUUIDOk() (*string, bool) {
	if o == nil || IsNil(o.ObjectUUID) {
		return nil, false
	}
	return o.ObjectUUID, true
}

// HasObjectUUID returns a boolean if a field has been set.
func (o *TimeEntryValue) HasObjectUUID() bool {
	if o != nil && !IsNil(o.ObjectUUID) {
		return true
	}

	return false
}

// SetObjectUUID gets a reference to the given string and assigns it to the ObjectUUID field.
func (o *TimeEntryValue) SetObjectUUID(v string) {
	o.ObjectUUID = &v
}

// GetRevisionHistory returns the RevisionHistory field value if set, zero value otherwise.
func (o *TimeEntryValue) GetRevisionHistory() RevisionHistoryRef {
	if o == nil || IsNil(o.RevisionHistory) {
		var ret RevisionHistoryRef
		return ret
	}
	return *o.RevisionHistory
}

// GetRevisionHistoryOk returns a tuple with the RevisionHistory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimeEntryValue) GetRevisionHistoryOk() (*RevisionHistoryRef, bool) {
	if o == nil || IsNil(o.RevisionHistory) {
		return nil, false
	}
	return o.RevisionHistory, true
}

// HasRevisionHistory returns a boolean if a field has been set.
func (o *TimeEntryValue) HasRevisionHistory() bool {
	if o != nil && !IsNil(o.RevisionHistory) {
		return true
	}

	return false
}

// SetRevisionHistory gets a reference to the given RevisionHistoryRef and assigns it to the RevisionHistory field.
func (o *TimeEntryValue) SetRevisionHistory(v RevisionHistoryRef) {
	o.RevisionHistory = &v
}

// GetSubscription returns the Subscription field value if set, zero value otherwise.
func (o *TimeEntryValue) GetSubscription() SubscriptionRef {
	if o == nil || IsNil(o.Subscription) {
		var ret SubscriptionRef
		return ret
	}
	return *o.Subscription
}

// GetSubscriptionOk returns a tuple with the Subscription field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimeEntryValue) GetSubscriptionOk() (*SubscriptionRef, bool) {
	if o == nil || IsNil(o.Subscription) {
		return nil, false
	}
	return o.Subscription, true
}

// HasSubscription returns a boolean if a field has been set.
func (o *TimeEntryValue) HasSubscription() bool {
	if o != nil && !IsNil(o.Subscription) {
		return true
	}

	return false
}

// SetSubscription gets a reference to the given SubscriptionRef and assigns it to the Subscription field.
func (o *TimeEntryValue) SetSubscription(v SubscriptionRef) {
	o.Subscription = &v
}

// GetTimeEntryItem returns the TimeEntryItem field value if set, zero value otherwise.
func (o *TimeEntryValue) GetTimeEntryItem() TimeEntryItemRef {
	if o == nil || IsNil(o.TimeEntryItem) {
		var ret TimeEntryItemRef
		return ret
	}
	return *o.TimeEntryItem
}

// GetTimeEntryItemOk returns a tuple with the TimeEntryItem field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimeEntryValue) GetTimeEntryItemOk() (*TimeEntryItemRef, bool) {
	if o == nil || IsNil(o.TimeEntryItem) {
		return nil, false
	}
	return o.TimeEntryItem, true
}

// HasTimeEntryItem returns a boolean if a field has been set.
func (o *TimeEntryValue) HasTimeEntryItem() bool {
	if o != nil && !IsNil(o.TimeEntryItem) {
		return true
	}

	return false
}

// SetTimeEntryItem gets a reference to the given TimeEntryItemRef and assigns it to the TimeEntryItem field.
func (o *TimeEntryValue) SetTimeEntryItem(v TimeEntryItemRef) {
	o.TimeEntryItem = &v
}

// GetVersionId returns the VersionId field value if set, zero value otherwise.
func (o *TimeEntryValue) GetVersionId() string {
	if o == nil || IsNil(o.VersionId) {
		var ret string
		return ret
	}
	return *o.VersionId
}

// GetVersionIdOk returns a tuple with the VersionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimeEntryValue) GetVersionIdOk() (*string, bool) {
	if o == nil || IsNil(o.VersionId) {
		return nil, false
	}
	return o.VersionId, true
}

// HasVersionId returns a boolean if a field has been set.
func (o *TimeEntryValue) HasVersionId() bool {
	if o != nil && !IsNil(o.VersionId) {
		return true
	}

	return false
}

// SetVersionId gets a reference to the given string and assigns it to the VersionId field.
func (o *TimeEntryValue) SetVersionId(v string) {
	o.VersionId = &v
}

// GetWorkspace returns the Workspace field value if set, zero value otherwise.
func (o *TimeEntryValue) GetWorkspace() WorkspaceRef {
	if o == nil || IsNil(o.Workspace) {
		var ret WorkspaceRef
		return ret
	}
	return *o.Workspace
}

// GetWorkspaceOk returns a tuple with the Workspace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimeEntryValue) GetWorkspaceOk() (*WorkspaceRef, bool) {
	if o == nil || IsNil(o.Workspace) {
		return nil, false
	}
	return o.Workspace, true
}

// HasWorkspace returns a boolean if a field has been set.
func (o *TimeEntryValue) HasWorkspace() bool {
	if o != nil && !IsNil(o.Workspace) {
		return true
	}

	return false
}

// SetWorkspace gets a reference to the given WorkspaceRef and assigns it to the Workspace field.
func (o *TimeEntryValue) SetWorkspace(v WorkspaceRef) {
	o.Workspace = &v
}

// GetWarnings returns the Warnings field value if set, zero value otherwise.
func (o *TimeEntryValue) GetWarnings() []string {
	if o == nil || IsNil(o.Warnings) {
		var ret []string
		return ret
	}
	return o.Warnings
}

// GetWarningsOk returns a tuple with the Warnings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimeEntryValue) GetWarningsOk() ([]string, bool) {
	if o == nil || IsNil(o.Warnings) {
		return nil, false
	}
	return o.Warnings, true
}

// HasWarnings returns a boolean if a field has been set.
func (o *TimeEntryValue) HasWarnings() bool {
	if o != nil && !IsNil(o.Warnings) {
		return true
	}

	return false
}

// SetWarnings gets a reference to the given []string and assigns it to the Warnings field.
func (o *TimeEntryValue) SetWarnings(v []string) {
	o.Warnings = v
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *TimeEntryValue) GetErrors() []string {
	if o == nil || IsNil(o.Errors) {
		var ret []string
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimeEntryValue) GetErrorsOk() ([]string, bool) {
	if o == nil || IsNil(o.Errors) {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *TimeEntryValue) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []string and assigns it to the Errors field.
func (o *TimeEntryValue) SetErrors(v []string) {
	o.Errors = v
}

func (o TimeEntryValue) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TimeEntryValue) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CreationDate) {
		toSerialize["CreationDate"] = o.CreationDate
	}
	if !IsNil(o.DateVal) {
		toSerialize["DateVal"] = o.DateVal
	}
	if !IsNil(o.Hours) {
		toSerialize["Hours"] = o.Hours
	}
	if !IsNil(o.LastUpdated) {
		toSerialize["LastUpdated"] = o.LastUpdated
	}
	if !IsNil(o.ObjectID) {
		toSerialize["ObjectID"] = o.ObjectID
	}
	if !IsNil(o.ObjectUUID) {
		toSerialize["ObjectUUID"] = o.ObjectUUID
	}
	if !IsNil(o.RevisionHistory) {
		toSerialize["RevisionHistory"] = o.RevisionHistory
	}
	if !IsNil(o.Subscription) {
		toSerialize["Subscription"] = o.Subscription
	}
	if !IsNil(o.TimeEntryItem) {
		toSerialize["TimeEntryItem"] = o.TimeEntryItem
	}
	if !IsNil(o.VersionId) {
		toSerialize["VersionId"] = o.VersionId
	}
	if !IsNil(o.Workspace) {
		toSerialize["Workspace"] = o.Workspace
	}
	if !IsNil(o.Warnings) {
		toSerialize["Warnings"] = o.Warnings
	}
	if !IsNil(o.Errors) {
		toSerialize["Errors"] = o.Errors
	}
	return toSerialize, nil
}

type NullableTimeEntryValue struct {
	value *TimeEntryValue
	isSet bool
}

func (v NullableTimeEntryValue) Get() *TimeEntryValue {
	return v.value
}

func (v *NullableTimeEntryValue) Set(val *TimeEntryValue) {
	v.value = val
	v.isSet = true
}

func (v NullableTimeEntryValue) IsSet() bool {
	return v.isSet
}

func (v *NullableTimeEntryValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTimeEntryValue(val *TimeEntryValue) *NullableTimeEntryValue {
	return &NullableTimeEntryValue{value: val, isSet: true}
}

func (v NullableTimeEntryValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTimeEntryValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


