/*
Rally WebService API

Rally Open API docs

API version: v2.0
Contact: support@rallydev.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ObjectiveMutationObjective type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ObjectiveMutationObjective{}

// ObjectiveMutationObjective Objective
type ObjectiveMutationObjective struct {
	AssociatedWork *Collection `json:"AssociatedWork,omitempty"`
	// Description
	Description *string `json:"Description,omitempty"`
	// Display Color
	DisplayColor *string `json:"DisplayColor,omitempty"`
	// Interim Target Date Template
	InterimTargetDateTemplate *string `json:"InterimTargetDateTemplate,omitempty"`
	KeyResults *Collection `json:"KeyResults,omitempty"`
	// Name
	Name *string `json:"Name,omitempty"`
	Owner *UserRef `json:"Owner,omitempty"`
	Projects *Collection `json:"Projects,omitempty"`
	// Score
	Score *float32 `json:"Score,omitempty"`
	// Start Date
	StartDate *string `json:"StartDate,omitempty"`
	State *StateRef `json:"State,omitempty"`
	Tags *Collection `json:"Tags,omitempty"`
	// Target Date
	TargetDate *string `json:"TargetDate,omitempty"`
	Workspace *WorkspaceRef `json:"Workspace,omitempty"`
	// Integration Mappings
	CIntegrationMappings *string `json:"c_IntegrationMappings,omitempty"`
	// Source
	CSource *string `json:"c_Source,omitempty"`
	Warnings []string `json:"Warnings,omitempty"`
	Errors []string `json:"Errors,omitempty"`
}

// NewObjectiveMutationObjective instantiates a new ObjectiveMutationObjective object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewObjectiveMutationObjective() *ObjectiveMutationObjective {
	this := ObjectiveMutationObjective{}
	return &this
}

// NewObjectiveMutationObjectiveWithDefaults instantiates a new ObjectiveMutationObjective object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewObjectiveMutationObjectiveWithDefaults() *ObjectiveMutationObjective {
	this := ObjectiveMutationObjective{}
	return &this
}

// GetAssociatedWork returns the AssociatedWork field value if set, zero value otherwise.
func (o *ObjectiveMutationObjective) GetAssociatedWork() Collection {
	if o == nil || IsNil(o.AssociatedWork) {
		var ret Collection
		return ret
	}
	return *o.AssociatedWork
}

// GetAssociatedWorkOk returns a tuple with the AssociatedWork field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ObjectiveMutationObjective) GetAssociatedWorkOk() (*Collection, bool) {
	if o == nil || IsNil(o.AssociatedWork) {
		return nil, false
	}
	return o.AssociatedWork, true
}

// HasAssociatedWork returns a boolean if a field has been set.
func (o *ObjectiveMutationObjective) HasAssociatedWork() bool {
	if o != nil && !IsNil(o.AssociatedWork) {
		return true
	}

	return false
}

// SetAssociatedWork gets a reference to the given Collection and assigns it to the AssociatedWork field.
func (o *ObjectiveMutationObjective) SetAssociatedWork(v Collection) {
	o.AssociatedWork = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ObjectiveMutationObjective) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ObjectiveMutationObjective) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ObjectiveMutationObjective) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ObjectiveMutationObjective) SetDescription(v string) {
	o.Description = &v
}

// GetDisplayColor returns the DisplayColor field value if set, zero value otherwise.
func (o *ObjectiveMutationObjective) GetDisplayColor() string {
	if o == nil || IsNil(o.DisplayColor) {
		var ret string
		return ret
	}
	return *o.DisplayColor
}

// GetDisplayColorOk returns a tuple with the DisplayColor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ObjectiveMutationObjective) GetDisplayColorOk() (*string, bool) {
	if o == nil || IsNil(o.DisplayColor) {
		return nil, false
	}
	return o.DisplayColor, true
}

// HasDisplayColor returns a boolean if a field has been set.
func (o *ObjectiveMutationObjective) HasDisplayColor() bool {
	if o != nil && !IsNil(o.DisplayColor) {
		return true
	}

	return false
}

// SetDisplayColor gets a reference to the given string and assigns it to the DisplayColor field.
func (o *ObjectiveMutationObjective) SetDisplayColor(v string) {
	o.DisplayColor = &v
}

// GetInterimTargetDateTemplate returns the InterimTargetDateTemplate field value if set, zero value otherwise.
func (o *ObjectiveMutationObjective) GetInterimTargetDateTemplate() string {
	if o == nil || IsNil(o.InterimTargetDateTemplate) {
		var ret string
		return ret
	}
	return *o.InterimTargetDateTemplate
}

// GetInterimTargetDateTemplateOk returns a tuple with the InterimTargetDateTemplate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ObjectiveMutationObjective) GetInterimTargetDateTemplateOk() (*string, bool) {
	if o == nil || IsNil(o.InterimTargetDateTemplate) {
		return nil, false
	}
	return o.InterimTargetDateTemplate, true
}

// HasInterimTargetDateTemplate returns a boolean if a field has been set.
func (o *ObjectiveMutationObjective) HasInterimTargetDateTemplate() bool {
	if o != nil && !IsNil(o.InterimTargetDateTemplate) {
		return true
	}

	return false
}

// SetInterimTargetDateTemplate gets a reference to the given string and assigns it to the InterimTargetDateTemplate field.
func (o *ObjectiveMutationObjective) SetInterimTargetDateTemplate(v string) {
	o.InterimTargetDateTemplate = &v
}

// GetKeyResults returns the KeyResults field value if set, zero value otherwise.
func (o *ObjectiveMutationObjective) GetKeyResults() Collection {
	if o == nil || IsNil(o.KeyResults) {
		var ret Collection
		return ret
	}
	return *o.KeyResults
}

// GetKeyResultsOk returns a tuple with the KeyResults field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ObjectiveMutationObjective) GetKeyResultsOk() (*Collection, bool) {
	if o == nil || IsNil(o.KeyResults) {
		return nil, false
	}
	return o.KeyResults, true
}

// HasKeyResults returns a boolean if a field has been set.
func (o *ObjectiveMutationObjective) HasKeyResults() bool {
	if o != nil && !IsNil(o.KeyResults) {
		return true
	}

	return false
}

// SetKeyResults gets a reference to the given Collection and assigns it to the KeyResults field.
func (o *ObjectiveMutationObjective) SetKeyResults(v Collection) {
	o.KeyResults = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ObjectiveMutationObjective) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ObjectiveMutationObjective) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ObjectiveMutationObjective) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ObjectiveMutationObjective) SetName(v string) {
	o.Name = &v
}

// GetOwner returns the Owner field value if set, zero value otherwise.
func (o *ObjectiveMutationObjective) GetOwner() UserRef {
	if o == nil || IsNil(o.Owner) {
		var ret UserRef
		return ret
	}
	return *o.Owner
}

// GetOwnerOk returns a tuple with the Owner field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ObjectiveMutationObjective) GetOwnerOk() (*UserRef, bool) {
	if o == nil || IsNil(o.Owner) {
		return nil, false
	}
	return o.Owner, true
}

// HasOwner returns a boolean if a field has been set.
func (o *ObjectiveMutationObjective) HasOwner() bool {
	if o != nil && !IsNil(o.Owner) {
		return true
	}

	return false
}

// SetOwner gets a reference to the given UserRef and assigns it to the Owner field.
func (o *ObjectiveMutationObjective) SetOwner(v UserRef) {
	o.Owner = &v
}

// GetProjects returns the Projects field value if set, zero value otherwise.
func (o *ObjectiveMutationObjective) GetProjects() Collection {
	if o == nil || IsNil(o.Projects) {
		var ret Collection
		return ret
	}
	return *o.Projects
}

// GetProjectsOk returns a tuple with the Projects field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ObjectiveMutationObjective) GetProjectsOk() (*Collection, bool) {
	if o == nil || IsNil(o.Projects) {
		return nil, false
	}
	return o.Projects, true
}

// HasProjects returns a boolean if a field has been set.
func (o *ObjectiveMutationObjective) HasProjects() bool {
	if o != nil && !IsNil(o.Projects) {
		return true
	}

	return false
}

// SetProjects gets a reference to the given Collection and assigns it to the Projects field.
func (o *ObjectiveMutationObjective) SetProjects(v Collection) {
	o.Projects = &v
}

// GetScore returns the Score field value if set, zero value otherwise.
func (o *ObjectiveMutationObjective) GetScore() float32 {
	if o == nil || IsNil(o.Score) {
		var ret float32
		return ret
	}
	return *o.Score
}

// GetScoreOk returns a tuple with the Score field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ObjectiveMutationObjective) GetScoreOk() (*float32, bool) {
	if o == nil || IsNil(o.Score) {
		return nil, false
	}
	return o.Score, true
}

// HasScore returns a boolean if a field has been set.
func (o *ObjectiveMutationObjective) HasScore() bool {
	if o != nil && !IsNil(o.Score) {
		return true
	}

	return false
}

// SetScore gets a reference to the given float32 and assigns it to the Score field.
func (o *ObjectiveMutationObjective) SetScore(v float32) {
	o.Score = &v
}

// GetStartDate returns the StartDate field value if set, zero value otherwise.
func (o *ObjectiveMutationObjective) GetStartDate() string {
	if o == nil || IsNil(o.StartDate) {
		var ret string
		return ret
	}
	return *o.StartDate
}

// GetStartDateOk returns a tuple with the StartDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ObjectiveMutationObjective) GetStartDateOk() (*string, bool) {
	if o == nil || IsNil(o.StartDate) {
		return nil, false
	}
	return o.StartDate, true
}

// HasStartDate returns a boolean if a field has been set.
func (o *ObjectiveMutationObjective) HasStartDate() bool {
	if o != nil && !IsNil(o.StartDate) {
		return true
	}

	return false
}

// SetStartDate gets a reference to the given string and assigns it to the StartDate field.
func (o *ObjectiveMutationObjective) SetStartDate(v string) {
	o.StartDate = &v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *ObjectiveMutationObjective) GetState() StateRef {
	if o == nil || IsNil(o.State) {
		var ret StateRef
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ObjectiveMutationObjective) GetStateOk() (*StateRef, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *ObjectiveMutationObjective) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given StateRef and assigns it to the State field.
func (o *ObjectiveMutationObjective) SetState(v StateRef) {
	o.State = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *ObjectiveMutationObjective) GetTags() Collection {
	if o == nil || IsNil(o.Tags) {
		var ret Collection
		return ret
	}
	return *o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ObjectiveMutationObjective) GetTagsOk() (*Collection, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *ObjectiveMutationObjective) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given Collection and assigns it to the Tags field.
func (o *ObjectiveMutationObjective) SetTags(v Collection) {
	o.Tags = &v
}

// GetTargetDate returns the TargetDate field value if set, zero value otherwise.
func (o *ObjectiveMutationObjective) GetTargetDate() string {
	if o == nil || IsNil(o.TargetDate) {
		var ret string
		return ret
	}
	return *o.TargetDate
}

// GetTargetDateOk returns a tuple with the TargetDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ObjectiveMutationObjective) GetTargetDateOk() (*string, bool) {
	if o == nil || IsNil(o.TargetDate) {
		return nil, false
	}
	return o.TargetDate, true
}

// HasTargetDate returns a boolean if a field has been set.
func (o *ObjectiveMutationObjective) HasTargetDate() bool {
	if o != nil && !IsNil(o.TargetDate) {
		return true
	}

	return false
}

// SetTargetDate gets a reference to the given string and assigns it to the TargetDate field.
func (o *ObjectiveMutationObjective) SetTargetDate(v string) {
	o.TargetDate = &v
}

// GetWorkspace returns the Workspace field value if set, zero value otherwise.
func (o *ObjectiveMutationObjective) GetWorkspace() WorkspaceRef {
	if o == nil || IsNil(o.Workspace) {
		var ret WorkspaceRef
		return ret
	}
	return *o.Workspace
}

// GetWorkspaceOk returns a tuple with the Workspace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ObjectiveMutationObjective) GetWorkspaceOk() (*WorkspaceRef, bool) {
	if o == nil || IsNil(o.Workspace) {
		return nil, false
	}
	return o.Workspace, true
}

// HasWorkspace returns a boolean if a field has been set.
func (o *ObjectiveMutationObjective) HasWorkspace() bool {
	if o != nil && !IsNil(o.Workspace) {
		return true
	}

	return false
}

// SetWorkspace gets a reference to the given WorkspaceRef and assigns it to the Workspace field.
func (o *ObjectiveMutationObjective) SetWorkspace(v WorkspaceRef) {
	o.Workspace = &v
}

// GetCIntegrationMappings returns the CIntegrationMappings field value if set, zero value otherwise.
func (o *ObjectiveMutationObjective) GetCIntegrationMappings() string {
	if o == nil || IsNil(o.CIntegrationMappings) {
		var ret string
		return ret
	}
	return *o.CIntegrationMappings
}

// GetCIntegrationMappingsOk returns a tuple with the CIntegrationMappings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ObjectiveMutationObjective) GetCIntegrationMappingsOk() (*string, bool) {
	if o == nil || IsNil(o.CIntegrationMappings) {
		return nil, false
	}
	return o.CIntegrationMappings, true
}

// HasCIntegrationMappings returns a boolean if a field has been set.
func (o *ObjectiveMutationObjective) HasCIntegrationMappings() bool {
	if o != nil && !IsNil(o.CIntegrationMappings) {
		return true
	}

	return false
}

// SetCIntegrationMappings gets a reference to the given string and assigns it to the CIntegrationMappings field.
func (o *ObjectiveMutationObjective) SetCIntegrationMappings(v string) {
	o.CIntegrationMappings = &v
}

// GetCSource returns the CSource field value if set, zero value otherwise.
func (o *ObjectiveMutationObjective) GetCSource() string {
	if o == nil || IsNil(o.CSource) {
		var ret string
		return ret
	}
	return *o.CSource
}

// GetCSourceOk returns a tuple with the CSource field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ObjectiveMutationObjective) GetCSourceOk() (*string, bool) {
	if o == nil || IsNil(o.CSource) {
		return nil, false
	}
	return o.CSource, true
}

// HasCSource returns a boolean if a field has been set.
func (o *ObjectiveMutationObjective) HasCSource() bool {
	if o != nil && !IsNil(o.CSource) {
		return true
	}

	return false
}

// SetCSource gets a reference to the given string and assigns it to the CSource field.
func (o *ObjectiveMutationObjective) SetCSource(v string) {
	o.CSource = &v
}

// GetWarnings returns the Warnings field value if set, zero value otherwise.
func (o *ObjectiveMutationObjective) GetWarnings() []string {
	if o == nil || IsNil(o.Warnings) {
		var ret []string
		return ret
	}
	return o.Warnings
}

// GetWarningsOk returns a tuple with the Warnings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ObjectiveMutationObjective) GetWarningsOk() ([]string, bool) {
	if o == nil || IsNil(o.Warnings) {
		return nil, false
	}
	return o.Warnings, true
}

// HasWarnings returns a boolean if a field has been set.
func (o *ObjectiveMutationObjective) HasWarnings() bool {
	if o != nil && !IsNil(o.Warnings) {
		return true
	}

	return false
}

// SetWarnings gets a reference to the given []string and assigns it to the Warnings field.
func (o *ObjectiveMutationObjective) SetWarnings(v []string) {
	o.Warnings = v
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *ObjectiveMutationObjective) GetErrors() []string {
	if o == nil || IsNil(o.Errors) {
		var ret []string
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ObjectiveMutationObjective) GetErrorsOk() ([]string, bool) {
	if o == nil || IsNil(o.Errors) {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *ObjectiveMutationObjective) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []string and assigns it to the Errors field.
func (o *ObjectiveMutationObjective) SetErrors(v []string) {
	o.Errors = v
}

func (o ObjectiveMutationObjective) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ObjectiveMutationObjective) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AssociatedWork) {
		toSerialize["AssociatedWork"] = o.AssociatedWork
	}
	if !IsNil(o.Description) {
		toSerialize["Description"] = o.Description
	}
	if !IsNil(o.DisplayColor) {
		toSerialize["DisplayColor"] = o.DisplayColor
	}
	if !IsNil(o.InterimTargetDateTemplate) {
		toSerialize["InterimTargetDateTemplate"] = o.InterimTargetDateTemplate
	}
	if !IsNil(o.KeyResults) {
		toSerialize["KeyResults"] = o.KeyResults
	}
	if !IsNil(o.Name) {
		toSerialize["Name"] = o.Name
	}
	if !IsNil(o.Owner) {
		toSerialize["Owner"] = o.Owner
	}
	if !IsNil(o.Projects) {
		toSerialize["Projects"] = o.Projects
	}
	if !IsNil(o.Score) {
		toSerialize["Score"] = o.Score
	}
	if !IsNil(o.StartDate) {
		toSerialize["StartDate"] = o.StartDate
	}
	if !IsNil(o.State) {
		toSerialize["State"] = o.State
	}
	if !IsNil(o.Tags) {
		toSerialize["Tags"] = o.Tags
	}
	if !IsNil(o.TargetDate) {
		toSerialize["TargetDate"] = o.TargetDate
	}
	if !IsNil(o.Workspace) {
		toSerialize["Workspace"] = o.Workspace
	}
	if !IsNil(o.CIntegrationMappings) {
		toSerialize["c_IntegrationMappings"] = o.CIntegrationMappings
	}
	if !IsNil(o.CSource) {
		toSerialize["c_Source"] = o.CSource
	}
	if !IsNil(o.Warnings) {
		toSerialize["Warnings"] = o.Warnings
	}
	if !IsNil(o.Errors) {
		toSerialize["Errors"] = o.Errors
	}
	return toSerialize, nil
}

type NullableObjectiveMutationObjective struct {
	value *ObjectiveMutationObjective
	isSet bool
}

func (v NullableObjectiveMutationObjective) Get() *ObjectiveMutationObjective {
	return v.value
}

func (v *NullableObjectiveMutationObjective) Set(val *ObjectiveMutationObjective) {
	v.value = val
	v.isSet = true
}

func (v NullableObjectiveMutationObjective) IsSet() bool {
	return v.isSet
}

func (v *NullableObjectiveMutationObjective) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableObjectiveMutationObjective(val *ObjectiveMutationObjective) *NullableObjectiveMutationObjective {
	return &NullableObjectiveMutationObjective{value: val, isSet: true}
}

func (v NullableObjectiveMutationObjective) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableObjectiveMutationObjective) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


