/*
Rally WebService API

Rally Open API docs

API version: v2.0
Contact: support@rallydev.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the VSMProductPortfolioItemMutation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VSMProductPortfolioItemMutation{}

// VSMProductPortfolioItemMutation VSMProductPortfolioItem
type VSMProductPortfolioItemMutation struct {
	VSMProductPortfolioItem *VSMProductPortfolioItemMutationVSMProductPortfolioItem `json:"VSMProductPortfolioItem,omitempty"`
}

// NewVSMProductPortfolioItemMutation instantiates a new VSMProductPortfolioItemMutation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVSMProductPortfolioItemMutation() *VSMProductPortfolioItemMutation {
	this := VSMProductPortfolioItemMutation{}
	return &this
}

// NewVSMProductPortfolioItemMutationWithDefaults instantiates a new VSMProductPortfolioItemMutation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVSMProductPortfolioItemMutationWithDefaults() *VSMProductPortfolioItemMutation {
	this := VSMProductPortfolioItemMutation{}
	return &this
}

// GetVSMProductPortfolioItem returns the VSMProductPortfolioItem field value if set, zero value otherwise.
func (o *VSMProductPortfolioItemMutation) GetVSMProductPortfolioItem() VSMProductPortfolioItemMutationVSMProductPortfolioItem {
	if o == nil || IsNil(o.VSMProductPortfolioItem) {
		var ret VSMProductPortfolioItemMutationVSMProductPortfolioItem
		return ret
	}
	return *o.VSMProductPortfolioItem
}

// GetVSMProductPortfolioItemOk returns a tuple with the VSMProductPortfolioItem field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VSMProductPortfolioItemMutation) GetVSMProductPortfolioItemOk() (*VSMProductPortfolioItemMutationVSMProductPortfolioItem, bool) {
	if o == nil || IsNil(o.VSMProductPortfolioItem) {
		return nil, false
	}
	return o.VSMProductPortfolioItem, true
}

// HasVSMProductPortfolioItem returns a boolean if a field has been set.
func (o *VSMProductPortfolioItemMutation) HasVSMProductPortfolioItem() bool {
	if o != nil && !IsNil(o.VSMProductPortfolioItem) {
		return true
	}

	return false
}

// SetVSMProductPortfolioItem gets a reference to the given VSMProductPortfolioItemMutationVSMProductPortfolioItem and assigns it to the VSMProductPortfolioItem field.
func (o *VSMProductPortfolioItemMutation) SetVSMProductPortfolioItem(v VSMProductPortfolioItemMutationVSMProductPortfolioItem) {
	o.VSMProductPortfolioItem = &v
}

func (o VSMProductPortfolioItemMutation) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VSMProductPortfolioItemMutation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.VSMProductPortfolioItem) {
		toSerialize["VSMProductPortfolioItem"] = o.VSMProductPortfolioItem
	}
	return toSerialize, nil
}

type NullableVSMProductPortfolioItemMutation struct {
	value *VSMProductPortfolioItemMutation
	isSet bool
}

func (v NullableVSMProductPortfolioItemMutation) Get() *VSMProductPortfolioItemMutation {
	return v.value
}

func (v *NullableVSMProductPortfolioItemMutation) Set(val *VSMProductPortfolioItemMutation) {
	v.value = val
	v.isSet = true
}

func (v NullableVSMProductPortfolioItemMutation) IsSet() bool {
	return v.isSet
}

func (v *NullableVSMProductPortfolioItemMutation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVSMProductPortfolioItemMutation(val *VSMProductPortfolioItemMutation) *NullableVSMProductPortfolioItemMutation {
	return &NullableVSMProductPortfolioItemMutation{value: val, isSet: true}
}

func (v NullableVSMProductPortfolioItemMutation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVSMProductPortfolioItemMutation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
