/*
Rally WebService API

Rally Open API docs

API version: v2.0
Contact: support@rallydev.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the PreferenceCreate200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PreferenceCreate200Response{}

// PreferenceCreate200Response struct for PreferenceCreate200Response
type PreferenceCreate200Response struct {
	CreateResult *PreferenceCreate200ResponseCreateResult `json:"CreateResult,omitempty"`
}

// NewPreferenceCreate200Response instantiates a new PreferenceCreate200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPreferenceCreate200Response() *PreferenceCreate200Response {
	this := PreferenceCreate200Response{}
	return &this
}

// NewPreferenceCreate200ResponseWithDefaults instantiates a new PreferenceCreate200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPreferenceCreate200ResponseWithDefaults() *PreferenceCreate200Response {
	this := PreferenceCreate200Response{}
	return &this
}

// GetCreateResult returns the CreateResult field value if set, zero value otherwise.
func (o *PreferenceCreate200Response) GetCreateResult() PreferenceCreate200ResponseCreateResult {
	if o == nil || IsNil(o.CreateResult) {
		var ret PreferenceCreate200ResponseCreateResult
		return ret
	}
	return *o.CreateResult
}

// GetCreateResultOk returns a tuple with the CreateResult field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PreferenceCreate200Response) GetCreateResultOk() (*PreferenceCreate200ResponseCreateResult, bool) {
	if o == nil || IsNil(o.CreateResult) {
		return nil, false
	}
	return o.CreateResult, true
}

// HasCreateResult returns a boolean if a field has been set.
func (o *PreferenceCreate200Response) HasCreateResult() bool {
	if o != nil && !IsNil(o.CreateResult) {
		return true
	}

	return false
}

// SetCreateResult gets a reference to the given PreferenceCreate200ResponseCreateResult and assigns it to the CreateResult field.
func (o *PreferenceCreate200Response) SetCreateResult(v PreferenceCreate200ResponseCreateResult) {
	o.CreateResult = &v
}

func (o PreferenceCreate200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PreferenceCreate200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CreateResult) {
		toSerialize["CreateResult"] = o.CreateResult
	}
	return toSerialize, nil
}

type NullablePreferenceCreate200Response struct {
	value *PreferenceCreate200Response
	isSet bool
}

func (v NullablePreferenceCreate200Response) Get() *PreferenceCreate200Response {
	return v.value
}

func (v *NullablePreferenceCreate200Response) Set(val *PreferenceCreate200Response) {
	v.value = val
	v.isSet = true
}

func (v NullablePreferenceCreate200Response) IsSet() bool {
	return v.isSet
}

func (v *NullablePreferenceCreate200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePreferenceCreate200Response(val *PreferenceCreate200Response) *NullablePreferenceCreate200Response {
	return &NullablePreferenceCreate200Response{value: val, isSet: true}
}

func (v NullablePreferenceCreate200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePreferenceCreate200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
