/*
Rally WebService API

Rally Open API docs

API version: v2.0
Contact: support@rallydev.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the VSMMetricPortfolioItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VSMMetricPortfolioItem{}

// VSMMetricPortfolioItem VSMMetricPortfolioItem
type VSMMetricPortfolioItem struct {
	// Creation Date
	CreationDate *string `json:"CreationDate,omitempty"`
	// Last Update Date
	LastUpdateDate *string `json:"LastUpdateDate,omitempty"`
	Metric *ObjectRef `json:"Metric,omitempty"`
	// Object ID
	ObjectID *int64 `json:"ObjectID,omitempty"`
	// ObjectUUID
	ObjectUUID *string `json:"ObjectUUID,omitempty"`
	PortfolioItem *PortfolioItemRef `json:"PortfolioItem,omitempty"`
	Subscription *SubscriptionRef `json:"Subscription,omitempty"`
	// VersionId
	VersionId *string `json:"VersionId,omitempty"`
	Workspace *WorkspaceRef `json:"Workspace,omitempty"`
	Warnings []string `json:"Warnings,omitempty"`
	Errors []string `json:"Errors,omitempty"`
}

// NewVSMMetricPortfolioItem instantiates a new VSMMetricPortfolioItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVSMMetricPortfolioItem() *VSMMetricPortfolioItem {
	this := VSMMetricPortfolioItem{}
	return &this
}

// NewVSMMetricPortfolioItemWithDefaults instantiates a new VSMMetricPortfolioItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVSMMetricPortfolioItemWithDefaults() *VSMMetricPortfolioItem {
	this := VSMMetricPortfolioItem{}
	return &this
}

// GetCreationDate returns the CreationDate field value if set, zero value otherwise.
func (o *VSMMetricPortfolioItem) GetCreationDate() string {
	if o == nil || IsNil(o.CreationDate) {
		var ret string
		return ret
	}
	return *o.CreationDate
}

// GetCreationDateOk returns a tuple with the CreationDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VSMMetricPortfolioItem) GetCreationDateOk() (*string, bool) {
	if o == nil || IsNil(o.CreationDate) {
		return nil, false
	}
	return o.CreationDate, true
}

// HasCreationDate returns a boolean if a field has been set.
func (o *VSMMetricPortfolioItem) HasCreationDate() bool {
	if o != nil && !IsNil(o.CreationDate) {
		return true
	}

	return false
}

// SetCreationDate gets a reference to the given string and assigns it to the CreationDate field.
func (o *VSMMetricPortfolioItem) SetCreationDate(v string) {
	o.CreationDate = &v
}

// GetLastUpdateDate returns the LastUpdateDate field value if set, zero value otherwise.
func (o *VSMMetricPortfolioItem) GetLastUpdateDate() string {
	if o == nil || IsNil(o.LastUpdateDate) {
		var ret string
		return ret
	}
	return *o.LastUpdateDate
}

// GetLastUpdateDateOk returns a tuple with the LastUpdateDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VSMMetricPortfolioItem) GetLastUpdateDateOk() (*string, bool) {
	if o == nil || IsNil(o.LastUpdateDate) {
		return nil, false
	}
	return o.LastUpdateDate, true
}

// HasLastUpdateDate returns a boolean if a field has been set.
func (o *VSMMetricPortfolioItem) HasLastUpdateDate() bool {
	if o != nil && !IsNil(o.LastUpdateDate) {
		return true
	}

	return false
}

// SetLastUpdateDate gets a reference to the given string and assigns it to the LastUpdateDate field.
func (o *VSMMetricPortfolioItem) SetLastUpdateDate(v string) {
	o.LastUpdateDate = &v
}

// GetMetric returns the Metric field value if set, zero value otherwise.
func (o *VSMMetricPortfolioItem) GetMetric() ObjectRef {
	if o == nil || IsNil(o.Metric) {
		var ret ObjectRef
		return ret
	}
	return *o.Metric
}

// GetMetricOk returns a tuple with the Metric field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VSMMetricPortfolioItem) GetMetricOk() (*ObjectRef, bool) {
	if o == nil || IsNil(o.Metric) {
		return nil, false
	}
	return o.Metric, true
}

// HasMetric returns a boolean if a field has been set.
func (o *VSMMetricPortfolioItem) HasMetric() bool {
	if o != nil && !IsNil(o.Metric) {
		return true
	}

	return false
}

// SetMetric gets a reference to the given ObjectRef and assigns it to the Metric field.
func (o *VSMMetricPortfolioItem) SetMetric(v ObjectRef) {
	o.Metric = &v
}

// GetObjectID returns the ObjectID field value if set, zero value otherwise.
func (o *VSMMetricPortfolioItem) GetObjectID() int64 {
	if o == nil || IsNil(o.ObjectID) {
		var ret int64
		return ret
	}
	return *o.ObjectID
}

// GetObjectIDOk returns a tuple with the ObjectID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VSMMetricPortfolioItem) GetObjectIDOk() (*int64, bool) {
	if o == nil || IsNil(o.ObjectID) {
		return nil, false
	}
	return o.ObjectID, true
}

// HasObjectID returns a boolean if a field has been set.
func (o *VSMMetricPortfolioItem) HasObjectID() bool {
	if o != nil && !IsNil(o.ObjectID) {
		return true
	}

	return false
}

// SetObjectID gets a reference to the given int64 and assigns it to the ObjectID field.
func (o *VSMMetricPortfolioItem) SetObjectID(v int64) {
	o.ObjectID = &v
}

// GetObjectUUID returns the ObjectUUID field value if set, zero value otherwise.
func (o *VSMMetricPortfolioItem) GetObjectUUID() string {
	if o == nil || IsNil(o.ObjectUUID) {
		var ret string
		return ret
	}
	return *o.ObjectUUID
}

// GetObjectUUIDOk returns a tuple with the ObjectUUID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VSMMetricPortfolioItem) GetObjectUUIDOk() (*string, bool) {
	if o == nil || IsNil(o.ObjectUUID) {
		return nil, false
	}
	return o.ObjectUUID, true
}

// HasObjectUUID returns a boolean if a field has been set.
func (o *VSMMetricPortfolioItem) HasObjectUUID() bool {
	if o != nil && !IsNil(o.ObjectUUID) {
		return true
	}

	return false
}

// SetObjectUUID gets a reference to the given string and assigns it to the ObjectUUID field.
func (o *VSMMetricPortfolioItem) SetObjectUUID(v string) {
	o.ObjectUUID = &v
}

// GetPortfolioItem returns the PortfolioItem field value if set, zero value otherwise.
func (o *VSMMetricPortfolioItem) GetPortfolioItem() PortfolioItemRef {
	if o == nil || IsNil(o.PortfolioItem) {
		var ret PortfolioItemRef
		return ret
	}
	return *o.PortfolioItem
}

// GetPortfolioItemOk returns a tuple with the PortfolioItem field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VSMMetricPortfolioItem) GetPortfolioItemOk() (*PortfolioItemRef, bool) {
	if o == nil || IsNil(o.PortfolioItem) {
		return nil, false
	}
	return o.PortfolioItem, true
}

// HasPortfolioItem returns a boolean if a field has been set.
func (o *VSMMetricPortfolioItem) HasPortfolioItem() bool {
	if o != nil && !IsNil(o.PortfolioItem) {
		return true
	}

	return false
}

// SetPortfolioItem gets a reference to the given PortfolioItemRef and assigns it to the PortfolioItem field.
func (o *VSMMetricPortfolioItem) SetPortfolioItem(v PortfolioItemRef) {
	o.PortfolioItem = &v
}

// GetSubscription returns the Subscription field value if set, zero value otherwise.
func (o *VSMMetricPortfolioItem) GetSubscription() SubscriptionRef {
	if o == nil || IsNil(o.Subscription) {
		var ret SubscriptionRef
		return ret
	}
	return *o.Subscription
}

// GetSubscriptionOk returns a tuple with the Subscription field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VSMMetricPortfolioItem) GetSubscriptionOk() (*SubscriptionRef, bool) {
	if o == nil || IsNil(o.Subscription) {
		return nil, false
	}
	return o.Subscription, true
}

// HasSubscription returns a boolean if a field has been set.
func (o *VSMMetricPortfolioItem) HasSubscription() bool {
	if o != nil && !IsNil(o.Subscription) {
		return true
	}

	return false
}

// SetSubscription gets a reference to the given SubscriptionRef and assigns it to the Subscription field.
func (o *VSMMetricPortfolioItem) SetSubscription(v SubscriptionRef) {
	o.Subscription = &v
}

// GetVersionId returns the VersionId field value if set, zero value otherwise.
func (o *VSMMetricPortfolioItem) GetVersionId() string {
	if o == nil || IsNil(o.VersionId) {
		var ret string
		return ret
	}
	return *o.VersionId
}

// GetVersionIdOk returns a tuple with the VersionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VSMMetricPortfolioItem) GetVersionIdOk() (*string, bool) {
	if o == nil || IsNil(o.VersionId) {
		return nil, false
	}
	return o.VersionId, true
}

// HasVersionId returns a boolean if a field has been set.
func (o *VSMMetricPortfolioItem) HasVersionId() bool {
	if o != nil && !IsNil(o.VersionId) {
		return true
	}

	return false
}

// SetVersionId gets a reference to the given string and assigns it to the VersionId field.
func (o *VSMMetricPortfolioItem) SetVersionId(v string) {
	o.VersionId = &v
}

// GetWorkspace returns the Workspace field value if set, zero value otherwise.
func (o *VSMMetricPortfolioItem) GetWorkspace() WorkspaceRef {
	if o == nil || IsNil(o.Workspace) {
		var ret WorkspaceRef
		return ret
	}
	return *o.Workspace
}

// GetWorkspaceOk returns a tuple with the Workspace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VSMMetricPortfolioItem) GetWorkspaceOk() (*WorkspaceRef, bool) {
	if o == nil || IsNil(o.Workspace) {
		return nil, false
	}
	return o.Workspace, true
}

// HasWorkspace returns a boolean if a field has been set.
func (o *VSMMetricPortfolioItem) HasWorkspace() bool {
	if o != nil && !IsNil(o.Workspace) {
		return true
	}

	return false
}

// SetWorkspace gets a reference to the given WorkspaceRef and assigns it to the Workspace field.
func (o *VSMMetricPortfolioItem) SetWorkspace(v WorkspaceRef) {
	o.Workspace = &v
}

// GetWarnings returns the Warnings field value if set, zero value otherwise.
func (o *VSMMetricPortfolioItem) GetWarnings() []string {
	if o == nil || IsNil(o.Warnings) {
		var ret []string
		return ret
	}
	return o.Warnings
}

// GetWarningsOk returns a tuple with the Warnings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VSMMetricPortfolioItem) GetWarningsOk() ([]string, bool) {
	if o == nil || IsNil(o.Warnings) {
		return nil, false
	}
	return o.Warnings, true
}

// HasWarnings returns a boolean if a field has been set.
func (o *VSMMetricPortfolioItem) HasWarnings() bool {
	if o != nil && !IsNil(o.Warnings) {
		return true
	}

	return false
}

// SetWarnings gets a reference to the given []string and assigns it to the Warnings field.
func (o *VSMMetricPortfolioItem) SetWarnings(v []string) {
	o.Warnings = v
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *VSMMetricPortfolioItem) GetErrors() []string {
	if o == nil || IsNil(o.Errors) {
		var ret []string
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VSMMetricPortfolioItem) GetErrorsOk() ([]string, bool) {
	if o == nil || IsNil(o.Errors) {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *VSMMetricPortfolioItem) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []string and assigns it to the Errors field.
func (o *VSMMetricPortfolioItem) SetErrors(v []string) {
	o.Errors = v
}

func (o VSMMetricPortfolioItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VSMMetricPortfolioItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CreationDate) {
		toSerialize["CreationDate"] = o.CreationDate
	}
	if !IsNil(o.LastUpdateDate) {
		toSerialize["LastUpdateDate"] = o.LastUpdateDate
	}
	if !IsNil(o.Metric) {
		toSerialize["Metric"] = o.Metric
	}
	if !IsNil(o.ObjectID) {
		toSerialize["ObjectID"] = o.ObjectID
	}
	if !IsNil(o.ObjectUUID) {
		toSerialize["ObjectUUID"] = o.ObjectUUID
	}
	if !IsNil(o.PortfolioItem) {
		toSerialize["PortfolioItem"] = o.PortfolioItem
	}
	if !IsNil(o.Subscription) {
		toSerialize["Subscription"] = o.Subscription
	}
	if !IsNil(o.VersionId) {
		toSerialize["VersionId"] = o.VersionId
	}
	if !IsNil(o.Workspace) {
		toSerialize["Workspace"] = o.Workspace
	}
	if !IsNil(o.Warnings) {
		toSerialize["Warnings"] = o.Warnings
	}
	if !IsNil(o.Errors) {
		toSerialize["Errors"] = o.Errors
	}
	return toSerialize, nil
}

type NullableVSMMetricPortfolioItem struct {
	value *VSMMetricPortfolioItem
	isSet bool
}

func (v NullableVSMMetricPortfolioItem) Get() *VSMMetricPortfolioItem {
	return v.value
}

func (v *NullableVSMMetricPortfolioItem) Set(val *VSMMetricPortfolioItem) {
	v.value = val
	v.isSet = true
}

func (v NullableVSMMetricPortfolioItem) IsSet() bool {
	return v.isSet
}

func (v *NullableVSMMetricPortfolioItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVSMMetricPortfolioItem(val *VSMMetricPortfolioItem) *NullableVSMMetricPortfolioItem {
	return &NullableVSMMetricPortfolioItem{value: val, isSet: true}
}

func (v NullableVSMMetricPortfolioItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVSMMetricPortfolioItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


