/*
Rally WebService API

Rally Open API docs

API version: v2.0
Contact: support@rallydev.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the RecycleBinEntry type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RecycleBinEntry{}

// RecycleBinEntry RecycleBinEntry
type RecycleBinEntry struct {
	DeletedBy *UserRef `json:"DeletedBy,omitempty"`
	// Deletion Date
	DeletionDate *string `json:"DeletionDate,omitempty"`
	// ID
	ID *string `json:"ID,omitempty"`
	// ItemOID
	ItemOID *int64 `json:"ItemOID,omitempty"`
	// Name
	Name *string `json:"Name,omitempty"`
	// Object ID
	ObjectID *int64 `json:"ObjectID,omitempty"`
	// ObjectUUID
	ObjectUUID *string `json:"ObjectUUID,omitempty"`
	Subscription *SubscriptionRef `json:"Subscription,omitempty"`
	Type *TypeDefinitionRef `json:"Type,omitempty"`
	// VersionId
	VersionId *string `json:"VersionId,omitempty"`
	Workspace *WorkspaceRef `json:"Workspace,omitempty"`
	Warnings []string `json:"Warnings,omitempty"`
	Errors []string `json:"Errors,omitempty"`
}

// NewRecycleBinEntry instantiates a new RecycleBinEntry object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRecycleBinEntry() *RecycleBinEntry {
	this := RecycleBinEntry{}
	return &this
}

// NewRecycleBinEntryWithDefaults instantiates a new RecycleBinEntry object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRecycleBinEntryWithDefaults() *RecycleBinEntry {
	this := RecycleBinEntry{}
	return &this
}

// GetDeletedBy returns the DeletedBy field value if set, zero value otherwise.
func (o *RecycleBinEntry) GetDeletedBy() UserRef {
	if o == nil || IsNil(o.DeletedBy) {
		var ret UserRef
		return ret
	}
	return *o.DeletedBy
}

// GetDeletedByOk returns a tuple with the DeletedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecycleBinEntry) GetDeletedByOk() (*UserRef, bool) {
	if o == nil || IsNil(o.DeletedBy) {
		return nil, false
	}
	return o.DeletedBy, true
}

// HasDeletedBy returns a boolean if a field has been set.
func (o *RecycleBinEntry) HasDeletedBy() bool {
	if o != nil && !IsNil(o.DeletedBy) {
		return true
	}

	return false
}

// SetDeletedBy gets a reference to the given UserRef and assigns it to the DeletedBy field.
func (o *RecycleBinEntry) SetDeletedBy(v UserRef) {
	o.DeletedBy = &v
}

// GetDeletionDate returns the DeletionDate field value if set, zero value otherwise.
func (o *RecycleBinEntry) GetDeletionDate() string {
	if o == nil || IsNil(o.DeletionDate) {
		var ret string
		return ret
	}
	return *o.DeletionDate
}

// GetDeletionDateOk returns a tuple with the DeletionDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecycleBinEntry) GetDeletionDateOk() (*string, bool) {
	if o == nil || IsNil(o.DeletionDate) {
		return nil, false
	}
	return o.DeletionDate, true
}

// HasDeletionDate returns a boolean if a field has been set.
func (o *RecycleBinEntry) HasDeletionDate() bool {
	if o != nil && !IsNil(o.DeletionDate) {
		return true
	}

	return false
}

// SetDeletionDate gets a reference to the given string and assigns it to the DeletionDate field.
func (o *RecycleBinEntry) SetDeletionDate(v string) {
	o.DeletionDate = &v
}

// GetID returns the ID field value if set, zero value otherwise.
func (o *RecycleBinEntry) GetID() string {
	if o == nil || IsNil(o.ID) {
		var ret string
		return ret
	}
	return *o.ID
}

// GetIDOk returns a tuple with the ID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecycleBinEntry) GetIDOk() (*string, bool) {
	if o == nil || IsNil(o.ID) {
		return nil, false
	}
	return o.ID, true
}

// HasID returns a boolean if a field has been set.
func (o *RecycleBinEntry) HasID() bool {
	if o != nil && !IsNil(o.ID) {
		return true
	}

	return false
}

// SetID gets a reference to the given string and assigns it to the ID field.
func (o *RecycleBinEntry) SetID(v string) {
	o.ID = &v
}

// GetItemOID returns the ItemOID field value if set, zero value otherwise.
func (o *RecycleBinEntry) GetItemOID() int64 {
	if o == nil || IsNil(o.ItemOID) {
		var ret int64
		return ret
	}
	return *o.ItemOID
}

// GetItemOIDOk returns a tuple with the ItemOID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecycleBinEntry) GetItemOIDOk() (*int64, bool) {
	if o == nil || IsNil(o.ItemOID) {
		return nil, false
	}
	return o.ItemOID, true
}

// HasItemOID returns a boolean if a field has been set.
func (o *RecycleBinEntry) HasItemOID() bool {
	if o != nil && !IsNil(o.ItemOID) {
		return true
	}

	return false
}

// SetItemOID gets a reference to the given int64 and assigns it to the ItemOID field.
func (o *RecycleBinEntry) SetItemOID(v int64) {
	o.ItemOID = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *RecycleBinEntry) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecycleBinEntry) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *RecycleBinEntry) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *RecycleBinEntry) SetName(v string) {
	o.Name = &v
}

// GetObjectID returns the ObjectID field value if set, zero value otherwise.
func (o *RecycleBinEntry) GetObjectID() int64 {
	if o == nil || IsNil(o.ObjectID) {
		var ret int64
		return ret
	}
	return *o.ObjectID
}

// GetObjectIDOk returns a tuple with the ObjectID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecycleBinEntry) GetObjectIDOk() (*int64, bool) {
	if o == nil || IsNil(o.ObjectID) {
		return nil, false
	}
	return o.ObjectID, true
}

// HasObjectID returns a boolean if a field has been set.
func (o *RecycleBinEntry) HasObjectID() bool {
	if o != nil && !IsNil(o.ObjectID) {
		return true
	}

	return false
}

// SetObjectID gets a reference to the given int64 and assigns it to the ObjectID field.
func (o *RecycleBinEntry) SetObjectID(v int64) {
	o.ObjectID = &v
}

// GetObjectUUID returns the ObjectUUID field value if set, zero value otherwise.
func (o *RecycleBinEntry) GetObjectUUID() string {
	if o == nil || IsNil(o.ObjectUUID) {
		var ret string
		return ret
	}
	return *o.ObjectUUID
}

// GetObjectUUIDOk returns a tuple with the ObjectUUID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecycleBinEntry) GetObjectUUIDOk() (*string, bool) {
	if o == nil || IsNil(o.ObjectUUID) {
		return nil, false
	}
	return o.ObjectUUID, true
}

// HasObjectUUID returns a boolean if a field has been set.
func (o *RecycleBinEntry) HasObjectUUID() bool {
	if o != nil && !IsNil(o.ObjectUUID) {
		return true
	}

	return false
}

// SetObjectUUID gets a reference to the given string and assigns it to the ObjectUUID field.
func (o *RecycleBinEntry) SetObjectUUID(v string) {
	o.ObjectUUID = &v
}

// GetSubscription returns the Subscription field value if set, zero value otherwise.
func (o *RecycleBinEntry) GetSubscription() SubscriptionRef {
	if o == nil || IsNil(o.Subscription) {
		var ret SubscriptionRef
		return ret
	}
	return *o.Subscription
}

// GetSubscriptionOk returns a tuple with the Subscription field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecycleBinEntry) GetSubscriptionOk() (*SubscriptionRef, bool) {
	if o == nil || IsNil(o.Subscription) {
		return nil, false
	}
	return o.Subscription, true
}

// HasSubscription returns a boolean if a field has been set.
func (o *RecycleBinEntry) HasSubscription() bool {
	if o != nil && !IsNil(o.Subscription) {
		return true
	}

	return false
}

// SetSubscription gets a reference to the given SubscriptionRef and assigns it to the Subscription field.
func (o *RecycleBinEntry) SetSubscription(v SubscriptionRef) {
	o.Subscription = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *RecycleBinEntry) GetType() TypeDefinitionRef {
	if o == nil || IsNil(o.Type) {
		var ret TypeDefinitionRef
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecycleBinEntry) GetTypeOk() (*TypeDefinitionRef, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *RecycleBinEntry) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given TypeDefinitionRef and assigns it to the Type field.
func (o *RecycleBinEntry) SetType(v TypeDefinitionRef) {
	o.Type = &v
}

// GetVersionId returns the VersionId field value if set, zero value otherwise.
func (o *RecycleBinEntry) GetVersionId() string {
	if o == nil || IsNil(o.VersionId) {
		var ret string
		return ret
	}
	return *o.VersionId
}

// GetVersionIdOk returns a tuple with the VersionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecycleBinEntry) GetVersionIdOk() (*string, bool) {
	if o == nil || IsNil(o.VersionId) {
		return nil, false
	}
	return o.VersionId, true
}

// HasVersionId returns a boolean if a field has been set.
func (o *RecycleBinEntry) HasVersionId() bool {
	if o != nil && !IsNil(o.VersionId) {
		return true
	}

	return false
}

// SetVersionId gets a reference to the given string and assigns it to the VersionId field.
func (o *RecycleBinEntry) SetVersionId(v string) {
	o.VersionId = &v
}

// GetWorkspace returns the Workspace field value if set, zero value otherwise.
func (o *RecycleBinEntry) GetWorkspace() WorkspaceRef {
	if o == nil || IsNil(o.Workspace) {
		var ret WorkspaceRef
		return ret
	}
	return *o.Workspace
}

// GetWorkspaceOk returns a tuple with the Workspace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecycleBinEntry) GetWorkspaceOk() (*WorkspaceRef, bool) {
	if o == nil || IsNil(o.Workspace) {
		return nil, false
	}
	return o.Workspace, true
}

// HasWorkspace returns a boolean if a field has been set.
func (o *RecycleBinEntry) HasWorkspace() bool {
	if o != nil && !IsNil(o.Workspace) {
		return true
	}

	return false
}

// SetWorkspace gets a reference to the given WorkspaceRef and assigns it to the Workspace field.
func (o *RecycleBinEntry) SetWorkspace(v WorkspaceRef) {
	o.Workspace = &v
}

// GetWarnings returns the Warnings field value if set, zero value otherwise.
func (o *RecycleBinEntry) GetWarnings() []string {
	if o == nil || IsNil(o.Warnings) {
		var ret []string
		return ret
	}
	return o.Warnings
}

// GetWarningsOk returns a tuple with the Warnings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecycleBinEntry) GetWarningsOk() ([]string, bool) {
	if o == nil || IsNil(o.Warnings) {
		return nil, false
	}
	return o.Warnings, true
}

// HasWarnings returns a boolean if a field has been set.
func (o *RecycleBinEntry) HasWarnings() bool {
	if o != nil && !IsNil(o.Warnings) {
		return true
	}

	return false
}

// SetWarnings gets a reference to the given []string and assigns it to the Warnings field.
func (o *RecycleBinEntry) SetWarnings(v []string) {
	o.Warnings = v
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *RecycleBinEntry) GetErrors() []string {
	if o == nil || IsNil(o.Errors) {
		var ret []string
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecycleBinEntry) GetErrorsOk() ([]string, bool) {
	if o == nil || IsNil(o.Errors) {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *RecycleBinEntry) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []string and assigns it to the Errors field.
func (o *RecycleBinEntry) SetErrors(v []string) {
	o.Errors = v
}

func (o RecycleBinEntry) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RecycleBinEntry) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DeletedBy) {
		toSerialize["DeletedBy"] = o.DeletedBy
	}
	if !IsNil(o.DeletionDate) {
		toSerialize["DeletionDate"] = o.DeletionDate
	}
	if !IsNil(o.ID) {
		toSerialize["ID"] = o.ID
	}
	if !IsNil(o.ItemOID) {
		toSerialize["ItemOID"] = o.ItemOID
	}
	if !IsNil(o.Name) {
		toSerialize["Name"] = o.Name
	}
	if !IsNil(o.ObjectID) {
		toSerialize["ObjectID"] = o.ObjectID
	}
	if !IsNil(o.ObjectUUID) {
		toSerialize["ObjectUUID"] = o.ObjectUUID
	}
	if !IsNil(o.Subscription) {
		toSerialize["Subscription"] = o.Subscription
	}
	if !IsNil(o.Type) {
		toSerialize["Type"] = o.Type
	}
	if !IsNil(o.VersionId) {
		toSerialize["VersionId"] = o.VersionId
	}
	if !IsNil(o.Workspace) {
		toSerialize["Workspace"] = o.Workspace
	}
	if !IsNil(o.Warnings) {
		toSerialize["Warnings"] = o.Warnings
	}
	if !IsNil(o.Errors) {
		toSerialize["Errors"] = o.Errors
	}
	return toSerialize, nil
}

type NullableRecycleBinEntry struct {
	value *RecycleBinEntry
	isSet bool
}

func (v NullableRecycleBinEntry) Get() *RecycleBinEntry {
	return v.value
}

func (v *NullableRecycleBinEntry) Set(val *RecycleBinEntry) {
	v.value = val
	v.isSet = true
}

func (v NullableRecycleBinEntry) IsSet() bool {
	return v.isSet
}

func (v *NullableRecycleBinEntry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRecycleBinEntry(val *RecycleBinEntry) *NullableRecycleBinEntry {
	return &NullableRecycleBinEntry{value: val, isSet: true}
}

func (v NullableRecycleBinEntry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRecycleBinEntry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


