/*
Rally WebService API

Rally Open API docs

API version: v2.0
Contact: support@rallydev.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the RiskMutationRisk type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RiskMutationRisk{}

// RiskMutationRisk Risk
type RiskMutationRisk struct {
	Attachments *Collection `json:"Attachments,omitempty"`
	Changesets  *Collection `json:"Changesets,omitempty"`
	// Description
	Description *string `json:"Description,omitempty"`
	// Display Color
	DisplayColor *string `json:"DisplayColor,omitempty"`
	// Expedite
	Expedite *bool `json:"Expedite,omitempty"`
	// Financial Work Type
	FinancialWorkType *string       `json:"FinancialWorkType,omitempty"`
	FlowState         *FlowStateRef `json:"FlowState,omitempty"`
	// Impact
	Impact    *string       `json:"Impact,omitempty"`
	Iteration *IterationRef `json:"Iteration,omitempty"`
	// Iteration Value
	IterationValue *string     `json:"IterationValue,omitempty"`
	Milestones     *Collection `json:"Milestones,omitempty"`
	// Name
	Name *string `json:"Name,omitempty"`
	// Notes
	Notes *string  `json:"Notes,omitempty"`
	Owner *UserRef `json:"Owner,omitempty"`
	// Plan Estimate
	PlanEstimate *float32 `json:"PlanEstimate,omitempty"`
	// Probability
	Probability *string     `json:"Probability,omitempty"`
	Project     *ProjectRef `json:"Project,omitempty"`
	Release     *ReleaseRef `json:"Release,omitempty"`
	// Release Value
	ReleaseValue *string `json:"ReleaseValue,omitempty"`
	// Resolution
	Resolution *string `json:"Resolution,omitempty"`
	// Response
	Response *string `json:"Response,omitempty"`
	// Schedule State
	ScheduleState *string `json:"ScheduleState,omitempty"`
	// Size Of Loss
	SizeOfLoss *int64 `json:"SizeOfLoss,omitempty"`
	// State
	State             *string       `json:"State,omitempty"`
	SubmittedBy       *UserRef      `json:"SubmittedBy,omitempty"`
	Tags              *Collection   `json:"Tags,omitempty"`
	WorkItemsAffected *Collection   `json:"WorkItemsAffected,omitempty"`
	Workspace         *WorkspaceRef `json:"Workspace,omitempty"`
	// Attention Level
	CAttentionLevel *string `json:"c_AttentionLevel,omitempty"`
	// Item Type
	CItemType *string `json:"c_ItemType,omitempty"`
	// MIAMI
	CMIAMI *bool `json:"c_MIAMI,omitempty"`
	// Next Steps
	CNextSteps *string `json:"c_NextSteps,omitempty"`
	// Owner (Non-Rally User)
	COwnerNonRallyUser *string `json:"c_OwnerNonRallyUser,omitempty"`
	// Target Date
	CTargetDate *string `json:"c_TargetDate,omitempty"`
	// Workload CI ID
	CWorkloadCIID *string  `json:"c_WorkloadCIID,omitempty"`
	Warnings      []string `json:"Warnings,omitempty"`
	Errors        []string `json:"Errors,omitempty"`
}

// NewRiskMutationRisk instantiates a new RiskMutationRisk object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRiskMutationRisk() *RiskMutationRisk {
	this := RiskMutationRisk{}
	var impact string = "None"
	this.Impact = &impact
	var probability string = "None"
	this.Probability = &probability
	var response string = "None"
	this.Response = &response
	var scheduleState string = "Defined"
	this.ScheduleState = &scheduleState
	var state string = "None"
	this.State = &state
	return &this
}

// NewRiskMutationRiskWithDefaults instantiates a new RiskMutationRisk object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRiskMutationRiskWithDefaults() *RiskMutationRisk {
	this := RiskMutationRisk{}
	var impact string = "None"
	this.Impact = &impact
	var probability string = "None"
	this.Probability = &probability
	var response string = "None"
	this.Response = &response
	var scheduleState string = "Defined"
	this.ScheduleState = &scheduleState
	var state string = "None"
	this.State = &state
	return &this
}

// GetAttachments returns the Attachments field value if set, zero value otherwise.
func (o *RiskMutationRisk) GetAttachments() Collection {
	if o == nil || IsNil(o.Attachments) {
		var ret Collection
		return ret
	}
	return *o.Attachments
}

// GetAttachmentsOk returns a tuple with the Attachments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskMutationRisk) GetAttachmentsOk() (*Collection, bool) {
	if o == nil || IsNil(o.Attachments) {
		return nil, false
	}
	return o.Attachments, true
}

// HasAttachments returns a boolean if a field has been set.
func (o *RiskMutationRisk) HasAttachments() bool {
	if o != nil && !IsNil(o.Attachments) {
		return true
	}

	return false
}

// SetAttachments gets a reference to the given Collection and assigns it to the Attachments field.
func (o *RiskMutationRisk) SetAttachments(v Collection) {
	o.Attachments = &v
}

// GetChangesets returns the Changesets field value if set, zero value otherwise.
func (o *RiskMutationRisk) GetChangesets() Collection {
	if o == nil || IsNil(o.Changesets) {
		var ret Collection
		return ret
	}
	return *o.Changesets
}

// GetChangesetsOk returns a tuple with the Changesets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskMutationRisk) GetChangesetsOk() (*Collection, bool) {
	if o == nil || IsNil(o.Changesets) {
		return nil, false
	}
	return o.Changesets, true
}

// HasChangesets returns a boolean if a field has been set.
func (o *RiskMutationRisk) HasChangesets() bool {
	if o != nil && !IsNil(o.Changesets) {
		return true
	}

	return false
}

// SetChangesets gets a reference to the given Collection and assigns it to the Changesets field.
func (o *RiskMutationRisk) SetChangesets(v Collection) {
	o.Changesets = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *RiskMutationRisk) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskMutationRisk) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *RiskMutationRisk) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *RiskMutationRisk) SetDescription(v string) {
	o.Description = &v
}

// GetDisplayColor returns the DisplayColor field value if set, zero value otherwise.
func (o *RiskMutationRisk) GetDisplayColor() string {
	if o == nil || IsNil(o.DisplayColor) {
		var ret string
		return ret
	}
	return *o.DisplayColor
}

// GetDisplayColorOk returns a tuple with the DisplayColor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskMutationRisk) GetDisplayColorOk() (*string, bool) {
	if o == nil || IsNil(o.DisplayColor) {
		return nil, false
	}
	return o.DisplayColor, true
}

// HasDisplayColor returns a boolean if a field has been set.
func (o *RiskMutationRisk) HasDisplayColor() bool {
	if o != nil && !IsNil(o.DisplayColor) {
		return true
	}

	return false
}

// SetDisplayColor gets a reference to the given string and assigns it to the DisplayColor field.
func (o *RiskMutationRisk) SetDisplayColor(v string) {
	o.DisplayColor = &v
}

// GetExpedite returns the Expedite field value if set, zero value otherwise.
func (o *RiskMutationRisk) GetExpedite() bool {
	if o == nil || IsNil(o.Expedite) {
		var ret bool
		return ret
	}
	return *o.Expedite
}

// GetExpediteOk returns a tuple with the Expedite field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskMutationRisk) GetExpediteOk() (*bool, bool) {
	if o == nil || IsNil(o.Expedite) {
		return nil, false
	}
	return o.Expedite, true
}

// HasExpedite returns a boolean if a field has been set.
func (o *RiskMutationRisk) HasExpedite() bool {
	if o != nil && !IsNil(o.Expedite) {
		return true
	}

	return false
}

// SetExpedite gets a reference to the given bool and assigns it to the Expedite field.
func (o *RiskMutationRisk) SetExpedite(v bool) {
	o.Expedite = &v
}

// GetFinancialWorkType returns the FinancialWorkType field value if set, zero value otherwise.
func (o *RiskMutationRisk) GetFinancialWorkType() string {
	if o == nil || IsNil(o.FinancialWorkType) {
		var ret string
		return ret
	}
	return *o.FinancialWorkType
}

// GetFinancialWorkTypeOk returns a tuple with the FinancialWorkType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskMutationRisk) GetFinancialWorkTypeOk() (*string, bool) {
	if o == nil || IsNil(o.FinancialWorkType) {
		return nil, false
	}
	return o.FinancialWorkType, true
}

// HasFinancialWorkType returns a boolean if a field has been set.
func (o *RiskMutationRisk) HasFinancialWorkType() bool {
	if o != nil && !IsNil(o.FinancialWorkType) {
		return true
	}

	return false
}

// SetFinancialWorkType gets a reference to the given string and assigns it to the FinancialWorkType field.
func (o *RiskMutationRisk) SetFinancialWorkType(v string) {
	o.FinancialWorkType = &v
}

// GetFlowState returns the FlowState field value if set, zero value otherwise.
func (o *RiskMutationRisk) GetFlowState() FlowStateRef {
	if o == nil || IsNil(o.FlowState) {
		var ret FlowStateRef
		return ret
	}
	return *o.FlowState
}

// GetFlowStateOk returns a tuple with the FlowState field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskMutationRisk) GetFlowStateOk() (*FlowStateRef, bool) {
	if o == nil || IsNil(o.FlowState) {
		return nil, false
	}
	return o.FlowState, true
}

// HasFlowState returns a boolean if a field has been set.
func (o *RiskMutationRisk) HasFlowState() bool {
	if o != nil && !IsNil(o.FlowState) {
		return true
	}

	return false
}

// SetFlowState gets a reference to the given FlowStateRef and assigns it to the FlowState field.
func (o *RiskMutationRisk) SetFlowState(v FlowStateRef) {
	o.FlowState = &v
}

// GetImpact returns the Impact field value if set, zero value otherwise.
func (o *RiskMutationRisk) GetImpact() string {
	if o == nil || IsNil(o.Impact) {
		var ret string
		return ret
	}
	return *o.Impact
}

// GetImpactOk returns a tuple with the Impact field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskMutationRisk) GetImpactOk() (*string, bool) {
	if o == nil || IsNil(o.Impact) {
		return nil, false
	}
	return o.Impact, true
}

// HasImpact returns a boolean if a field has been set.
func (o *RiskMutationRisk) HasImpact() bool {
	if o != nil && !IsNil(o.Impact) {
		return true
	}

	return false
}

// SetImpact gets a reference to the given string and assigns it to the Impact field.
func (o *RiskMutationRisk) SetImpact(v string) {
	o.Impact = &v
}

// GetIteration returns the Iteration field value if set, zero value otherwise.
func (o *RiskMutationRisk) GetIteration() IterationRef {
	if o == nil || IsNil(o.Iteration) {
		var ret IterationRef
		return ret
	}
	return *o.Iteration
}

// GetIterationOk returns a tuple with the Iteration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskMutationRisk) GetIterationOk() (*IterationRef, bool) {
	if o == nil || IsNil(o.Iteration) {
		return nil, false
	}
	return o.Iteration, true
}

// HasIteration returns a boolean if a field has been set.
func (o *RiskMutationRisk) HasIteration() bool {
	if o != nil && !IsNil(o.Iteration) {
		return true
	}

	return false
}

// SetIteration gets a reference to the given IterationRef and assigns it to the Iteration field.
func (o *RiskMutationRisk) SetIteration(v IterationRef) {
	o.Iteration = &v
}

// GetIterationValue returns the IterationValue field value if set, zero value otherwise.
func (o *RiskMutationRisk) GetIterationValue() string {
	if o == nil || IsNil(o.IterationValue) {
		var ret string
		return ret
	}
	return *o.IterationValue
}

// GetIterationValueOk returns a tuple with the IterationValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskMutationRisk) GetIterationValueOk() (*string, bool) {
	if o == nil || IsNil(o.IterationValue) {
		return nil, false
	}
	return o.IterationValue, true
}

// HasIterationValue returns a boolean if a field has been set.
func (o *RiskMutationRisk) HasIterationValue() bool {
	if o != nil && !IsNil(o.IterationValue) {
		return true
	}

	return false
}

// SetIterationValue gets a reference to the given string and assigns it to the IterationValue field.
func (o *RiskMutationRisk) SetIterationValue(v string) {
	o.IterationValue = &v
}

// GetMilestones returns the Milestones field value if set, zero value otherwise.
func (o *RiskMutationRisk) GetMilestones() Collection {
	if o == nil || IsNil(o.Milestones) {
		var ret Collection
		return ret
	}
	return *o.Milestones
}

// GetMilestonesOk returns a tuple with the Milestones field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskMutationRisk) GetMilestonesOk() (*Collection, bool) {
	if o == nil || IsNil(o.Milestones) {
		return nil, false
	}
	return o.Milestones, true
}

// HasMilestones returns a boolean if a field has been set.
func (o *RiskMutationRisk) HasMilestones() bool {
	if o != nil && !IsNil(o.Milestones) {
		return true
	}

	return false
}

// SetMilestones gets a reference to the given Collection and assigns it to the Milestones field.
func (o *RiskMutationRisk) SetMilestones(v Collection) {
	o.Milestones = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *RiskMutationRisk) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskMutationRisk) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *RiskMutationRisk) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *RiskMutationRisk) SetName(v string) {
	o.Name = &v
}

// GetNotes returns the Notes field value if set, zero value otherwise.
func (o *RiskMutationRisk) GetNotes() string {
	if o == nil || IsNil(o.Notes) {
		var ret string
		return ret
	}
	return *o.Notes
}

// GetNotesOk returns a tuple with the Notes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskMutationRisk) GetNotesOk() (*string, bool) {
	if o == nil || IsNil(o.Notes) {
		return nil, false
	}
	return o.Notes, true
}

// HasNotes returns a boolean if a field has been set.
func (o *RiskMutationRisk) HasNotes() bool {
	if o != nil && !IsNil(o.Notes) {
		return true
	}

	return false
}

// SetNotes gets a reference to the given string and assigns it to the Notes field.
func (o *RiskMutationRisk) SetNotes(v string) {
	o.Notes = &v
}

// GetOwner returns the Owner field value if set, zero value otherwise.
func (o *RiskMutationRisk) GetOwner() UserRef {
	if o == nil || IsNil(o.Owner) {
		var ret UserRef
		return ret
	}
	return *o.Owner
}

// GetOwnerOk returns a tuple with the Owner field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskMutationRisk) GetOwnerOk() (*UserRef, bool) {
	if o == nil || IsNil(o.Owner) {
		return nil, false
	}
	return o.Owner, true
}

// HasOwner returns a boolean if a field has been set.
func (o *RiskMutationRisk) HasOwner() bool {
	if o != nil && !IsNil(o.Owner) {
		return true
	}

	return false
}

// SetOwner gets a reference to the given UserRef and assigns it to the Owner field.
func (o *RiskMutationRisk) SetOwner(v UserRef) {
	o.Owner = &v
}

// GetPlanEstimate returns the PlanEstimate field value if set, zero value otherwise.
func (o *RiskMutationRisk) GetPlanEstimate() float32 {
	if o == nil || IsNil(o.PlanEstimate) {
		var ret float32
		return ret
	}
	return *o.PlanEstimate
}

// GetPlanEstimateOk returns a tuple with the PlanEstimate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskMutationRisk) GetPlanEstimateOk() (*float32, bool) {
	if o == nil || IsNil(o.PlanEstimate) {
		return nil, false
	}
	return o.PlanEstimate, true
}

// HasPlanEstimate returns a boolean if a field has been set.
func (o *RiskMutationRisk) HasPlanEstimate() bool {
	if o != nil && !IsNil(o.PlanEstimate) {
		return true
	}

	return false
}

// SetPlanEstimate gets a reference to the given float32 and assigns it to the PlanEstimate field.
func (o *RiskMutationRisk) SetPlanEstimate(v float32) {
	o.PlanEstimate = &v
}

// GetProbability returns the Probability field value if set, zero value otherwise.
func (o *RiskMutationRisk) GetProbability() string {
	if o == nil || IsNil(o.Probability) {
		var ret string
		return ret
	}
	return *o.Probability
}

// GetProbabilityOk returns a tuple with the Probability field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskMutationRisk) GetProbabilityOk() (*string, bool) {
	if o == nil || IsNil(o.Probability) {
		return nil, false
	}
	return o.Probability, true
}

// HasProbability returns a boolean if a field has been set.
func (o *RiskMutationRisk) HasProbability() bool {
	if o != nil && !IsNil(o.Probability) {
		return true
	}

	return false
}

// SetProbability gets a reference to the given string and assigns it to the Probability field.
func (o *RiskMutationRisk) SetProbability(v string) {
	o.Probability = &v
}

// GetProject returns the Project field value if set, zero value otherwise.
func (o *RiskMutationRisk) GetProject() ProjectRef {
	if o == nil || IsNil(o.Project) {
		var ret ProjectRef
		return ret
	}
	return *o.Project
}

// GetProjectOk returns a tuple with the Project field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskMutationRisk) GetProjectOk() (*ProjectRef, bool) {
	if o == nil || IsNil(o.Project) {
		return nil, false
	}
	return o.Project, true
}

// HasProject returns a boolean if a field has been set.
func (o *RiskMutationRisk) HasProject() bool {
	if o != nil && !IsNil(o.Project) {
		return true
	}

	return false
}

// SetProject gets a reference to the given ProjectRef and assigns it to the Project field.
func (o *RiskMutationRisk) SetProject(v ProjectRef) {
	o.Project = &v
}

// GetRelease returns the Release field value if set, zero value otherwise.
func (o *RiskMutationRisk) GetRelease() ReleaseRef {
	if o == nil || IsNil(o.Release) {
		var ret ReleaseRef
		return ret
	}
	return *o.Release
}

// GetReleaseOk returns a tuple with the Release field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskMutationRisk) GetReleaseOk() (*ReleaseRef, bool) {
	if o == nil || IsNil(o.Release) {
		return nil, false
	}
	return o.Release, true
}

// HasRelease returns a boolean if a field has been set.
func (o *RiskMutationRisk) HasRelease() bool {
	if o != nil && !IsNil(o.Release) {
		return true
	}

	return false
}

// SetRelease gets a reference to the given ReleaseRef and assigns it to the Release field.
func (o *RiskMutationRisk) SetRelease(v ReleaseRef) {
	o.Release = &v
}

// GetReleaseValue returns the ReleaseValue field value if set, zero value otherwise.
func (o *RiskMutationRisk) GetReleaseValue() string {
	if o == nil || IsNil(o.ReleaseValue) {
		var ret string
		return ret
	}
	return *o.ReleaseValue
}

// GetReleaseValueOk returns a tuple with the ReleaseValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskMutationRisk) GetReleaseValueOk() (*string, bool) {
	if o == nil || IsNil(o.ReleaseValue) {
		return nil, false
	}
	return o.ReleaseValue, true
}

// HasReleaseValue returns a boolean if a field has been set.
func (o *RiskMutationRisk) HasReleaseValue() bool {
	if o != nil && !IsNil(o.ReleaseValue) {
		return true
	}

	return false
}

// SetReleaseValue gets a reference to the given string and assigns it to the ReleaseValue field.
func (o *RiskMutationRisk) SetReleaseValue(v string) {
	o.ReleaseValue = &v
}

// GetResolution returns the Resolution field value if set, zero value otherwise.
func (o *RiskMutationRisk) GetResolution() string {
	if o == nil || IsNil(o.Resolution) {
		var ret string
		return ret
	}
	return *o.Resolution
}

// GetResolutionOk returns a tuple with the Resolution field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskMutationRisk) GetResolutionOk() (*string, bool) {
	if o == nil || IsNil(o.Resolution) {
		return nil, false
	}
	return o.Resolution, true
}

// HasResolution returns a boolean if a field has been set.
func (o *RiskMutationRisk) HasResolution() bool {
	if o != nil && !IsNil(o.Resolution) {
		return true
	}

	return false
}

// SetResolution gets a reference to the given string and assigns it to the Resolution field.
func (o *RiskMutationRisk) SetResolution(v string) {
	o.Resolution = &v
}

// GetResponse returns the Response field value if set, zero value otherwise.
func (o *RiskMutationRisk) GetResponse() string {
	if o == nil || IsNil(o.Response) {
		var ret string
		return ret
	}
	return *o.Response
}

// GetResponseOk returns a tuple with the Response field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskMutationRisk) GetResponseOk() (*string, bool) {
	if o == nil || IsNil(o.Response) {
		return nil, false
	}
	return o.Response, true
}

// HasResponse returns a boolean if a field has been set.
func (o *RiskMutationRisk) HasResponse() bool {
	if o != nil && !IsNil(o.Response) {
		return true
	}

	return false
}

// SetResponse gets a reference to the given string and assigns it to the Response field.
func (o *RiskMutationRisk) SetResponse(v string) {
	o.Response = &v
}

// GetScheduleState returns the ScheduleState field value if set, zero value otherwise.
func (o *RiskMutationRisk) GetScheduleState() string {
	if o == nil || IsNil(o.ScheduleState) {
		var ret string
		return ret
	}
	return *o.ScheduleState
}

// GetScheduleStateOk returns a tuple with the ScheduleState field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskMutationRisk) GetScheduleStateOk() (*string, bool) {
	if o == nil || IsNil(o.ScheduleState) {
		return nil, false
	}
	return o.ScheduleState, true
}

// HasScheduleState returns a boolean if a field has been set.
func (o *RiskMutationRisk) HasScheduleState() bool {
	if o != nil && !IsNil(o.ScheduleState) {
		return true
	}

	return false
}

// SetScheduleState gets a reference to the given string and assigns it to the ScheduleState field.
func (o *RiskMutationRisk) SetScheduleState(v string) {
	o.ScheduleState = &v
}

// GetSizeOfLoss returns the SizeOfLoss field value if set, zero value otherwise.
func (o *RiskMutationRisk) GetSizeOfLoss() int64 {
	if o == nil || IsNil(o.SizeOfLoss) {
		var ret int64
		return ret
	}
	return *o.SizeOfLoss
}

// GetSizeOfLossOk returns a tuple with the SizeOfLoss field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskMutationRisk) GetSizeOfLossOk() (*int64, bool) {
	if o == nil || IsNil(o.SizeOfLoss) {
		return nil, false
	}
	return o.SizeOfLoss, true
}

// HasSizeOfLoss returns a boolean if a field has been set.
func (o *RiskMutationRisk) HasSizeOfLoss() bool {
	if o != nil && !IsNil(o.SizeOfLoss) {
		return true
	}

	return false
}

// SetSizeOfLoss gets a reference to the given int64 and assigns it to the SizeOfLoss field.
func (o *RiskMutationRisk) SetSizeOfLoss(v int64) {
	o.SizeOfLoss = &v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *RiskMutationRisk) GetState() string {
	if o == nil || IsNil(o.State) {
		var ret string
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskMutationRisk) GetStateOk() (*string, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *RiskMutationRisk) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given string and assigns it to the State field.
func (o *RiskMutationRisk) SetState(v string) {
	o.State = &v
}

// GetSubmittedBy returns the SubmittedBy field value if set, zero value otherwise.
func (o *RiskMutationRisk) GetSubmittedBy() UserRef {
	if o == nil || IsNil(o.SubmittedBy) {
		var ret UserRef
		return ret
	}
	return *o.SubmittedBy
}

// GetSubmittedByOk returns a tuple with the SubmittedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskMutationRisk) GetSubmittedByOk() (*UserRef, bool) {
	if o == nil || IsNil(o.SubmittedBy) {
		return nil, false
	}
	return o.SubmittedBy, true
}

// HasSubmittedBy returns a boolean if a field has been set.
func (o *RiskMutationRisk) HasSubmittedBy() bool {
	if o != nil && !IsNil(o.SubmittedBy) {
		return true
	}

	return false
}

// SetSubmittedBy gets a reference to the given UserRef and assigns it to the SubmittedBy field.
func (o *RiskMutationRisk) SetSubmittedBy(v UserRef) {
	o.SubmittedBy = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *RiskMutationRisk) GetTags() Collection {
	if o == nil || IsNil(o.Tags) {
		var ret Collection
		return ret
	}
	return *o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskMutationRisk) GetTagsOk() (*Collection, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *RiskMutationRisk) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given Collection and assigns it to the Tags field.
func (o *RiskMutationRisk) SetTags(v Collection) {
	o.Tags = &v
}

// GetWorkItemsAffected returns the WorkItemsAffected field value if set, zero value otherwise.
func (o *RiskMutationRisk) GetWorkItemsAffected() Collection {
	if o == nil || IsNil(o.WorkItemsAffected) {
		var ret Collection
		return ret
	}
	return *o.WorkItemsAffected
}

// GetWorkItemsAffectedOk returns a tuple with the WorkItemsAffected field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskMutationRisk) GetWorkItemsAffectedOk() (*Collection, bool) {
	if o == nil || IsNil(o.WorkItemsAffected) {
		return nil, false
	}
	return o.WorkItemsAffected, true
}

// HasWorkItemsAffected returns a boolean if a field has been set.
func (o *RiskMutationRisk) HasWorkItemsAffected() bool {
	if o != nil && !IsNil(o.WorkItemsAffected) {
		return true
	}

	return false
}

// SetWorkItemsAffected gets a reference to the given Collection and assigns it to the WorkItemsAffected field.
func (o *RiskMutationRisk) SetWorkItemsAffected(v Collection) {
	o.WorkItemsAffected = &v
}

// GetWorkspace returns the Workspace field value if set, zero value otherwise.
func (o *RiskMutationRisk) GetWorkspace() WorkspaceRef {
	if o == nil || IsNil(o.Workspace) {
		var ret WorkspaceRef
		return ret
	}
	return *o.Workspace
}

// GetWorkspaceOk returns a tuple with the Workspace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskMutationRisk) GetWorkspaceOk() (*WorkspaceRef, bool) {
	if o == nil || IsNil(o.Workspace) {
		return nil, false
	}
	return o.Workspace, true
}

// HasWorkspace returns a boolean if a field has been set.
func (o *RiskMutationRisk) HasWorkspace() bool {
	if o != nil && !IsNil(o.Workspace) {
		return true
	}

	return false
}

// SetWorkspace gets a reference to the given WorkspaceRef and assigns it to the Workspace field.
func (o *RiskMutationRisk) SetWorkspace(v WorkspaceRef) {
	o.Workspace = &v
}

// GetCAttentionLevel returns the CAttentionLevel field value if set, zero value otherwise.
func (o *RiskMutationRisk) GetCAttentionLevel() string {
	if o == nil || IsNil(o.CAttentionLevel) {
		var ret string
		return ret
	}
	return *o.CAttentionLevel
}

// GetCAttentionLevelOk returns a tuple with the CAttentionLevel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskMutationRisk) GetCAttentionLevelOk() (*string, bool) {
	if o == nil || IsNil(o.CAttentionLevel) {
		return nil, false
	}
	return o.CAttentionLevel, true
}

// HasCAttentionLevel returns a boolean if a field has been set.
func (o *RiskMutationRisk) HasCAttentionLevel() bool {
	if o != nil && !IsNil(o.CAttentionLevel) {
		return true
	}

	return false
}

// SetCAttentionLevel gets a reference to the given string and assigns it to the CAttentionLevel field.
func (o *RiskMutationRisk) SetCAttentionLevel(v string) {
	o.CAttentionLevel = &v
}

// GetCItemType returns the CItemType field value if set, zero value otherwise.
func (o *RiskMutationRisk) GetCItemType() string {
	if o == nil || IsNil(o.CItemType) {
		var ret string
		return ret
	}
	return *o.CItemType
}

// GetCItemTypeOk returns a tuple with the CItemType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskMutationRisk) GetCItemTypeOk() (*string, bool) {
	if o == nil || IsNil(o.CItemType) {
		return nil, false
	}
	return o.CItemType, true
}

// HasCItemType returns a boolean if a field has been set.
func (o *RiskMutationRisk) HasCItemType() bool {
	if o != nil && !IsNil(o.CItemType) {
		return true
	}

	return false
}

// SetCItemType gets a reference to the given string and assigns it to the CItemType field.
func (o *RiskMutationRisk) SetCItemType(v string) {
	o.CItemType = &v
}

// GetCMIAMI returns the CMIAMI field value if set, zero value otherwise.
func (o *RiskMutationRisk) GetCMIAMI() bool {
	if o == nil || IsNil(o.CMIAMI) {
		var ret bool
		return ret
	}
	return *o.CMIAMI
}

// GetCMIAMIOk returns a tuple with the CMIAMI field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskMutationRisk) GetCMIAMIOk() (*bool, bool) {
	if o == nil || IsNil(o.CMIAMI) {
		return nil, false
	}
	return o.CMIAMI, true
}

// HasCMIAMI returns a boolean if a field has been set.
func (o *RiskMutationRisk) HasCMIAMI() bool {
	if o != nil && !IsNil(o.CMIAMI) {
		return true
	}

	return false
}

// SetCMIAMI gets a reference to the given bool and assigns it to the CMIAMI field.
func (o *RiskMutationRisk) SetCMIAMI(v bool) {
	o.CMIAMI = &v
}

// GetCNextSteps returns the CNextSteps field value if set, zero value otherwise.
func (o *RiskMutationRisk) GetCNextSteps() string {
	if o == nil || IsNil(o.CNextSteps) {
		var ret string
		return ret
	}
	return *o.CNextSteps
}

// GetCNextStepsOk returns a tuple with the CNextSteps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskMutationRisk) GetCNextStepsOk() (*string, bool) {
	if o == nil || IsNil(o.CNextSteps) {
		return nil, false
	}
	return o.CNextSteps, true
}

// HasCNextSteps returns a boolean if a field has been set.
func (o *RiskMutationRisk) HasCNextSteps() bool {
	if o != nil && !IsNil(o.CNextSteps) {
		return true
	}

	return false
}

// SetCNextSteps gets a reference to the given string and assigns it to the CNextSteps field.
func (o *RiskMutationRisk) SetCNextSteps(v string) {
	o.CNextSteps = &v
}

// GetCOwnerNonRallyUser returns the COwnerNonRallyUser field value if set, zero value otherwise.
func (o *RiskMutationRisk) GetCOwnerNonRallyUser() string {
	if o == nil || IsNil(o.COwnerNonRallyUser) {
		var ret string
		return ret
	}
	return *o.COwnerNonRallyUser
}

// GetCOwnerNonRallyUserOk returns a tuple with the COwnerNonRallyUser field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskMutationRisk) GetCOwnerNonRallyUserOk() (*string, bool) {
	if o == nil || IsNil(o.COwnerNonRallyUser) {
		return nil, false
	}
	return o.COwnerNonRallyUser, true
}

// HasCOwnerNonRallyUser returns a boolean if a field has been set.
func (o *RiskMutationRisk) HasCOwnerNonRallyUser() bool {
	if o != nil && !IsNil(o.COwnerNonRallyUser) {
		return true
	}

	return false
}

// SetCOwnerNonRallyUser gets a reference to the given string and assigns it to the COwnerNonRallyUser field.
func (o *RiskMutationRisk) SetCOwnerNonRallyUser(v string) {
	o.COwnerNonRallyUser = &v
}

// GetCTargetDate returns the CTargetDate field value if set, zero value otherwise.
func (o *RiskMutationRisk) GetCTargetDate() string {
	if o == nil || IsNil(o.CTargetDate) {
		var ret string
		return ret
	}
	return *o.CTargetDate
}

// GetCTargetDateOk returns a tuple with the CTargetDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskMutationRisk) GetCTargetDateOk() (*string, bool) {
	if o == nil || IsNil(o.CTargetDate) {
		return nil, false
	}
	return o.CTargetDate, true
}

// HasCTargetDate returns a boolean if a field has been set.
func (o *RiskMutationRisk) HasCTargetDate() bool {
	if o != nil && !IsNil(o.CTargetDate) {
		return true
	}

	return false
}

// SetCTargetDate gets a reference to the given string and assigns it to the CTargetDate field.
func (o *RiskMutationRisk) SetCTargetDate(v string) {
	o.CTargetDate = &v
}

// GetCWorkloadCIID returns the CWorkloadCIID field value if set, zero value otherwise.
func (o *RiskMutationRisk) GetCWorkloadCIID() string {
	if o == nil || IsNil(o.CWorkloadCIID) {
		var ret string
		return ret
	}
	return *o.CWorkloadCIID
}

// GetCWorkloadCIIDOk returns a tuple with the CWorkloadCIID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskMutationRisk) GetCWorkloadCIIDOk() (*string, bool) {
	if o == nil || IsNil(o.CWorkloadCIID) {
		return nil, false
	}
	return o.CWorkloadCIID, true
}

// HasCWorkloadCIID returns a boolean if a field has been set.
func (o *RiskMutationRisk) HasCWorkloadCIID() bool {
	if o != nil && !IsNil(o.CWorkloadCIID) {
		return true
	}

	return false
}

// SetCWorkloadCIID gets a reference to the given string and assigns it to the CWorkloadCIID field.
func (o *RiskMutationRisk) SetCWorkloadCIID(v string) {
	o.CWorkloadCIID = &v
}

// GetWarnings returns the Warnings field value if set, zero value otherwise.
func (o *RiskMutationRisk) GetWarnings() []string {
	if o == nil || IsNil(o.Warnings) {
		var ret []string
		return ret
	}
	return o.Warnings
}

// GetWarningsOk returns a tuple with the Warnings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskMutationRisk) GetWarningsOk() ([]string, bool) {
	if o == nil || IsNil(o.Warnings) {
		return nil, false
	}
	return o.Warnings, true
}

// HasWarnings returns a boolean if a field has been set.
func (o *RiskMutationRisk) HasWarnings() bool {
	if o != nil && !IsNil(o.Warnings) {
		return true
	}

	return false
}

// SetWarnings gets a reference to the given []string and assigns it to the Warnings field.
func (o *RiskMutationRisk) SetWarnings(v []string) {
	o.Warnings = v
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *RiskMutationRisk) GetErrors() []string {
	if o == nil || IsNil(o.Errors) {
		var ret []string
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskMutationRisk) GetErrorsOk() ([]string, bool) {
	if o == nil || IsNil(o.Errors) {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *RiskMutationRisk) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []string and assigns it to the Errors field.
func (o *RiskMutationRisk) SetErrors(v []string) {
	o.Errors = v
}

func (o RiskMutationRisk) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RiskMutationRisk) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Attachments) {
		toSerialize["Attachments"] = o.Attachments
	}
	if !IsNil(o.Changesets) {
		toSerialize["Changesets"] = o.Changesets
	}
	if !IsNil(o.Description) {
		toSerialize["Description"] = o.Description
	}
	if !IsNil(o.DisplayColor) {
		toSerialize["DisplayColor"] = o.DisplayColor
	}
	if !IsNil(o.Expedite) {
		toSerialize["Expedite"] = o.Expedite
	}
	if !IsNil(o.FinancialWorkType) {
		toSerialize["FinancialWorkType"] = o.FinancialWorkType
	}
	if !IsNil(o.FlowState) {
		toSerialize["FlowState"] = o.FlowState
	}
	if !IsNil(o.Impact) {
		toSerialize["Impact"] = o.Impact
	}
	if !IsNil(o.Iteration) {
		toSerialize["Iteration"] = o.Iteration
	}
	if !IsNil(o.IterationValue) {
		toSerialize["IterationValue"] = o.IterationValue
	}
	if !IsNil(o.Milestones) {
		toSerialize["Milestones"] = o.Milestones
	}
	if !IsNil(o.Name) {
		toSerialize["Name"] = o.Name
	}
	if !IsNil(o.Notes) {
		toSerialize["Notes"] = o.Notes
	}
	if !IsNil(o.Owner) {
		toSerialize["Owner"] = o.Owner
	}
	if !IsNil(o.PlanEstimate) {
		toSerialize["PlanEstimate"] = o.PlanEstimate
	}
	if !IsNil(o.Probability) {
		toSerialize["Probability"] = o.Probability
	}
	if !IsNil(o.Project) {
		toSerialize["Project"] = o.Project
	}
	if !IsNil(o.Release) {
		toSerialize["Release"] = o.Release
	}
	if !IsNil(o.ReleaseValue) {
		toSerialize["ReleaseValue"] = o.ReleaseValue
	}
	if !IsNil(o.Resolution) {
		toSerialize["Resolution"] = o.Resolution
	}
	if !IsNil(o.Response) {
		toSerialize["Response"] = o.Response
	}
	if !IsNil(o.ScheduleState) {
		toSerialize["ScheduleState"] = o.ScheduleState
	}
	if !IsNil(o.SizeOfLoss) {
		toSerialize["SizeOfLoss"] = o.SizeOfLoss
	}
	if !IsNil(o.State) {
		toSerialize["State"] = o.State
	}
	if !IsNil(o.SubmittedBy) {
		toSerialize["SubmittedBy"] = o.SubmittedBy
	}
	if !IsNil(o.Tags) {
		toSerialize["Tags"] = o.Tags
	}
	if !IsNil(o.WorkItemsAffected) {
		toSerialize["WorkItemsAffected"] = o.WorkItemsAffected
	}
	if !IsNil(o.Workspace) {
		toSerialize["Workspace"] = o.Workspace
	}
	if !IsNil(o.CAttentionLevel) {
		toSerialize["c_AttentionLevel"] = o.CAttentionLevel
	}
	if !IsNil(o.CItemType) {
		toSerialize["c_ItemType"] = o.CItemType
	}
	if !IsNil(o.CMIAMI) {
		toSerialize["c_MIAMI"] = o.CMIAMI
	}
	if !IsNil(o.CNextSteps) {
		toSerialize["c_NextSteps"] = o.CNextSteps
	}
	if !IsNil(o.COwnerNonRallyUser) {
		toSerialize["c_OwnerNonRallyUser"] = o.COwnerNonRallyUser
	}
	if !IsNil(o.CTargetDate) {
		toSerialize["c_TargetDate"] = o.CTargetDate
	}
	if !IsNil(o.CWorkloadCIID) {
		toSerialize["c_WorkloadCIID"] = o.CWorkloadCIID
	}
	if !IsNil(o.Warnings) {
		toSerialize["Warnings"] = o.Warnings
	}
	if !IsNil(o.Errors) {
		toSerialize["Errors"] = o.Errors
	}
	return toSerialize, nil
}

type NullableRiskMutationRisk struct {
	value *RiskMutationRisk
	isSet bool
}

func (v NullableRiskMutationRisk) Get() *RiskMutationRisk {
	return v.value
}

func (v *NullableRiskMutationRisk) Set(val *RiskMutationRisk) {
	v.value = val
	v.isSet = true
}

func (v NullableRiskMutationRisk) IsSet() bool {
	return v.isSet
}

func (v *NullableRiskMutationRisk) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRiskMutationRisk(val *RiskMutationRisk) *NullableRiskMutationRisk {
	return &NullableRiskMutationRisk{value: val, isSet: true}
}

func (v NullableRiskMutationRisk) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRiskMutationRisk) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
