/*
Rally WebService API

Rally Open API docs

API version: v2.0
Contact: support@rallydev.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ScopedAttributeDefinitionQuery200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ScopedAttributeDefinitionQuery200Response{}

// ScopedAttributeDefinitionQuery200Response struct for ScopedAttributeDefinitionQuery200Response
type ScopedAttributeDefinitionQuery200Response struct {
	QueryResult *ScopedAttributeDefinitionQuery200ResponseQueryResult `json:"QueryResult,omitempty"`
}

// NewScopedAttributeDefinitionQuery200Response instantiates a new ScopedAttributeDefinitionQuery200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewScopedAttributeDefinitionQuery200Response() *ScopedAttributeDefinitionQuery200Response {
	this := ScopedAttributeDefinitionQuery200Response{}
	return &this
}

// NewScopedAttributeDefinitionQuery200ResponseWithDefaults instantiates a new ScopedAttributeDefinitionQuery200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewScopedAttributeDefinitionQuery200ResponseWithDefaults() *ScopedAttributeDefinitionQuery200Response {
	this := ScopedAttributeDefinitionQuery200Response{}
	return &this
}

// GetQueryResult returns the QueryResult field value if set, zero value otherwise.
func (o *ScopedAttributeDefinitionQuery200Response) GetQueryResult() ScopedAttributeDefinitionQuery200ResponseQueryResult {
	if o == nil || IsNil(o.QueryResult) {
		var ret ScopedAttributeDefinitionQuery200ResponseQueryResult
		return ret
	}
	return *o.QueryResult
}

// GetQueryResultOk returns a tuple with the QueryResult field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScopedAttributeDefinitionQuery200Response) GetQueryResultOk() (*ScopedAttributeDefinitionQuery200ResponseQueryResult, bool) {
	if o == nil || IsNil(o.QueryResult) {
		return nil, false
	}
	return o.QueryResult, true
}

// HasQueryResult returns a boolean if a field has been set.
func (o *ScopedAttributeDefinitionQuery200Response) HasQueryResult() bool {
	if o != nil && !IsNil(o.QueryResult) {
		return true
	}

	return false
}

// SetQueryResult gets a reference to the given ScopedAttributeDefinitionQuery200ResponseQueryResult and assigns it to the QueryResult field.
func (o *ScopedAttributeDefinitionQuery200Response) SetQueryResult(v ScopedAttributeDefinitionQuery200ResponseQueryResult) {
	o.QueryResult = &v
}

func (o ScopedAttributeDefinitionQuery200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ScopedAttributeDefinitionQuery200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.QueryResult) {
		toSerialize["QueryResult"] = o.QueryResult
	}
	return toSerialize, nil
}

type NullableScopedAttributeDefinitionQuery200Response struct {
	value *ScopedAttributeDefinitionQuery200Response
	isSet bool
}

func (v NullableScopedAttributeDefinitionQuery200Response) Get() *ScopedAttributeDefinitionQuery200Response {
	return v.value
}

func (v *NullableScopedAttributeDefinitionQuery200Response) Set(val *ScopedAttributeDefinitionQuery200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableScopedAttributeDefinitionQuery200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableScopedAttributeDefinitionQuery200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableScopedAttributeDefinitionQuery200Response(val *ScopedAttributeDefinitionQuery200Response) *NullableScopedAttributeDefinitionQuery200Response {
	return &NullableScopedAttributeDefinitionQuery200Response{value: val, isSet: true}
}

func (v NullableScopedAttributeDefinitionQuery200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableScopedAttributeDefinitionQuery200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


