/*
Rally WebService API

Rally Open API docs

API version: v2.0
Contact: support@rallydev.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the WorkspaceQuery200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WorkspaceQuery200Response{}

// WorkspaceQuery200Response struct for WorkspaceQuery200Response
type WorkspaceQuery200Response struct {
	QueryResult *WorkspaceQuery200ResponseQueryResult `json:"QueryResult,omitempty"`
}

// NewWorkspaceQuery200Response instantiates a new WorkspaceQuery200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkspaceQuery200Response() *WorkspaceQuery200Response {
	this := WorkspaceQuery200Response{}
	return &this
}

// NewWorkspaceQuery200ResponseWithDefaults instantiates a new WorkspaceQuery200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkspaceQuery200ResponseWithDefaults() *WorkspaceQuery200Response {
	this := WorkspaceQuery200Response{}
	return &this
}

// GetQueryResult returns the QueryResult field value if set, zero value otherwise.
func (o *WorkspaceQuery200Response) GetQueryResult() WorkspaceQuery200ResponseQueryResult {
	if o == nil || IsNil(o.QueryResult) {
		var ret WorkspaceQuery200ResponseQueryResult
		return ret
	}
	return *o.QueryResult
}

// GetQueryResultOk returns a tuple with the QueryResult field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkspaceQuery200Response) GetQueryResultOk() (*WorkspaceQuery200ResponseQueryResult, bool) {
	if o == nil || IsNil(o.QueryResult) {
		return nil, false
	}
	return o.QueryResult, true
}

// HasQueryResult returns a boolean if a field has been set.
func (o *WorkspaceQuery200Response) HasQueryResult() bool {
	if o != nil && !IsNil(o.QueryResult) {
		return true
	}

	return false
}

// SetQueryResult gets a reference to the given WorkspaceQuery200ResponseQueryResult and assigns it to the QueryResult field.
func (o *WorkspaceQuery200Response) SetQueryResult(v WorkspaceQuery200ResponseQueryResult) {
	o.QueryResult = &v
}

func (o WorkspaceQuery200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WorkspaceQuery200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.QueryResult) {
		toSerialize["QueryResult"] = o.QueryResult
	}
	return toSerialize, nil
}

type NullableWorkspaceQuery200Response struct {
	value *WorkspaceQuery200Response
	isSet bool
}

func (v NullableWorkspaceQuery200Response) Get() *WorkspaceQuery200Response {
	return v.value
}

func (v *NullableWorkspaceQuery200Response) Set(val *WorkspaceQuery200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkspaceQuery200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkspaceQuery200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkspaceQuery200Response(val *WorkspaceQuery200Response) *NullableWorkspaceQuery200Response {
	return &NullableWorkspaceQuery200Response{value: val, isSet: true}
}

func (v NullableWorkspaceQuery200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkspaceQuery200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


