/*
Rally WebService API

Rally Open API docs

API version: v2.0
Contact: support@rallydev.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the TestFolderStatus type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TestFolderStatus{}

// TestFolderStatus TestFolderStatus
type TestFolderStatus struct {
	// Creation Date
	CreationDate *string `json:"CreationDate,omitempty"`
	// Failed Count
	FailedCount *int64 `json:"FailedCount,omitempty"`
	// No Result Count
	NoResultCount *int64 `json:"NoResultCount,omitempty"`
	// Object ID
	ObjectID *int64 `json:"ObjectID,omitempty"`
	// ObjectUUID
	ObjectUUID *string `json:"ObjectUUID,omitempty"`
	// Others Count
	OthersCount *int64 `json:"OthersCount,omitempty"`
	// Passing Count
	PassingCount *int64           `json:"PassingCount,omitempty"`
	Subscription *SubscriptionRef `json:"Subscription,omitempty"`
	// VersionId
	VersionId *string       `json:"VersionId,omitempty"`
	Workspace *WorkspaceRef `json:"Workspace,omitempty"`
	Warnings  []string      `json:"Warnings,omitempty"`
	Errors    []string      `json:"Errors,omitempty"`
}

// NewTestFolderStatus instantiates a new TestFolderStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTestFolderStatus() *TestFolderStatus {
	this := TestFolderStatus{}
	return &this
}

// NewTestFolderStatusWithDefaults instantiates a new TestFolderStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTestFolderStatusWithDefaults() *TestFolderStatus {
	this := TestFolderStatus{}
	return &this
}

// GetCreationDate returns the CreationDate field value if set, zero value otherwise.
func (o *TestFolderStatus) GetCreationDate() string {
	if o == nil || IsNil(o.CreationDate) {
		var ret string
		return ret
	}
	return *o.CreationDate
}

// GetCreationDateOk returns a tuple with the CreationDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TestFolderStatus) GetCreationDateOk() (*string, bool) {
	if o == nil || IsNil(o.CreationDate) {
		return nil, false
	}
	return o.CreationDate, true
}

// HasCreationDate returns a boolean if a field has been set.
func (o *TestFolderStatus) HasCreationDate() bool {
	if o != nil && !IsNil(o.CreationDate) {
		return true
	}

	return false
}

// SetCreationDate gets a reference to the given string and assigns it to the CreationDate field.
func (o *TestFolderStatus) SetCreationDate(v string) {
	o.CreationDate = &v
}

// GetFailedCount returns the FailedCount field value if set, zero value otherwise.
func (o *TestFolderStatus) GetFailedCount() int64 {
	if o == nil || IsNil(o.FailedCount) {
		var ret int64
		return ret
	}
	return *o.FailedCount
}

// GetFailedCountOk returns a tuple with the FailedCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TestFolderStatus) GetFailedCountOk() (*int64, bool) {
	if o == nil || IsNil(o.FailedCount) {
		return nil, false
	}
	return o.FailedCount, true
}

// HasFailedCount returns a boolean if a field has been set.
func (o *TestFolderStatus) HasFailedCount() bool {
	if o != nil && !IsNil(o.FailedCount) {
		return true
	}

	return false
}

// SetFailedCount gets a reference to the given int64 and assigns it to the FailedCount field.
func (o *TestFolderStatus) SetFailedCount(v int64) {
	o.FailedCount = &v
}

// GetNoResultCount returns the NoResultCount field value if set, zero value otherwise.
func (o *TestFolderStatus) GetNoResultCount() int64 {
	if o == nil || IsNil(o.NoResultCount) {
		var ret int64
		return ret
	}
	return *o.NoResultCount
}

// GetNoResultCountOk returns a tuple with the NoResultCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TestFolderStatus) GetNoResultCountOk() (*int64, bool) {
	if o == nil || IsNil(o.NoResultCount) {
		return nil, false
	}
	return o.NoResultCount, true
}

// HasNoResultCount returns a boolean if a field has been set.
func (o *TestFolderStatus) HasNoResultCount() bool {
	if o != nil && !IsNil(o.NoResultCount) {
		return true
	}

	return false
}

// SetNoResultCount gets a reference to the given int64 and assigns it to the NoResultCount field.
func (o *TestFolderStatus) SetNoResultCount(v int64) {
	o.NoResultCount = &v
}

// GetObjectID returns the ObjectID field value if set, zero value otherwise.
func (o *TestFolderStatus) GetObjectID() int64 {
	if o == nil || IsNil(o.ObjectID) {
		var ret int64
		return ret
	}
	return *o.ObjectID
}

// GetObjectIDOk returns a tuple with the ObjectID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TestFolderStatus) GetObjectIDOk() (*int64, bool) {
	if o == nil || IsNil(o.ObjectID) {
		return nil, false
	}
	return o.ObjectID, true
}

// HasObjectID returns a boolean if a field has been set.
func (o *TestFolderStatus) HasObjectID() bool {
	if o != nil && !IsNil(o.ObjectID) {
		return true
	}

	return false
}

// SetObjectID gets a reference to the given int64 and assigns it to the ObjectID field.
func (o *TestFolderStatus) SetObjectID(v int64) {
	o.ObjectID = &v
}

// GetObjectUUID returns the ObjectUUID field value if set, zero value otherwise.
func (o *TestFolderStatus) GetObjectUUID() string {
	if o == nil || IsNil(o.ObjectUUID) {
		var ret string
		return ret
	}
	return *o.ObjectUUID
}

// GetObjectUUIDOk returns a tuple with the ObjectUUID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TestFolderStatus) GetObjectUUIDOk() (*string, bool) {
	if o == nil || IsNil(o.ObjectUUID) {
		return nil, false
	}
	return o.ObjectUUID, true
}

// HasObjectUUID returns a boolean if a field has been set.
func (o *TestFolderStatus) HasObjectUUID() bool {
	if o != nil && !IsNil(o.ObjectUUID) {
		return true
	}

	return false
}

// SetObjectUUID gets a reference to the given string and assigns it to the ObjectUUID field.
func (o *TestFolderStatus) SetObjectUUID(v string) {
	o.ObjectUUID = &v
}

// GetOthersCount returns the OthersCount field value if set, zero value otherwise.
func (o *TestFolderStatus) GetOthersCount() int64 {
	if o == nil || IsNil(o.OthersCount) {
		var ret int64
		return ret
	}
	return *o.OthersCount
}

// GetOthersCountOk returns a tuple with the OthersCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TestFolderStatus) GetOthersCountOk() (*int64, bool) {
	if o == nil || IsNil(o.OthersCount) {
		return nil, false
	}
	return o.OthersCount, true
}

// HasOthersCount returns a boolean if a field has been set.
func (o *TestFolderStatus) HasOthersCount() bool {
	if o != nil && !IsNil(o.OthersCount) {
		return true
	}

	return false
}

// SetOthersCount gets a reference to the given int64 and assigns it to the OthersCount field.
func (o *TestFolderStatus) SetOthersCount(v int64) {
	o.OthersCount = &v
}

// GetPassingCount returns the PassingCount field value if set, zero value otherwise.
func (o *TestFolderStatus) GetPassingCount() int64 {
	if o == nil || IsNil(o.PassingCount) {
		var ret int64
		return ret
	}
	return *o.PassingCount
}

// GetPassingCountOk returns a tuple with the PassingCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TestFolderStatus) GetPassingCountOk() (*int64, bool) {
	if o == nil || IsNil(o.PassingCount) {
		return nil, false
	}
	return o.PassingCount, true
}

// HasPassingCount returns a boolean if a field has been set.
func (o *TestFolderStatus) HasPassingCount() bool {
	if o != nil && !IsNil(o.PassingCount) {
		return true
	}

	return false
}

// SetPassingCount gets a reference to the given int64 and assigns it to the PassingCount field.
func (o *TestFolderStatus) SetPassingCount(v int64) {
	o.PassingCount = &v
}

// GetSubscription returns the Subscription field value if set, zero value otherwise.
func (o *TestFolderStatus) GetSubscription() SubscriptionRef {
	if o == nil || IsNil(o.Subscription) {
		var ret SubscriptionRef
		return ret
	}
	return *o.Subscription
}

// GetSubscriptionOk returns a tuple with the Subscription field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TestFolderStatus) GetSubscriptionOk() (*SubscriptionRef, bool) {
	if o == nil || IsNil(o.Subscription) {
		return nil, false
	}
	return o.Subscription, true
}

// HasSubscription returns a boolean if a field has been set.
func (o *TestFolderStatus) HasSubscription() bool {
	if o != nil && !IsNil(o.Subscription) {
		return true
	}

	return false
}

// SetSubscription gets a reference to the given SubscriptionRef and assigns it to the Subscription field.
func (o *TestFolderStatus) SetSubscription(v SubscriptionRef) {
	o.Subscription = &v
}

// GetVersionId returns the VersionId field value if set, zero value otherwise.
func (o *TestFolderStatus) GetVersionId() string {
	if o == nil || IsNil(o.VersionId) {
		var ret string
		return ret
	}
	return *o.VersionId
}

// GetVersionIdOk returns a tuple with the VersionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TestFolderStatus) GetVersionIdOk() (*string, bool) {
	if o == nil || IsNil(o.VersionId) {
		return nil, false
	}
	return o.VersionId, true
}

// HasVersionId returns a boolean if a field has been set.
func (o *TestFolderStatus) HasVersionId() bool {
	if o != nil && !IsNil(o.VersionId) {
		return true
	}

	return false
}

// SetVersionId gets a reference to the given string and assigns it to the VersionId field.
func (o *TestFolderStatus) SetVersionId(v string) {
	o.VersionId = &v
}

// GetWorkspace returns the Workspace field value if set, zero value otherwise.
func (o *TestFolderStatus) GetWorkspace() WorkspaceRef {
	if o == nil || IsNil(o.Workspace) {
		var ret WorkspaceRef
		return ret
	}
	return *o.Workspace
}

// GetWorkspaceOk returns a tuple with the Workspace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TestFolderStatus) GetWorkspaceOk() (*WorkspaceRef, bool) {
	if o == nil || IsNil(o.Workspace) {
		return nil, false
	}
	return o.Workspace, true
}

// HasWorkspace returns a boolean if a field has been set.
func (o *TestFolderStatus) HasWorkspace() bool {
	if o != nil && !IsNil(o.Workspace) {
		return true
	}

	return false
}

// SetWorkspace gets a reference to the given WorkspaceRef and assigns it to the Workspace field.
func (o *TestFolderStatus) SetWorkspace(v WorkspaceRef) {
	o.Workspace = &v
}

// GetWarnings returns the Warnings field value if set, zero value otherwise.
func (o *TestFolderStatus) GetWarnings() []string {
	if o == nil || IsNil(o.Warnings) {
		var ret []string
		return ret
	}
	return o.Warnings
}

// GetWarningsOk returns a tuple with the Warnings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TestFolderStatus) GetWarningsOk() ([]string, bool) {
	if o == nil || IsNil(o.Warnings) {
		return nil, false
	}
	return o.Warnings, true
}

// HasWarnings returns a boolean if a field has been set.
func (o *TestFolderStatus) HasWarnings() bool {
	if o != nil && !IsNil(o.Warnings) {
		return true
	}

	return false
}

// SetWarnings gets a reference to the given []string and assigns it to the Warnings field.
func (o *TestFolderStatus) SetWarnings(v []string) {
	o.Warnings = v
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *TestFolderStatus) GetErrors() []string {
	if o == nil || IsNil(o.Errors) {
		var ret []string
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TestFolderStatus) GetErrorsOk() ([]string, bool) {
	if o == nil || IsNil(o.Errors) {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *TestFolderStatus) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []string and assigns it to the Errors field.
func (o *TestFolderStatus) SetErrors(v []string) {
	o.Errors = v
}

func (o TestFolderStatus) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TestFolderStatus) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CreationDate) {
		toSerialize["CreationDate"] = o.CreationDate
	}
	if !IsNil(o.FailedCount) {
		toSerialize["FailedCount"] = o.FailedCount
	}
	if !IsNil(o.NoResultCount) {
		toSerialize["NoResultCount"] = o.NoResultCount
	}
	if !IsNil(o.ObjectID) {
		toSerialize["ObjectID"] = o.ObjectID
	}
	if !IsNil(o.ObjectUUID) {
		toSerialize["ObjectUUID"] = o.ObjectUUID
	}
	if !IsNil(o.OthersCount) {
		toSerialize["OthersCount"] = o.OthersCount
	}
	if !IsNil(o.PassingCount) {
		toSerialize["PassingCount"] = o.PassingCount
	}
	if !IsNil(o.Subscription) {
		toSerialize["Subscription"] = o.Subscription
	}
	if !IsNil(o.VersionId) {
		toSerialize["VersionId"] = o.VersionId
	}
	if !IsNil(o.Workspace) {
		toSerialize["Workspace"] = o.Workspace
	}
	if !IsNil(o.Warnings) {
		toSerialize["Warnings"] = o.Warnings
	}
	if !IsNil(o.Errors) {
		toSerialize["Errors"] = o.Errors
	}
	return toSerialize, nil
}

type NullableTestFolderStatus struct {
	value *TestFolderStatus
	isSet bool
}

func (v NullableTestFolderStatus) Get() *TestFolderStatus {
	return v.value
}

func (v *NullableTestFolderStatus) Set(val *TestFolderStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableTestFolderStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableTestFolderStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTestFolderStatus(val *TestFolderStatus) *NullableTestFolderStatus {
	return &NullableTestFolderStatus{value: val, isSet: true}
}

func (v NullableTestFolderStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTestFolderStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
