/*
Rally WebService API

Rally Open API docs

API version: v2.0
Contact: support@rallydev.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the LDAPConfiguration type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LDAPConfiguration{}

// LDAPConfiguration LDAPConfiguration
type LDAPConfiguration struct {
	// Admin DN
	AdminDN *string `json:"AdminDN,omitempty"`
	// Admin Password
	AdminPassword *string `json:"AdminPassword,omitempty"`
	// Base DN
	BaseDN *string `json:"BaseDN,omitempty"`
	// Creation Date
	CreationDate *string `json:"CreationDate,omitempty"`
	// Display Name Attribute
	DisplayNameAttribute *string `json:"DisplayNameAttribute,omitempty"`
	// Email Attribute
	EmailAttribute *string `json:"EmailAttribute,omitempty"`
	// Enable User Sync
	EnableUserSync *bool `json:"EnableUserSync,omitempty"`
	// First Name Attribute
	FirstNameAttribute *string `json:"FirstNameAttribute,omitempty"`
	// Host
	Host *string `json:"Host,omitempty"`
	// Inactive Attribute
	InactiveAttribute *string `json:"InactiveAttribute,omitempty"`
	// Inactive Value
	InactiveValue *string `json:"InactiveValue,omitempty"`
	// LDAP Username Attribute
	LDAPUsernameAttribute *string `json:"LDAPUsernameAttribute,omitempty"`
	// Last Name Attribute
	LastNameAttribute *string `json:"LastNameAttribute,omitempty"`
	// Object ID
	ObjectID *int64 `json:"ObjectID,omitempty"`
	// ObjectUUID
	ObjectUUID *string `json:"ObjectUUID,omitempty"`
	// Port
	Port *int64 `json:"Port,omitempty"`
	// Rally Username Attribute
	RallyUsernameAttribute *string `json:"RallyUsernameAttribute,omitempty"`
	// SSL Cert
	SSLCert *string `json:"SSLCert,omitempty"`
	// Subscription ID
	SubscriptionID *int64 `json:"SubscriptionID,omitempty"`
	// Use SSL
	UseSSL *bool `json:"UseSSL,omitempty"`
	// User Filter Query
	UserFilterQuery *string `json:"UserFilterQuery,omitempty"`
	// VersionId
	VersionId *string `json:"VersionId,omitempty"`
	Warnings []string `json:"Warnings,omitempty"`
	Errors []string `json:"Errors,omitempty"`
}

// NewLDAPConfiguration instantiates a new LDAPConfiguration object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLDAPConfiguration() *LDAPConfiguration {
	this := LDAPConfiguration{}
	return &this
}

// NewLDAPConfigurationWithDefaults instantiates a new LDAPConfiguration object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLDAPConfigurationWithDefaults() *LDAPConfiguration {
	this := LDAPConfiguration{}
	return &this
}

// GetAdminDN returns the AdminDN field value if set, zero value otherwise.
func (o *LDAPConfiguration) GetAdminDN() string {
	if o == nil || IsNil(o.AdminDN) {
		var ret string
		return ret
	}
	return *o.AdminDN
}

// GetAdminDNOk returns a tuple with the AdminDN field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LDAPConfiguration) GetAdminDNOk() (*string, bool) {
	if o == nil || IsNil(o.AdminDN) {
		return nil, false
	}
	return o.AdminDN, true
}

// HasAdminDN returns a boolean if a field has been set.
func (o *LDAPConfiguration) HasAdminDN() bool {
	if o != nil && !IsNil(o.AdminDN) {
		return true
	}

	return false
}

// SetAdminDN gets a reference to the given string and assigns it to the AdminDN field.
func (o *LDAPConfiguration) SetAdminDN(v string) {
	o.AdminDN = &v
}

// GetAdminPassword returns the AdminPassword field value if set, zero value otherwise.
func (o *LDAPConfiguration) GetAdminPassword() string {
	if o == nil || IsNil(o.AdminPassword) {
		var ret string
		return ret
	}
	return *o.AdminPassword
}

// GetAdminPasswordOk returns a tuple with the AdminPassword field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LDAPConfiguration) GetAdminPasswordOk() (*string, bool) {
	if o == nil || IsNil(o.AdminPassword) {
		return nil, false
	}
	return o.AdminPassword, true
}

// HasAdminPassword returns a boolean if a field has been set.
func (o *LDAPConfiguration) HasAdminPassword() bool {
	if o != nil && !IsNil(o.AdminPassword) {
		return true
	}

	return false
}

// SetAdminPassword gets a reference to the given string and assigns it to the AdminPassword field.
func (o *LDAPConfiguration) SetAdminPassword(v string) {
	o.AdminPassword = &v
}

// GetBaseDN returns the BaseDN field value if set, zero value otherwise.
func (o *LDAPConfiguration) GetBaseDN() string {
	if o == nil || IsNil(o.BaseDN) {
		var ret string
		return ret
	}
	return *o.BaseDN
}

// GetBaseDNOk returns a tuple with the BaseDN field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LDAPConfiguration) GetBaseDNOk() (*string, bool) {
	if o == nil || IsNil(o.BaseDN) {
		return nil, false
	}
	return o.BaseDN, true
}

// HasBaseDN returns a boolean if a field has been set.
func (o *LDAPConfiguration) HasBaseDN() bool {
	if o != nil && !IsNil(o.BaseDN) {
		return true
	}

	return false
}

// SetBaseDN gets a reference to the given string and assigns it to the BaseDN field.
func (o *LDAPConfiguration) SetBaseDN(v string) {
	o.BaseDN = &v
}

// GetCreationDate returns the CreationDate field value if set, zero value otherwise.
func (o *LDAPConfiguration) GetCreationDate() string {
	if o == nil || IsNil(o.CreationDate) {
		var ret string
		return ret
	}
	return *o.CreationDate
}

// GetCreationDateOk returns a tuple with the CreationDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LDAPConfiguration) GetCreationDateOk() (*string, bool) {
	if o == nil || IsNil(o.CreationDate) {
		return nil, false
	}
	return o.CreationDate, true
}

// HasCreationDate returns a boolean if a field has been set.
func (o *LDAPConfiguration) HasCreationDate() bool {
	if o != nil && !IsNil(o.CreationDate) {
		return true
	}

	return false
}

// SetCreationDate gets a reference to the given string and assigns it to the CreationDate field.
func (o *LDAPConfiguration) SetCreationDate(v string) {
	o.CreationDate = &v
}

// GetDisplayNameAttribute returns the DisplayNameAttribute field value if set, zero value otherwise.
func (o *LDAPConfiguration) GetDisplayNameAttribute() string {
	if o == nil || IsNil(o.DisplayNameAttribute) {
		var ret string
		return ret
	}
	return *o.DisplayNameAttribute
}

// GetDisplayNameAttributeOk returns a tuple with the DisplayNameAttribute field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LDAPConfiguration) GetDisplayNameAttributeOk() (*string, bool) {
	if o == nil || IsNil(o.DisplayNameAttribute) {
		return nil, false
	}
	return o.DisplayNameAttribute, true
}

// HasDisplayNameAttribute returns a boolean if a field has been set.
func (o *LDAPConfiguration) HasDisplayNameAttribute() bool {
	if o != nil && !IsNil(o.DisplayNameAttribute) {
		return true
	}

	return false
}

// SetDisplayNameAttribute gets a reference to the given string and assigns it to the DisplayNameAttribute field.
func (o *LDAPConfiguration) SetDisplayNameAttribute(v string) {
	o.DisplayNameAttribute = &v
}

// GetEmailAttribute returns the EmailAttribute field value if set, zero value otherwise.
func (o *LDAPConfiguration) GetEmailAttribute() string {
	if o == nil || IsNil(o.EmailAttribute) {
		var ret string
		return ret
	}
	return *o.EmailAttribute
}

// GetEmailAttributeOk returns a tuple with the EmailAttribute field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LDAPConfiguration) GetEmailAttributeOk() (*string, bool) {
	if o == nil || IsNil(o.EmailAttribute) {
		return nil, false
	}
	return o.EmailAttribute, true
}

// HasEmailAttribute returns a boolean if a field has been set.
func (o *LDAPConfiguration) HasEmailAttribute() bool {
	if o != nil && !IsNil(o.EmailAttribute) {
		return true
	}

	return false
}

// SetEmailAttribute gets a reference to the given string and assigns it to the EmailAttribute field.
func (o *LDAPConfiguration) SetEmailAttribute(v string) {
	o.EmailAttribute = &v
}

// GetEnableUserSync returns the EnableUserSync field value if set, zero value otherwise.
func (o *LDAPConfiguration) GetEnableUserSync() bool {
	if o == nil || IsNil(o.EnableUserSync) {
		var ret bool
		return ret
	}
	return *o.EnableUserSync
}

// GetEnableUserSyncOk returns a tuple with the EnableUserSync field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LDAPConfiguration) GetEnableUserSyncOk() (*bool, bool) {
	if o == nil || IsNil(o.EnableUserSync) {
		return nil, false
	}
	return o.EnableUserSync, true
}

// HasEnableUserSync returns a boolean if a field has been set.
func (o *LDAPConfiguration) HasEnableUserSync() bool {
	if o != nil && !IsNil(o.EnableUserSync) {
		return true
	}

	return false
}

// SetEnableUserSync gets a reference to the given bool and assigns it to the EnableUserSync field.
func (o *LDAPConfiguration) SetEnableUserSync(v bool) {
	o.EnableUserSync = &v
}

// GetFirstNameAttribute returns the FirstNameAttribute field value if set, zero value otherwise.
func (o *LDAPConfiguration) GetFirstNameAttribute() string {
	if o == nil || IsNil(o.FirstNameAttribute) {
		var ret string
		return ret
	}
	return *o.FirstNameAttribute
}

// GetFirstNameAttributeOk returns a tuple with the FirstNameAttribute field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LDAPConfiguration) GetFirstNameAttributeOk() (*string, bool) {
	if o == nil || IsNil(o.FirstNameAttribute) {
		return nil, false
	}
	return o.FirstNameAttribute, true
}

// HasFirstNameAttribute returns a boolean if a field has been set.
func (o *LDAPConfiguration) HasFirstNameAttribute() bool {
	if o != nil && !IsNil(o.FirstNameAttribute) {
		return true
	}

	return false
}

// SetFirstNameAttribute gets a reference to the given string and assigns it to the FirstNameAttribute field.
func (o *LDAPConfiguration) SetFirstNameAttribute(v string) {
	o.FirstNameAttribute = &v
}

// GetHost returns the Host field value if set, zero value otherwise.
func (o *LDAPConfiguration) GetHost() string {
	if o == nil || IsNil(o.Host) {
		var ret string
		return ret
	}
	return *o.Host
}

// GetHostOk returns a tuple with the Host field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LDAPConfiguration) GetHostOk() (*string, bool) {
	if o == nil || IsNil(o.Host) {
		return nil, false
	}
	return o.Host, true
}

// HasHost returns a boolean if a field has been set.
func (o *LDAPConfiguration) HasHost() bool {
	if o != nil && !IsNil(o.Host) {
		return true
	}

	return false
}

// SetHost gets a reference to the given string and assigns it to the Host field.
func (o *LDAPConfiguration) SetHost(v string) {
	o.Host = &v
}

// GetInactiveAttribute returns the InactiveAttribute field value if set, zero value otherwise.
func (o *LDAPConfiguration) GetInactiveAttribute() string {
	if o == nil || IsNil(o.InactiveAttribute) {
		var ret string
		return ret
	}
	return *o.InactiveAttribute
}

// GetInactiveAttributeOk returns a tuple with the InactiveAttribute field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LDAPConfiguration) GetInactiveAttributeOk() (*string, bool) {
	if o == nil || IsNil(o.InactiveAttribute) {
		return nil, false
	}
	return o.InactiveAttribute, true
}

// HasInactiveAttribute returns a boolean if a field has been set.
func (o *LDAPConfiguration) HasInactiveAttribute() bool {
	if o != nil && !IsNil(o.InactiveAttribute) {
		return true
	}

	return false
}

// SetInactiveAttribute gets a reference to the given string and assigns it to the InactiveAttribute field.
func (o *LDAPConfiguration) SetInactiveAttribute(v string) {
	o.InactiveAttribute = &v
}

// GetInactiveValue returns the InactiveValue field value if set, zero value otherwise.
func (o *LDAPConfiguration) GetInactiveValue() string {
	if o == nil || IsNil(o.InactiveValue) {
		var ret string
		return ret
	}
	return *o.InactiveValue
}

// GetInactiveValueOk returns a tuple with the InactiveValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LDAPConfiguration) GetInactiveValueOk() (*string, bool) {
	if o == nil || IsNil(o.InactiveValue) {
		return nil, false
	}
	return o.InactiveValue, true
}

// HasInactiveValue returns a boolean if a field has been set.
func (o *LDAPConfiguration) HasInactiveValue() bool {
	if o != nil && !IsNil(o.InactiveValue) {
		return true
	}

	return false
}

// SetInactiveValue gets a reference to the given string and assigns it to the InactiveValue field.
func (o *LDAPConfiguration) SetInactiveValue(v string) {
	o.InactiveValue = &v
}

// GetLDAPUsernameAttribute returns the LDAPUsernameAttribute field value if set, zero value otherwise.
func (o *LDAPConfiguration) GetLDAPUsernameAttribute() string {
	if o == nil || IsNil(o.LDAPUsernameAttribute) {
		var ret string
		return ret
	}
	return *o.LDAPUsernameAttribute
}

// GetLDAPUsernameAttributeOk returns a tuple with the LDAPUsernameAttribute field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LDAPConfiguration) GetLDAPUsernameAttributeOk() (*string, bool) {
	if o == nil || IsNil(o.LDAPUsernameAttribute) {
		return nil, false
	}
	return o.LDAPUsernameAttribute, true
}

// HasLDAPUsernameAttribute returns a boolean if a field has been set.
func (o *LDAPConfiguration) HasLDAPUsernameAttribute() bool {
	if o != nil && !IsNil(o.LDAPUsernameAttribute) {
		return true
	}

	return false
}

// SetLDAPUsernameAttribute gets a reference to the given string and assigns it to the LDAPUsernameAttribute field.
func (o *LDAPConfiguration) SetLDAPUsernameAttribute(v string) {
	o.LDAPUsernameAttribute = &v
}

// GetLastNameAttribute returns the LastNameAttribute field value if set, zero value otherwise.
func (o *LDAPConfiguration) GetLastNameAttribute() string {
	if o == nil || IsNil(o.LastNameAttribute) {
		var ret string
		return ret
	}
	return *o.LastNameAttribute
}

// GetLastNameAttributeOk returns a tuple with the LastNameAttribute field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LDAPConfiguration) GetLastNameAttributeOk() (*string, bool) {
	if o == nil || IsNil(o.LastNameAttribute) {
		return nil, false
	}
	return o.LastNameAttribute, true
}

// HasLastNameAttribute returns a boolean if a field has been set.
func (o *LDAPConfiguration) HasLastNameAttribute() bool {
	if o != nil && !IsNil(o.LastNameAttribute) {
		return true
	}

	return false
}

// SetLastNameAttribute gets a reference to the given string and assigns it to the LastNameAttribute field.
func (o *LDAPConfiguration) SetLastNameAttribute(v string) {
	o.LastNameAttribute = &v
}

// GetObjectID returns the ObjectID field value if set, zero value otherwise.
func (o *LDAPConfiguration) GetObjectID() int64 {
	if o == nil || IsNil(o.ObjectID) {
		var ret int64
		return ret
	}
	return *o.ObjectID
}

// GetObjectIDOk returns a tuple with the ObjectID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LDAPConfiguration) GetObjectIDOk() (*int64, bool) {
	if o == nil || IsNil(o.ObjectID) {
		return nil, false
	}
	return o.ObjectID, true
}

// HasObjectID returns a boolean if a field has been set.
func (o *LDAPConfiguration) HasObjectID() bool {
	if o != nil && !IsNil(o.ObjectID) {
		return true
	}

	return false
}

// SetObjectID gets a reference to the given int64 and assigns it to the ObjectID field.
func (o *LDAPConfiguration) SetObjectID(v int64) {
	o.ObjectID = &v
}

// GetObjectUUID returns the ObjectUUID field value if set, zero value otherwise.
func (o *LDAPConfiguration) GetObjectUUID() string {
	if o == nil || IsNil(o.ObjectUUID) {
		var ret string
		return ret
	}
	return *o.ObjectUUID
}

// GetObjectUUIDOk returns a tuple with the ObjectUUID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LDAPConfiguration) GetObjectUUIDOk() (*string, bool) {
	if o == nil || IsNil(o.ObjectUUID) {
		return nil, false
	}
	return o.ObjectUUID, true
}

// HasObjectUUID returns a boolean if a field has been set.
func (o *LDAPConfiguration) HasObjectUUID() bool {
	if o != nil && !IsNil(o.ObjectUUID) {
		return true
	}

	return false
}

// SetObjectUUID gets a reference to the given string and assigns it to the ObjectUUID field.
func (o *LDAPConfiguration) SetObjectUUID(v string) {
	o.ObjectUUID = &v
}

// GetPort returns the Port field value if set, zero value otherwise.
func (o *LDAPConfiguration) GetPort() int64 {
	if o == nil || IsNil(o.Port) {
		var ret int64
		return ret
	}
	return *o.Port
}

// GetPortOk returns a tuple with the Port field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LDAPConfiguration) GetPortOk() (*int64, bool) {
	if o == nil || IsNil(o.Port) {
		return nil, false
	}
	return o.Port, true
}

// HasPort returns a boolean if a field has been set.
func (o *LDAPConfiguration) HasPort() bool {
	if o != nil && !IsNil(o.Port) {
		return true
	}

	return false
}

// SetPort gets a reference to the given int64 and assigns it to the Port field.
func (o *LDAPConfiguration) SetPort(v int64) {
	o.Port = &v
}

// GetRallyUsernameAttribute returns the RallyUsernameAttribute field value if set, zero value otherwise.
func (o *LDAPConfiguration) GetRallyUsernameAttribute() string {
	if o == nil || IsNil(o.RallyUsernameAttribute) {
		var ret string
		return ret
	}
	return *o.RallyUsernameAttribute
}

// GetRallyUsernameAttributeOk returns a tuple with the RallyUsernameAttribute field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LDAPConfiguration) GetRallyUsernameAttributeOk() (*string, bool) {
	if o == nil || IsNil(o.RallyUsernameAttribute) {
		return nil, false
	}
	return o.RallyUsernameAttribute, true
}

// HasRallyUsernameAttribute returns a boolean if a field has been set.
func (o *LDAPConfiguration) HasRallyUsernameAttribute() bool {
	if o != nil && !IsNil(o.RallyUsernameAttribute) {
		return true
	}

	return false
}

// SetRallyUsernameAttribute gets a reference to the given string and assigns it to the RallyUsernameAttribute field.
func (o *LDAPConfiguration) SetRallyUsernameAttribute(v string) {
	o.RallyUsernameAttribute = &v
}

// GetSSLCert returns the SSLCert field value if set, zero value otherwise.
func (o *LDAPConfiguration) GetSSLCert() string {
	if o == nil || IsNil(o.SSLCert) {
		var ret string
		return ret
	}
	return *o.SSLCert
}

// GetSSLCertOk returns a tuple with the SSLCert field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LDAPConfiguration) GetSSLCertOk() (*string, bool) {
	if o == nil || IsNil(o.SSLCert) {
		return nil, false
	}
	return o.SSLCert, true
}

// HasSSLCert returns a boolean if a field has been set.
func (o *LDAPConfiguration) HasSSLCert() bool {
	if o != nil && !IsNil(o.SSLCert) {
		return true
	}

	return false
}

// SetSSLCert gets a reference to the given string and assigns it to the SSLCert field.
func (o *LDAPConfiguration) SetSSLCert(v string) {
	o.SSLCert = &v
}

// GetSubscriptionID returns the SubscriptionID field value if set, zero value otherwise.
func (o *LDAPConfiguration) GetSubscriptionID() int64 {
	if o == nil || IsNil(o.SubscriptionID) {
		var ret int64
		return ret
	}
	return *o.SubscriptionID
}

// GetSubscriptionIDOk returns a tuple with the SubscriptionID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LDAPConfiguration) GetSubscriptionIDOk() (*int64, bool) {
	if o == nil || IsNil(o.SubscriptionID) {
		return nil, false
	}
	return o.SubscriptionID, true
}

// HasSubscriptionID returns a boolean if a field has been set.
func (o *LDAPConfiguration) HasSubscriptionID() bool {
	if o != nil && !IsNil(o.SubscriptionID) {
		return true
	}

	return false
}

// SetSubscriptionID gets a reference to the given int64 and assigns it to the SubscriptionID field.
func (o *LDAPConfiguration) SetSubscriptionID(v int64) {
	o.SubscriptionID = &v
}

// GetUseSSL returns the UseSSL field value if set, zero value otherwise.
func (o *LDAPConfiguration) GetUseSSL() bool {
	if o == nil || IsNil(o.UseSSL) {
		var ret bool
		return ret
	}
	return *o.UseSSL
}

// GetUseSSLOk returns a tuple with the UseSSL field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LDAPConfiguration) GetUseSSLOk() (*bool, bool) {
	if o == nil || IsNil(o.UseSSL) {
		return nil, false
	}
	return o.UseSSL, true
}

// HasUseSSL returns a boolean if a field has been set.
func (o *LDAPConfiguration) HasUseSSL() bool {
	if o != nil && !IsNil(o.UseSSL) {
		return true
	}

	return false
}

// SetUseSSL gets a reference to the given bool and assigns it to the UseSSL field.
func (o *LDAPConfiguration) SetUseSSL(v bool) {
	o.UseSSL = &v
}

// GetUserFilterQuery returns the UserFilterQuery field value if set, zero value otherwise.
func (o *LDAPConfiguration) GetUserFilterQuery() string {
	if o == nil || IsNil(o.UserFilterQuery) {
		var ret string
		return ret
	}
	return *o.UserFilterQuery
}

// GetUserFilterQueryOk returns a tuple with the UserFilterQuery field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LDAPConfiguration) GetUserFilterQueryOk() (*string, bool) {
	if o == nil || IsNil(o.UserFilterQuery) {
		return nil, false
	}
	return o.UserFilterQuery, true
}

// HasUserFilterQuery returns a boolean if a field has been set.
func (o *LDAPConfiguration) HasUserFilterQuery() bool {
	if o != nil && !IsNil(o.UserFilterQuery) {
		return true
	}

	return false
}

// SetUserFilterQuery gets a reference to the given string and assigns it to the UserFilterQuery field.
func (o *LDAPConfiguration) SetUserFilterQuery(v string) {
	o.UserFilterQuery = &v
}

// GetVersionId returns the VersionId field value if set, zero value otherwise.
func (o *LDAPConfiguration) GetVersionId() string {
	if o == nil || IsNil(o.VersionId) {
		var ret string
		return ret
	}
	return *o.VersionId
}

// GetVersionIdOk returns a tuple with the VersionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LDAPConfiguration) GetVersionIdOk() (*string, bool) {
	if o == nil || IsNil(o.VersionId) {
		return nil, false
	}
	return o.VersionId, true
}

// HasVersionId returns a boolean if a field has been set.
func (o *LDAPConfiguration) HasVersionId() bool {
	if o != nil && !IsNil(o.VersionId) {
		return true
	}

	return false
}

// SetVersionId gets a reference to the given string and assigns it to the VersionId field.
func (o *LDAPConfiguration) SetVersionId(v string) {
	o.VersionId = &v
}

// GetWarnings returns the Warnings field value if set, zero value otherwise.
func (o *LDAPConfiguration) GetWarnings() []string {
	if o == nil || IsNil(o.Warnings) {
		var ret []string
		return ret
	}
	return o.Warnings
}

// GetWarningsOk returns a tuple with the Warnings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LDAPConfiguration) GetWarningsOk() ([]string, bool) {
	if o == nil || IsNil(o.Warnings) {
		return nil, false
	}
	return o.Warnings, true
}

// HasWarnings returns a boolean if a field has been set.
func (o *LDAPConfiguration) HasWarnings() bool {
	if o != nil && !IsNil(o.Warnings) {
		return true
	}

	return false
}

// SetWarnings gets a reference to the given []string and assigns it to the Warnings field.
func (o *LDAPConfiguration) SetWarnings(v []string) {
	o.Warnings = v
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *LDAPConfiguration) GetErrors() []string {
	if o == nil || IsNil(o.Errors) {
		var ret []string
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LDAPConfiguration) GetErrorsOk() ([]string, bool) {
	if o == nil || IsNil(o.Errors) {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *LDAPConfiguration) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []string and assigns it to the Errors field.
func (o *LDAPConfiguration) SetErrors(v []string) {
	o.Errors = v
}

func (o LDAPConfiguration) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LDAPConfiguration) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AdminDN) {
		toSerialize["AdminDN"] = o.AdminDN
	}
	if !IsNil(o.AdminPassword) {
		toSerialize["AdminPassword"] = o.AdminPassword
	}
	if !IsNil(o.BaseDN) {
		toSerialize["BaseDN"] = o.BaseDN
	}
	if !IsNil(o.CreationDate) {
		toSerialize["CreationDate"] = o.CreationDate
	}
	if !IsNil(o.DisplayNameAttribute) {
		toSerialize["DisplayNameAttribute"] = o.DisplayNameAttribute
	}
	if !IsNil(o.EmailAttribute) {
		toSerialize["EmailAttribute"] = o.EmailAttribute
	}
	if !IsNil(o.EnableUserSync) {
		toSerialize["EnableUserSync"] = o.EnableUserSync
	}
	if !IsNil(o.FirstNameAttribute) {
		toSerialize["FirstNameAttribute"] = o.FirstNameAttribute
	}
	if !IsNil(o.Host) {
		toSerialize["Host"] = o.Host
	}
	if !IsNil(o.InactiveAttribute) {
		toSerialize["InactiveAttribute"] = o.InactiveAttribute
	}
	if !IsNil(o.InactiveValue) {
		toSerialize["InactiveValue"] = o.InactiveValue
	}
	if !IsNil(o.LDAPUsernameAttribute) {
		toSerialize["LDAPUsernameAttribute"] = o.LDAPUsernameAttribute
	}
	if !IsNil(o.LastNameAttribute) {
		toSerialize["LastNameAttribute"] = o.LastNameAttribute
	}
	if !IsNil(o.ObjectID) {
		toSerialize["ObjectID"] = o.ObjectID
	}
	if !IsNil(o.ObjectUUID) {
		toSerialize["ObjectUUID"] = o.ObjectUUID
	}
	if !IsNil(o.Port) {
		toSerialize["Port"] = o.Port
	}
	if !IsNil(o.RallyUsernameAttribute) {
		toSerialize["RallyUsernameAttribute"] = o.RallyUsernameAttribute
	}
	if !IsNil(o.SSLCert) {
		toSerialize["SSLCert"] = o.SSLCert
	}
	if !IsNil(o.SubscriptionID) {
		toSerialize["SubscriptionID"] = o.SubscriptionID
	}
	if !IsNil(o.UseSSL) {
		toSerialize["UseSSL"] = o.UseSSL
	}
	if !IsNil(o.UserFilterQuery) {
		toSerialize["UserFilterQuery"] = o.UserFilterQuery
	}
	if !IsNil(o.VersionId) {
		toSerialize["VersionId"] = o.VersionId
	}
	if !IsNil(o.Warnings) {
		toSerialize["Warnings"] = o.Warnings
	}
	if !IsNil(o.Errors) {
		toSerialize["Errors"] = o.Errors
	}
	return toSerialize, nil
}

type NullableLDAPConfiguration struct {
	value *LDAPConfiguration
	isSet bool
}

func (v NullableLDAPConfiguration) Get() *LDAPConfiguration {
	return v.value
}

func (v *NullableLDAPConfiguration) Set(val *LDAPConfiguration) {
	v.value = val
	v.isSet = true
}

func (v NullableLDAPConfiguration) IsSet() bool {
	return v.isSet
}

func (v *NullableLDAPConfiguration) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLDAPConfiguration(val *LDAPConfiguration) *NullableLDAPConfiguration {
	return &NullableLDAPConfiguration{value: val, isSet: true}
}

func (v NullableLDAPConfiguration) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLDAPConfiguration) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


