/*
Rally WebService API

Rally Open API docs

API version: v2.0
Contact: support@rallydev.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the TestCaseCreate200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TestCaseCreate200Response{}

// TestCaseCreate200Response struct for TestCaseCreate200Response
type TestCaseCreate200Response struct {
	CreateResult *TestCaseCreate200ResponseCreateResult `json:"CreateResult,omitempty"`
}

// NewTestCaseCreate200Response instantiates a new TestCaseCreate200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTestCaseCreate200Response() *TestCaseCreate200Response {
	this := TestCaseCreate200Response{}
	return &this
}

// NewTestCaseCreate200ResponseWithDefaults instantiates a new TestCaseCreate200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTestCaseCreate200ResponseWithDefaults() *TestCaseCreate200Response {
	this := TestCaseCreate200Response{}
	return &this
}

// GetCreateResult returns the CreateResult field value if set, zero value otherwise.
func (o *TestCaseCreate200Response) GetCreateResult() TestCaseCreate200ResponseCreateResult {
	if o == nil || IsNil(o.CreateResult) {
		var ret TestCaseCreate200ResponseCreateResult
		return ret
	}
	return *o.CreateResult
}

// GetCreateResultOk returns a tuple with the CreateResult field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TestCaseCreate200Response) GetCreateResultOk() (*TestCaseCreate200ResponseCreateResult, bool) {
	if o == nil || IsNil(o.CreateResult) {
		return nil, false
	}
	return o.CreateResult, true
}

// HasCreateResult returns a boolean if a field has been set.
func (o *TestCaseCreate200Response) HasCreateResult() bool {
	if o != nil && !IsNil(o.CreateResult) {
		return true
	}

	return false
}

// SetCreateResult gets a reference to the given TestCaseCreate200ResponseCreateResult and assigns it to the CreateResult field.
func (o *TestCaseCreate200Response) SetCreateResult(v TestCaseCreate200ResponseCreateResult) {
	o.CreateResult = &v
}

func (o TestCaseCreate200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TestCaseCreate200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CreateResult) {
		toSerialize["CreateResult"] = o.CreateResult
	}
	return toSerialize, nil
}

type NullableTestCaseCreate200Response struct {
	value *TestCaseCreate200Response
	isSet bool
}

func (v NullableTestCaseCreate200Response) Get() *TestCaseCreate200Response {
	return v.value
}

func (v *NullableTestCaseCreate200Response) Set(val *TestCaseCreate200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableTestCaseCreate200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableTestCaseCreate200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTestCaseCreate200Response(val *TestCaseCreate200Response) *NullableTestCaseCreate200Response {
	return &NullableTestCaseCreate200Response{value: val, isSet: true}
}

func (v NullableTestCaseCreate200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTestCaseCreate200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
