/*
Rally WebService API

Rally Open API docs

API version: v2.0
Contact: support@rallydev.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the VSMIncidentMutation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VSMIncidentMutation{}

// VSMIncidentMutation VSMIncident
type VSMIncidentMutation struct {
	VSMIncident *VSMIncidentMutationVSMIncident `json:"VSMIncident,omitempty"`
}

// NewVSMIncidentMutation instantiates a new VSMIncidentMutation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVSMIncidentMutation() *VSMIncidentMutation {
	this := VSMIncidentMutation{}
	return &this
}

// NewVSMIncidentMutationWithDefaults instantiates a new VSMIncidentMutation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVSMIncidentMutationWithDefaults() *VSMIncidentMutation {
	this := VSMIncidentMutation{}
	return &this
}

// GetVSMIncident returns the VSMIncident field value if set, zero value otherwise.
func (o *VSMIncidentMutation) GetVSMIncident() VSMIncidentMutationVSMIncident {
	if o == nil || IsNil(o.VSMIncident) {
		var ret VSMIncidentMutationVSMIncident
		return ret
	}
	return *o.VSMIncident
}

// GetVSMIncidentOk returns a tuple with the VSMIncident field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VSMIncidentMutation) GetVSMIncidentOk() (*VSMIncidentMutationVSMIncident, bool) {
	if o == nil || IsNil(o.VSMIncident) {
		return nil, false
	}
	return o.VSMIncident, true
}

// HasVSMIncident returns a boolean if a field has been set.
func (o *VSMIncidentMutation) HasVSMIncident() bool {
	if o != nil && !IsNil(o.VSMIncident) {
		return true
	}

	return false
}

// SetVSMIncident gets a reference to the given VSMIncidentMutationVSMIncident and assigns it to the VSMIncident field.
func (o *VSMIncidentMutation) SetVSMIncident(v VSMIncidentMutationVSMIncident) {
	o.VSMIncident = &v
}

func (o VSMIncidentMutation) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VSMIncidentMutation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.VSMIncident) {
		toSerialize["VSMIncident"] = o.VSMIncident
	}
	return toSerialize, nil
}

type NullableVSMIncidentMutation struct {
	value *VSMIncidentMutation
	isSet bool
}

func (v NullableVSMIncidentMutation) Get() *VSMIncidentMutation {
	return v.value
}

func (v *NullableVSMIncidentMutation) Set(val *VSMIncidentMutation) {
	v.value = val
	v.isSet = true
}

func (v NullableVSMIncidentMutation) IsSet() bool {
	return v.isSet
}

func (v *NullableVSMIncidentMutation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVSMIncidentMutation(val *VSMIncidentMutation) *NullableVSMIncidentMutation {
	return &NullableVSMIncidentMutation{value: val, isSet: true}
}

func (v NullableVSMIncidentMutation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVSMIncidentMutation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
