/*
Rally WebService API

Rally Open API docs

API version: v2.0
Contact: support@rallydev.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ExpertiseDemandMutation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExpertiseDemandMutation{}

// ExpertiseDemandMutation ExpertiseDemand
type ExpertiseDemandMutation struct {
	ExpertiseDemand *ExpertiseDemandMutationExpertiseDemand `json:"ExpertiseDemand,omitempty"`
}

// NewExpertiseDemandMutation instantiates a new ExpertiseDemandMutation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExpertiseDemandMutation() *ExpertiseDemandMutation {
	this := ExpertiseDemandMutation{}
	return &this
}

// NewExpertiseDemandMutationWithDefaults instantiates a new ExpertiseDemandMutation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExpertiseDemandMutationWithDefaults() *ExpertiseDemandMutation {
	this := ExpertiseDemandMutation{}
	return &this
}

// GetExpertiseDemand returns the ExpertiseDemand field value if set, zero value otherwise.
func (o *ExpertiseDemandMutation) GetExpertiseDemand() ExpertiseDemandMutationExpertiseDemand {
	if o == nil || IsNil(o.ExpertiseDemand) {
		var ret ExpertiseDemandMutationExpertiseDemand
		return ret
	}
	return *o.ExpertiseDemand
}

// GetExpertiseDemandOk returns a tuple with the ExpertiseDemand field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpertiseDemandMutation) GetExpertiseDemandOk() (*ExpertiseDemandMutationExpertiseDemand, bool) {
	if o == nil || IsNil(o.ExpertiseDemand) {
		return nil, false
	}
	return o.ExpertiseDemand, true
}

// HasExpertiseDemand returns a boolean if a field has been set.
func (o *ExpertiseDemandMutation) HasExpertiseDemand() bool {
	if o != nil && !IsNil(o.ExpertiseDemand) {
		return true
	}

	return false
}

// SetExpertiseDemand gets a reference to the given ExpertiseDemandMutationExpertiseDemand and assigns it to the ExpertiseDemand field.
func (o *ExpertiseDemandMutation) SetExpertiseDemand(v ExpertiseDemandMutationExpertiseDemand) {
	o.ExpertiseDemand = &v
}

func (o ExpertiseDemandMutation) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExpertiseDemandMutation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ExpertiseDemand) {
		toSerialize["ExpertiseDemand"] = o.ExpertiseDemand
	}
	return toSerialize, nil
}

type NullableExpertiseDemandMutation struct {
	value *ExpertiseDemandMutation
	isSet bool
}

func (v NullableExpertiseDemandMutation) Get() *ExpertiseDemandMutation {
	return v.value
}

func (v *NullableExpertiseDemandMutation) Set(val *ExpertiseDemandMutation) {
	v.value = val
	v.isSet = true
}

func (v NullableExpertiseDemandMutation) IsSet() bool {
	return v.isSet
}

func (v *NullableExpertiseDemandMutation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExpertiseDemandMutation(val *ExpertiseDemandMutation) *NullableExpertiseDemandMutation {
	return &NullableExpertiseDemandMutation{value: val, isSet: true}
}

func (v NullableExpertiseDemandMutation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExpertiseDemandMutation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


