/*
Rally WebService API

Rally Open API docs

API version: v2.0
Contact: support@rallydev.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DataMoveRequestRef type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DataMoveRequestRef{}

// DataMoveRequestRef Reference to DataMoveRequest
type DataMoveRequestRef struct {
	Ref string `json:"_ref"`
}

type _DataMoveRequestRef DataMoveRequestRef

// NewDataMoveRequestRef instantiates a new DataMoveRequestRef object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDataMoveRequestRef(ref string) *DataMoveRequestRef {
	this := DataMoveRequestRef{}
	this.Ref = ref
	return &this
}

// NewDataMoveRequestRefWithDefaults instantiates a new DataMoveRequestRef object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDataMoveRequestRefWithDefaults() *DataMoveRequestRef {
	this := DataMoveRequestRef{}
	return &this
}

// GetRef returns the Ref field value
func (o *DataMoveRequestRef) GetRef() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Ref
}

// GetRefOk returns a tuple with the Ref field value
// and a boolean to check if the value has been set.
func (o *DataMoveRequestRef) GetRefOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ref, true
}

// SetRef sets field value
func (o *DataMoveRequestRef) SetRef(v string) {
	o.Ref = v
}

func (o DataMoveRequestRef) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DataMoveRequestRef) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["_ref"] = o.Ref
	return toSerialize, nil
}

func (o *DataMoveRequestRef) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"_ref",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDataMoveRequestRef := _DataMoveRequestRef{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDataMoveRequestRef)

	if err != nil {
		return err
	}

	*o = DataMoveRequestRef(varDataMoveRequestRef)

	return err
}

type NullableDataMoveRequestRef struct {
	value *DataMoveRequestRef
	isSet bool
}

func (v NullableDataMoveRequestRef) Get() *DataMoveRequestRef {
	return v.value
}

func (v *NullableDataMoveRequestRef) Set(val *DataMoveRequestRef) {
	v.value = val
	v.isSet = true
}

func (v NullableDataMoveRequestRef) IsSet() bool {
	return v.isSet
}

func (v *NullableDataMoveRequestRef) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDataMoveRequestRef(val *DataMoveRequestRef) *NullableDataMoveRequestRef {
	return &NullableDataMoveRequestRef{value: val, isSet: true}
}

func (v NullableDataMoveRequestRef) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDataMoveRequestRef) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


