/*
Rally WebService API

Rally Open API docs

API version: v2.0
Contact: support@rallydev.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the VSMOutcomeCreate200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VSMOutcomeCreate200Response{}

// VSMOutcomeCreate200Response struct for VSMOutcomeCreate200Response
type VSMOutcomeCreate200Response struct {
	CreateResult *VSMOutcomeCreate200ResponseCreateResult `json:"CreateResult,omitempty"`
}

// NewVSMOutcomeCreate200Response instantiates a new VSMOutcomeCreate200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVSMOutcomeCreate200Response() *VSMOutcomeCreate200Response {
	this := VSMOutcomeCreate200Response{}
	return &this
}

// NewVSMOutcomeCreate200ResponseWithDefaults instantiates a new VSMOutcomeCreate200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVSMOutcomeCreate200ResponseWithDefaults() *VSMOutcomeCreate200Response {
	this := VSMOutcomeCreate200Response{}
	return &this
}

// GetCreateResult returns the CreateResult field value if set, zero value otherwise.
func (o *VSMOutcomeCreate200Response) GetCreateResult() VSMOutcomeCreate200ResponseCreateResult {
	if o == nil || IsNil(o.CreateResult) {
		var ret VSMOutcomeCreate200ResponseCreateResult
		return ret
	}
	return *o.CreateResult
}

// GetCreateResultOk returns a tuple with the CreateResult field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VSMOutcomeCreate200Response) GetCreateResultOk() (*VSMOutcomeCreate200ResponseCreateResult, bool) {
	if o == nil || IsNil(o.CreateResult) {
		return nil, false
	}
	return o.CreateResult, true
}

// HasCreateResult returns a boolean if a field has been set.
func (o *VSMOutcomeCreate200Response) HasCreateResult() bool {
	if o != nil && !IsNil(o.CreateResult) {
		return true
	}

	return false
}

// SetCreateResult gets a reference to the given VSMOutcomeCreate200ResponseCreateResult and assigns it to the CreateResult field.
func (o *VSMOutcomeCreate200Response) SetCreateResult(v VSMOutcomeCreate200ResponseCreateResult) {
	o.CreateResult = &v
}

func (o VSMOutcomeCreate200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VSMOutcomeCreate200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CreateResult) {
		toSerialize["CreateResult"] = o.CreateResult
	}
	return toSerialize, nil
}

type NullableVSMOutcomeCreate200Response struct {
	value *VSMOutcomeCreate200Response
	isSet bool
}

func (v NullableVSMOutcomeCreate200Response) Get() *VSMOutcomeCreate200Response {
	return v.value
}

func (v *NullableVSMOutcomeCreate200Response) Set(val *VSMOutcomeCreate200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableVSMOutcomeCreate200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableVSMOutcomeCreate200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVSMOutcomeCreate200Response(val *VSMOutcomeCreate200Response) *NullableVSMOutcomeCreate200Response {
	return &NullableVSMOutcomeCreate200Response{value: val, isSet: true}
}

func (v NullableVSMOutcomeCreate200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVSMOutcomeCreate200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
