/*
Rally WebService API

Rally Open API docs

API version: v2.0
Contact: support@rallydev.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the Release type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Release{}

// Release Release
type Release struct {
	// Accepted
	Accepted *float32 `json:"Accepted,omitempty"`
	// CascadedToChildren
	CascadedToChildren *bool `json:"CascadedToChildren,omitempty"`
	// Children Planned Velocity
	ChildrenPlannedVelocity *float32 `json:"ChildrenPlannedVelocity,omitempty"`
	// Creation Date
	CreationDate *string `json:"CreationDate,omitempty"`
	// Gross Estimate Conversion Ratio
	GrossEstimateConversionRatio *float32 `json:"GrossEstimateConversionRatio,omitempty"`
	// Last Update Date
	LastUpdateDate *string `json:"LastUpdateDate,omitempty"`
	// Name
	Name *string `json:"Name,omitempty"`
	// Notes
	Notes *string `json:"Notes,omitempty"`
	// Object ID
	ObjectID *int64 `json:"ObjectID,omitempty"`
	// ObjectUUID
	ObjectUUID *string `json:"ObjectUUID,omitempty"`
	// Plan Estimate
	PlanEstimate *float32 `json:"PlanEstimate,omitempty"`
	// Planned Velocity
	PlannedVelocity *float32 `json:"PlannedVelocity,omitempty"`
	Project *ProjectRef `json:"Project,omitempty"`
	// Release Backlog Items Count
	ReleaseBacklogItemsCount *int64 `json:"ReleaseBacklogItemsCount,omitempty"`
	// Release Date
	ReleaseDate *string `json:"ReleaseDate,omitempty"`
	// Release Start Date
	ReleaseStartDate *string `json:"ReleaseStartDate,omitempty"`
	RevisionHistory *RevisionHistoryRef `json:"RevisionHistory,omitempty"`
	// State
	State *string `json:"State,omitempty"`
	Subscription *SubscriptionRef `json:"Subscription,omitempty"`
	// SyncedWithParent
	SyncedWithParent *bool `json:"SyncedWithParent,omitempty"`
	// Task Actual Total
	TaskActualTotal *float32 `json:"TaskActualTotal,omitempty"`
	// Task Estimate Total
	TaskEstimateTotal *float32 `json:"TaskEstimateTotal,omitempty"`
	// Task Remaining Total
	TaskRemainingTotal *float32 `json:"TaskRemainingTotal,omitempty"`
	// Theme
	Theme *string `json:"Theme,omitempty"`
	// Version
	Version *string `json:"Version,omitempty"`
	// VersionId
	VersionId *string `json:"VersionId,omitempty"`
	WorkProducts *Collection `json:"WorkProducts,omitempty"`
	Workspace *WorkspaceRef `json:"Workspace,omitempty"`
	Warnings []string `json:"Warnings,omitempty"`
	Errors []string `json:"Errors,omitempty"`
}

// NewRelease instantiates a new Release object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRelease() *Release {
	this := Release{}
	return &this
}

// NewReleaseWithDefaults instantiates a new Release object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReleaseWithDefaults() *Release {
	this := Release{}
	return &this
}

// GetAccepted returns the Accepted field value if set, zero value otherwise.
func (o *Release) GetAccepted() float32 {
	if o == nil || IsNil(o.Accepted) {
		var ret float32
		return ret
	}
	return *o.Accepted
}

// GetAcceptedOk returns a tuple with the Accepted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Release) GetAcceptedOk() (*float32, bool) {
	if o == nil || IsNil(o.Accepted) {
		return nil, false
	}
	return o.Accepted, true
}

// HasAccepted returns a boolean if a field has been set.
func (o *Release) HasAccepted() bool {
	if o != nil && !IsNil(o.Accepted) {
		return true
	}

	return false
}

// SetAccepted gets a reference to the given float32 and assigns it to the Accepted field.
func (o *Release) SetAccepted(v float32) {
	o.Accepted = &v
}

// GetCascadedToChildren returns the CascadedToChildren field value if set, zero value otherwise.
func (o *Release) GetCascadedToChildren() bool {
	if o == nil || IsNil(o.CascadedToChildren) {
		var ret bool
		return ret
	}
	return *o.CascadedToChildren
}

// GetCascadedToChildrenOk returns a tuple with the CascadedToChildren field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Release) GetCascadedToChildrenOk() (*bool, bool) {
	if o == nil || IsNil(o.CascadedToChildren) {
		return nil, false
	}
	return o.CascadedToChildren, true
}

// HasCascadedToChildren returns a boolean if a field has been set.
func (o *Release) HasCascadedToChildren() bool {
	if o != nil && !IsNil(o.CascadedToChildren) {
		return true
	}

	return false
}

// SetCascadedToChildren gets a reference to the given bool and assigns it to the CascadedToChildren field.
func (o *Release) SetCascadedToChildren(v bool) {
	o.CascadedToChildren = &v
}

// GetChildrenPlannedVelocity returns the ChildrenPlannedVelocity field value if set, zero value otherwise.
func (o *Release) GetChildrenPlannedVelocity() float32 {
	if o == nil || IsNil(o.ChildrenPlannedVelocity) {
		var ret float32
		return ret
	}
	return *o.ChildrenPlannedVelocity
}

// GetChildrenPlannedVelocityOk returns a tuple with the ChildrenPlannedVelocity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Release) GetChildrenPlannedVelocityOk() (*float32, bool) {
	if o == nil || IsNil(o.ChildrenPlannedVelocity) {
		return nil, false
	}
	return o.ChildrenPlannedVelocity, true
}

// HasChildrenPlannedVelocity returns a boolean if a field has been set.
func (o *Release) HasChildrenPlannedVelocity() bool {
	if o != nil && !IsNil(o.ChildrenPlannedVelocity) {
		return true
	}

	return false
}

// SetChildrenPlannedVelocity gets a reference to the given float32 and assigns it to the ChildrenPlannedVelocity field.
func (o *Release) SetChildrenPlannedVelocity(v float32) {
	o.ChildrenPlannedVelocity = &v
}

// GetCreationDate returns the CreationDate field value if set, zero value otherwise.
func (o *Release) GetCreationDate() string {
	if o == nil || IsNil(o.CreationDate) {
		var ret string
		return ret
	}
	return *o.CreationDate
}

// GetCreationDateOk returns a tuple with the CreationDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Release) GetCreationDateOk() (*string, bool) {
	if o == nil || IsNil(o.CreationDate) {
		return nil, false
	}
	return o.CreationDate, true
}

// HasCreationDate returns a boolean if a field has been set.
func (o *Release) HasCreationDate() bool {
	if o != nil && !IsNil(o.CreationDate) {
		return true
	}

	return false
}

// SetCreationDate gets a reference to the given string and assigns it to the CreationDate field.
func (o *Release) SetCreationDate(v string) {
	o.CreationDate = &v
}

// GetGrossEstimateConversionRatio returns the GrossEstimateConversionRatio field value if set, zero value otherwise.
func (o *Release) GetGrossEstimateConversionRatio() float32 {
	if o == nil || IsNil(o.GrossEstimateConversionRatio) {
		var ret float32
		return ret
	}
	return *o.GrossEstimateConversionRatio
}

// GetGrossEstimateConversionRatioOk returns a tuple with the GrossEstimateConversionRatio field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Release) GetGrossEstimateConversionRatioOk() (*float32, bool) {
	if o == nil || IsNil(o.GrossEstimateConversionRatio) {
		return nil, false
	}
	return o.GrossEstimateConversionRatio, true
}

// HasGrossEstimateConversionRatio returns a boolean if a field has been set.
func (o *Release) HasGrossEstimateConversionRatio() bool {
	if o != nil && !IsNil(o.GrossEstimateConversionRatio) {
		return true
	}

	return false
}

// SetGrossEstimateConversionRatio gets a reference to the given float32 and assigns it to the GrossEstimateConversionRatio field.
func (o *Release) SetGrossEstimateConversionRatio(v float32) {
	o.GrossEstimateConversionRatio = &v
}

// GetLastUpdateDate returns the LastUpdateDate field value if set, zero value otherwise.
func (o *Release) GetLastUpdateDate() string {
	if o == nil || IsNil(o.LastUpdateDate) {
		var ret string
		return ret
	}
	return *o.LastUpdateDate
}

// GetLastUpdateDateOk returns a tuple with the LastUpdateDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Release) GetLastUpdateDateOk() (*string, bool) {
	if o == nil || IsNil(o.LastUpdateDate) {
		return nil, false
	}
	return o.LastUpdateDate, true
}

// HasLastUpdateDate returns a boolean if a field has been set.
func (o *Release) HasLastUpdateDate() bool {
	if o != nil && !IsNil(o.LastUpdateDate) {
		return true
	}

	return false
}

// SetLastUpdateDate gets a reference to the given string and assigns it to the LastUpdateDate field.
func (o *Release) SetLastUpdateDate(v string) {
	o.LastUpdateDate = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *Release) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Release) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *Release) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *Release) SetName(v string) {
	o.Name = &v
}

// GetNotes returns the Notes field value if set, zero value otherwise.
func (o *Release) GetNotes() string {
	if o == nil || IsNil(o.Notes) {
		var ret string
		return ret
	}
	return *o.Notes
}

// GetNotesOk returns a tuple with the Notes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Release) GetNotesOk() (*string, bool) {
	if o == nil || IsNil(o.Notes) {
		return nil, false
	}
	return o.Notes, true
}

// HasNotes returns a boolean if a field has been set.
func (o *Release) HasNotes() bool {
	if o != nil && !IsNil(o.Notes) {
		return true
	}

	return false
}

// SetNotes gets a reference to the given string and assigns it to the Notes field.
func (o *Release) SetNotes(v string) {
	o.Notes = &v
}

// GetObjectID returns the ObjectID field value if set, zero value otherwise.
func (o *Release) GetObjectID() int64 {
	if o == nil || IsNil(o.ObjectID) {
		var ret int64
		return ret
	}
	return *o.ObjectID
}

// GetObjectIDOk returns a tuple with the ObjectID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Release) GetObjectIDOk() (*int64, bool) {
	if o == nil || IsNil(o.ObjectID) {
		return nil, false
	}
	return o.ObjectID, true
}

// HasObjectID returns a boolean if a field has been set.
func (o *Release) HasObjectID() bool {
	if o != nil && !IsNil(o.ObjectID) {
		return true
	}

	return false
}

// SetObjectID gets a reference to the given int64 and assigns it to the ObjectID field.
func (o *Release) SetObjectID(v int64) {
	o.ObjectID = &v
}

// GetObjectUUID returns the ObjectUUID field value if set, zero value otherwise.
func (o *Release) GetObjectUUID() string {
	if o == nil || IsNil(o.ObjectUUID) {
		var ret string
		return ret
	}
	return *o.ObjectUUID
}

// GetObjectUUIDOk returns a tuple with the ObjectUUID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Release) GetObjectUUIDOk() (*string, bool) {
	if o == nil || IsNil(o.ObjectUUID) {
		return nil, false
	}
	return o.ObjectUUID, true
}

// HasObjectUUID returns a boolean if a field has been set.
func (o *Release) HasObjectUUID() bool {
	if o != nil && !IsNil(o.ObjectUUID) {
		return true
	}

	return false
}

// SetObjectUUID gets a reference to the given string and assigns it to the ObjectUUID field.
func (o *Release) SetObjectUUID(v string) {
	o.ObjectUUID = &v
}

// GetPlanEstimate returns the PlanEstimate field value if set, zero value otherwise.
func (o *Release) GetPlanEstimate() float32 {
	if o == nil || IsNil(o.PlanEstimate) {
		var ret float32
		return ret
	}
	return *o.PlanEstimate
}

// GetPlanEstimateOk returns a tuple with the PlanEstimate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Release) GetPlanEstimateOk() (*float32, bool) {
	if o == nil || IsNil(o.PlanEstimate) {
		return nil, false
	}
	return o.PlanEstimate, true
}

// HasPlanEstimate returns a boolean if a field has been set.
func (o *Release) HasPlanEstimate() bool {
	if o != nil && !IsNil(o.PlanEstimate) {
		return true
	}

	return false
}

// SetPlanEstimate gets a reference to the given float32 and assigns it to the PlanEstimate field.
func (o *Release) SetPlanEstimate(v float32) {
	o.PlanEstimate = &v
}

// GetPlannedVelocity returns the PlannedVelocity field value if set, zero value otherwise.
func (o *Release) GetPlannedVelocity() float32 {
	if o == nil || IsNil(o.PlannedVelocity) {
		var ret float32
		return ret
	}
	return *o.PlannedVelocity
}

// GetPlannedVelocityOk returns a tuple with the PlannedVelocity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Release) GetPlannedVelocityOk() (*float32, bool) {
	if o == nil || IsNil(o.PlannedVelocity) {
		return nil, false
	}
	return o.PlannedVelocity, true
}

// HasPlannedVelocity returns a boolean if a field has been set.
func (o *Release) HasPlannedVelocity() bool {
	if o != nil && !IsNil(o.PlannedVelocity) {
		return true
	}

	return false
}

// SetPlannedVelocity gets a reference to the given float32 and assigns it to the PlannedVelocity field.
func (o *Release) SetPlannedVelocity(v float32) {
	o.PlannedVelocity = &v
}

// GetProject returns the Project field value if set, zero value otherwise.
func (o *Release) GetProject() ProjectRef {
	if o == nil || IsNil(o.Project) {
		var ret ProjectRef
		return ret
	}
	return *o.Project
}

// GetProjectOk returns a tuple with the Project field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Release) GetProjectOk() (*ProjectRef, bool) {
	if o == nil || IsNil(o.Project) {
		return nil, false
	}
	return o.Project, true
}

// HasProject returns a boolean if a field has been set.
func (o *Release) HasProject() bool {
	if o != nil && !IsNil(o.Project) {
		return true
	}

	return false
}

// SetProject gets a reference to the given ProjectRef and assigns it to the Project field.
func (o *Release) SetProject(v ProjectRef) {
	o.Project = &v
}

// GetReleaseBacklogItemsCount returns the ReleaseBacklogItemsCount field value if set, zero value otherwise.
func (o *Release) GetReleaseBacklogItemsCount() int64 {
	if o == nil || IsNil(o.ReleaseBacklogItemsCount) {
		var ret int64
		return ret
	}
	return *o.ReleaseBacklogItemsCount
}

// GetReleaseBacklogItemsCountOk returns a tuple with the ReleaseBacklogItemsCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Release) GetReleaseBacklogItemsCountOk() (*int64, bool) {
	if o == nil || IsNil(o.ReleaseBacklogItemsCount) {
		return nil, false
	}
	return o.ReleaseBacklogItemsCount, true
}

// HasReleaseBacklogItemsCount returns a boolean if a field has been set.
func (o *Release) HasReleaseBacklogItemsCount() bool {
	if o != nil && !IsNil(o.ReleaseBacklogItemsCount) {
		return true
	}

	return false
}

// SetReleaseBacklogItemsCount gets a reference to the given int64 and assigns it to the ReleaseBacklogItemsCount field.
func (o *Release) SetReleaseBacklogItemsCount(v int64) {
	o.ReleaseBacklogItemsCount = &v
}

// GetReleaseDate returns the ReleaseDate field value if set, zero value otherwise.
func (o *Release) GetReleaseDate() string {
	if o == nil || IsNil(o.ReleaseDate) {
		var ret string
		return ret
	}
	return *o.ReleaseDate
}

// GetReleaseDateOk returns a tuple with the ReleaseDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Release) GetReleaseDateOk() (*string, bool) {
	if o == nil || IsNil(o.ReleaseDate) {
		return nil, false
	}
	return o.ReleaseDate, true
}

// HasReleaseDate returns a boolean if a field has been set.
func (o *Release) HasReleaseDate() bool {
	if o != nil && !IsNil(o.ReleaseDate) {
		return true
	}

	return false
}

// SetReleaseDate gets a reference to the given string and assigns it to the ReleaseDate field.
func (o *Release) SetReleaseDate(v string) {
	o.ReleaseDate = &v
}

// GetReleaseStartDate returns the ReleaseStartDate field value if set, zero value otherwise.
func (o *Release) GetReleaseStartDate() string {
	if o == nil || IsNil(o.ReleaseStartDate) {
		var ret string
		return ret
	}
	return *o.ReleaseStartDate
}

// GetReleaseStartDateOk returns a tuple with the ReleaseStartDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Release) GetReleaseStartDateOk() (*string, bool) {
	if o == nil || IsNil(o.ReleaseStartDate) {
		return nil, false
	}
	return o.ReleaseStartDate, true
}

// HasReleaseStartDate returns a boolean if a field has been set.
func (o *Release) HasReleaseStartDate() bool {
	if o != nil && !IsNil(o.ReleaseStartDate) {
		return true
	}

	return false
}

// SetReleaseStartDate gets a reference to the given string and assigns it to the ReleaseStartDate field.
func (o *Release) SetReleaseStartDate(v string) {
	o.ReleaseStartDate = &v
}

// GetRevisionHistory returns the RevisionHistory field value if set, zero value otherwise.
func (o *Release) GetRevisionHistory() RevisionHistoryRef {
	if o == nil || IsNil(o.RevisionHistory) {
		var ret RevisionHistoryRef
		return ret
	}
	return *o.RevisionHistory
}

// GetRevisionHistoryOk returns a tuple with the RevisionHistory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Release) GetRevisionHistoryOk() (*RevisionHistoryRef, bool) {
	if o == nil || IsNil(o.RevisionHistory) {
		return nil, false
	}
	return o.RevisionHistory, true
}

// HasRevisionHistory returns a boolean if a field has been set.
func (o *Release) HasRevisionHistory() bool {
	if o != nil && !IsNil(o.RevisionHistory) {
		return true
	}

	return false
}

// SetRevisionHistory gets a reference to the given RevisionHistoryRef and assigns it to the RevisionHistory field.
func (o *Release) SetRevisionHistory(v RevisionHistoryRef) {
	o.RevisionHistory = &v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *Release) GetState() string {
	if o == nil || IsNil(o.State) {
		var ret string
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Release) GetStateOk() (*string, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *Release) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given string and assigns it to the State field.
func (o *Release) SetState(v string) {
	o.State = &v
}

// GetSubscription returns the Subscription field value if set, zero value otherwise.
func (o *Release) GetSubscription() SubscriptionRef {
	if o == nil || IsNil(o.Subscription) {
		var ret SubscriptionRef
		return ret
	}
	return *o.Subscription
}

// GetSubscriptionOk returns a tuple with the Subscription field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Release) GetSubscriptionOk() (*SubscriptionRef, bool) {
	if o == nil || IsNil(o.Subscription) {
		return nil, false
	}
	return o.Subscription, true
}

// HasSubscription returns a boolean if a field has been set.
func (o *Release) HasSubscription() bool {
	if o != nil && !IsNil(o.Subscription) {
		return true
	}

	return false
}

// SetSubscription gets a reference to the given SubscriptionRef and assigns it to the Subscription field.
func (o *Release) SetSubscription(v SubscriptionRef) {
	o.Subscription = &v
}

// GetSyncedWithParent returns the SyncedWithParent field value if set, zero value otherwise.
func (o *Release) GetSyncedWithParent() bool {
	if o == nil || IsNil(o.SyncedWithParent) {
		var ret bool
		return ret
	}
	return *o.SyncedWithParent
}

// GetSyncedWithParentOk returns a tuple with the SyncedWithParent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Release) GetSyncedWithParentOk() (*bool, bool) {
	if o == nil || IsNil(o.SyncedWithParent) {
		return nil, false
	}
	return o.SyncedWithParent, true
}

// HasSyncedWithParent returns a boolean if a field has been set.
func (o *Release) HasSyncedWithParent() bool {
	if o != nil && !IsNil(o.SyncedWithParent) {
		return true
	}

	return false
}

// SetSyncedWithParent gets a reference to the given bool and assigns it to the SyncedWithParent field.
func (o *Release) SetSyncedWithParent(v bool) {
	o.SyncedWithParent = &v
}

// GetTaskActualTotal returns the TaskActualTotal field value if set, zero value otherwise.
func (o *Release) GetTaskActualTotal() float32 {
	if o == nil || IsNil(o.TaskActualTotal) {
		var ret float32
		return ret
	}
	return *o.TaskActualTotal
}

// GetTaskActualTotalOk returns a tuple with the TaskActualTotal field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Release) GetTaskActualTotalOk() (*float32, bool) {
	if o == nil || IsNil(o.TaskActualTotal) {
		return nil, false
	}
	return o.TaskActualTotal, true
}

// HasTaskActualTotal returns a boolean if a field has been set.
func (o *Release) HasTaskActualTotal() bool {
	if o != nil && !IsNil(o.TaskActualTotal) {
		return true
	}

	return false
}

// SetTaskActualTotal gets a reference to the given float32 and assigns it to the TaskActualTotal field.
func (o *Release) SetTaskActualTotal(v float32) {
	o.TaskActualTotal = &v
}

// GetTaskEstimateTotal returns the TaskEstimateTotal field value if set, zero value otherwise.
func (o *Release) GetTaskEstimateTotal() float32 {
	if o == nil || IsNil(o.TaskEstimateTotal) {
		var ret float32
		return ret
	}
	return *o.TaskEstimateTotal
}

// GetTaskEstimateTotalOk returns a tuple with the TaskEstimateTotal field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Release) GetTaskEstimateTotalOk() (*float32, bool) {
	if o == nil || IsNil(o.TaskEstimateTotal) {
		return nil, false
	}
	return o.TaskEstimateTotal, true
}

// HasTaskEstimateTotal returns a boolean if a field has been set.
func (o *Release) HasTaskEstimateTotal() bool {
	if o != nil && !IsNil(o.TaskEstimateTotal) {
		return true
	}

	return false
}

// SetTaskEstimateTotal gets a reference to the given float32 and assigns it to the TaskEstimateTotal field.
func (o *Release) SetTaskEstimateTotal(v float32) {
	o.TaskEstimateTotal = &v
}

// GetTaskRemainingTotal returns the TaskRemainingTotal field value if set, zero value otherwise.
func (o *Release) GetTaskRemainingTotal() float32 {
	if o == nil || IsNil(o.TaskRemainingTotal) {
		var ret float32
		return ret
	}
	return *o.TaskRemainingTotal
}

// GetTaskRemainingTotalOk returns a tuple with the TaskRemainingTotal field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Release) GetTaskRemainingTotalOk() (*float32, bool) {
	if o == nil || IsNil(o.TaskRemainingTotal) {
		return nil, false
	}
	return o.TaskRemainingTotal, true
}

// HasTaskRemainingTotal returns a boolean if a field has been set.
func (o *Release) HasTaskRemainingTotal() bool {
	if o != nil && !IsNil(o.TaskRemainingTotal) {
		return true
	}

	return false
}

// SetTaskRemainingTotal gets a reference to the given float32 and assigns it to the TaskRemainingTotal field.
func (o *Release) SetTaskRemainingTotal(v float32) {
	o.TaskRemainingTotal = &v
}

// GetTheme returns the Theme field value if set, zero value otherwise.
func (o *Release) GetTheme() string {
	if o == nil || IsNil(o.Theme) {
		var ret string
		return ret
	}
	return *o.Theme
}

// GetThemeOk returns a tuple with the Theme field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Release) GetThemeOk() (*string, bool) {
	if o == nil || IsNil(o.Theme) {
		return nil, false
	}
	return o.Theme, true
}

// HasTheme returns a boolean if a field has been set.
func (o *Release) HasTheme() bool {
	if o != nil && !IsNil(o.Theme) {
		return true
	}

	return false
}

// SetTheme gets a reference to the given string and assigns it to the Theme field.
func (o *Release) SetTheme(v string) {
	o.Theme = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *Release) GetVersion() string {
	if o == nil || IsNil(o.Version) {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Release) GetVersionOk() (*string, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *Release) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *Release) SetVersion(v string) {
	o.Version = &v
}

// GetVersionId returns the VersionId field value if set, zero value otherwise.
func (o *Release) GetVersionId() string {
	if o == nil || IsNil(o.VersionId) {
		var ret string
		return ret
	}
	return *o.VersionId
}

// GetVersionIdOk returns a tuple with the VersionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Release) GetVersionIdOk() (*string, bool) {
	if o == nil || IsNil(o.VersionId) {
		return nil, false
	}
	return o.VersionId, true
}

// HasVersionId returns a boolean if a field has been set.
func (o *Release) HasVersionId() bool {
	if o != nil && !IsNil(o.VersionId) {
		return true
	}

	return false
}

// SetVersionId gets a reference to the given string and assigns it to the VersionId field.
func (o *Release) SetVersionId(v string) {
	o.VersionId = &v
}

// GetWorkProducts returns the WorkProducts field value if set, zero value otherwise.
func (o *Release) GetWorkProducts() Collection {
	if o == nil || IsNil(o.WorkProducts) {
		var ret Collection
		return ret
	}
	return *o.WorkProducts
}

// GetWorkProductsOk returns a tuple with the WorkProducts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Release) GetWorkProductsOk() (*Collection, bool) {
	if o == nil || IsNil(o.WorkProducts) {
		return nil, false
	}
	return o.WorkProducts, true
}

// HasWorkProducts returns a boolean if a field has been set.
func (o *Release) HasWorkProducts() bool {
	if o != nil && !IsNil(o.WorkProducts) {
		return true
	}

	return false
}

// SetWorkProducts gets a reference to the given Collection and assigns it to the WorkProducts field.
func (o *Release) SetWorkProducts(v Collection) {
	o.WorkProducts = &v
}

// GetWorkspace returns the Workspace field value if set, zero value otherwise.
func (o *Release) GetWorkspace() WorkspaceRef {
	if o == nil || IsNil(o.Workspace) {
		var ret WorkspaceRef
		return ret
	}
	return *o.Workspace
}

// GetWorkspaceOk returns a tuple with the Workspace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Release) GetWorkspaceOk() (*WorkspaceRef, bool) {
	if o == nil || IsNil(o.Workspace) {
		return nil, false
	}
	return o.Workspace, true
}

// HasWorkspace returns a boolean if a field has been set.
func (o *Release) HasWorkspace() bool {
	if o != nil && !IsNil(o.Workspace) {
		return true
	}

	return false
}

// SetWorkspace gets a reference to the given WorkspaceRef and assigns it to the Workspace field.
func (o *Release) SetWorkspace(v WorkspaceRef) {
	o.Workspace = &v
}

// GetWarnings returns the Warnings field value if set, zero value otherwise.
func (o *Release) GetWarnings() []string {
	if o == nil || IsNil(o.Warnings) {
		var ret []string
		return ret
	}
	return o.Warnings
}

// GetWarningsOk returns a tuple with the Warnings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Release) GetWarningsOk() ([]string, bool) {
	if o == nil || IsNil(o.Warnings) {
		return nil, false
	}
	return o.Warnings, true
}

// HasWarnings returns a boolean if a field has been set.
func (o *Release) HasWarnings() bool {
	if o != nil && !IsNil(o.Warnings) {
		return true
	}

	return false
}

// SetWarnings gets a reference to the given []string and assigns it to the Warnings field.
func (o *Release) SetWarnings(v []string) {
	o.Warnings = v
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *Release) GetErrors() []string {
	if o == nil || IsNil(o.Errors) {
		var ret []string
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Release) GetErrorsOk() ([]string, bool) {
	if o == nil || IsNil(o.Errors) {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *Release) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []string and assigns it to the Errors field.
func (o *Release) SetErrors(v []string) {
	o.Errors = v
}

func (o Release) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Release) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Accepted) {
		toSerialize["Accepted"] = o.Accepted
	}
	if !IsNil(o.CascadedToChildren) {
		toSerialize["CascadedToChildren"] = o.CascadedToChildren
	}
	if !IsNil(o.ChildrenPlannedVelocity) {
		toSerialize["ChildrenPlannedVelocity"] = o.ChildrenPlannedVelocity
	}
	if !IsNil(o.CreationDate) {
		toSerialize["CreationDate"] = o.CreationDate
	}
	if !IsNil(o.GrossEstimateConversionRatio) {
		toSerialize["GrossEstimateConversionRatio"] = o.GrossEstimateConversionRatio
	}
	if !IsNil(o.LastUpdateDate) {
		toSerialize["LastUpdateDate"] = o.LastUpdateDate
	}
	if !IsNil(o.Name) {
		toSerialize["Name"] = o.Name
	}
	if !IsNil(o.Notes) {
		toSerialize["Notes"] = o.Notes
	}
	if !IsNil(o.ObjectID) {
		toSerialize["ObjectID"] = o.ObjectID
	}
	if !IsNil(o.ObjectUUID) {
		toSerialize["ObjectUUID"] = o.ObjectUUID
	}
	if !IsNil(o.PlanEstimate) {
		toSerialize["PlanEstimate"] = o.PlanEstimate
	}
	if !IsNil(o.PlannedVelocity) {
		toSerialize["PlannedVelocity"] = o.PlannedVelocity
	}
	if !IsNil(o.Project) {
		toSerialize["Project"] = o.Project
	}
	if !IsNil(o.ReleaseBacklogItemsCount) {
		toSerialize["ReleaseBacklogItemsCount"] = o.ReleaseBacklogItemsCount
	}
	if !IsNil(o.ReleaseDate) {
		toSerialize["ReleaseDate"] = o.ReleaseDate
	}
	if !IsNil(o.ReleaseStartDate) {
		toSerialize["ReleaseStartDate"] = o.ReleaseStartDate
	}
	if !IsNil(o.RevisionHistory) {
		toSerialize["RevisionHistory"] = o.RevisionHistory
	}
	if !IsNil(o.State) {
		toSerialize["State"] = o.State
	}
	if !IsNil(o.Subscription) {
		toSerialize["Subscription"] = o.Subscription
	}
	if !IsNil(o.SyncedWithParent) {
		toSerialize["SyncedWithParent"] = o.SyncedWithParent
	}
	if !IsNil(o.TaskActualTotal) {
		toSerialize["TaskActualTotal"] = o.TaskActualTotal
	}
	if !IsNil(o.TaskEstimateTotal) {
		toSerialize["TaskEstimateTotal"] = o.TaskEstimateTotal
	}
	if !IsNil(o.TaskRemainingTotal) {
		toSerialize["TaskRemainingTotal"] = o.TaskRemainingTotal
	}
	if !IsNil(o.Theme) {
		toSerialize["Theme"] = o.Theme
	}
	if !IsNil(o.Version) {
		toSerialize["Version"] = o.Version
	}
	if !IsNil(o.VersionId) {
		toSerialize["VersionId"] = o.VersionId
	}
	if !IsNil(o.WorkProducts) {
		toSerialize["WorkProducts"] = o.WorkProducts
	}
	if !IsNil(o.Workspace) {
		toSerialize["Workspace"] = o.Workspace
	}
	if !IsNil(o.Warnings) {
		toSerialize["Warnings"] = o.Warnings
	}
	if !IsNil(o.Errors) {
		toSerialize["Errors"] = o.Errors
	}
	return toSerialize, nil
}

type NullableRelease struct {
	value *Release
	isSet bool
}

func (v NullableRelease) Get() *Release {
	return v.value
}

func (v *NullableRelease) Set(val *Release) {
	v.value = val
	v.isSet = true
}

func (v NullableRelease) IsSet() bool {
	return v.isSet
}

func (v *NullableRelease) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRelease(val *Release) *NullableRelease {
	return &NullableRelease{value: val, isSet: true}
}

func (v NullableRelease) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRelease) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


