/*
Rally WebService API

Rally Open API docs

API version: v2.0
Contact: support@rallydev.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the BuildDefinitionRead200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BuildDefinitionRead200Response{}

// BuildDefinitionRead200Response struct for BuildDefinitionRead200Response
type BuildDefinitionRead200Response struct {
	RallyAPIMajor   *string          `json:"_rallyAPIMajor,omitempty"`
	RallyAPIMinor   *string          `json:"_rallyAPIMinor,omitempty"`
	BuildDefinition *BuildDefinition `json:"BuildDefinition,omitempty"`
	Warnings        []string         `json:"Warnings,omitempty"`
	Errors          []string         `json:"Errors,omitempty"`
}

// NewBuildDefinitionRead200Response instantiates a new BuildDefinitionRead200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBuildDefinitionRead200Response() *BuildDefinitionRead200Response {
	this := BuildDefinitionRead200Response{}
	return &this
}

// NewBuildDefinitionRead200ResponseWithDefaults instantiates a new BuildDefinitionRead200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBuildDefinitionRead200ResponseWithDefaults() *BuildDefinitionRead200Response {
	this := BuildDefinitionRead200Response{}
	return &this
}

// GetRallyAPIMajor returns the RallyAPIMajor field value if set, zero value otherwise.
func (o *BuildDefinitionRead200Response) GetRallyAPIMajor() string {
	if o == nil || IsNil(o.RallyAPIMajor) {
		var ret string
		return ret
	}
	return *o.RallyAPIMajor
}

// GetRallyAPIMajorOk returns a tuple with the RallyAPIMajor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BuildDefinitionRead200Response) GetRallyAPIMajorOk() (*string, bool) {
	if o == nil || IsNil(o.RallyAPIMajor) {
		return nil, false
	}
	return o.RallyAPIMajor, true
}

// HasRallyAPIMajor returns a boolean if a field has been set.
func (o *BuildDefinitionRead200Response) HasRallyAPIMajor() bool {
	if o != nil && !IsNil(o.RallyAPIMajor) {
		return true
	}

	return false
}

// SetRallyAPIMajor gets a reference to the given string and assigns it to the RallyAPIMajor field.
func (o *BuildDefinitionRead200Response) SetRallyAPIMajor(v string) {
	o.RallyAPIMajor = &v
}

// GetRallyAPIMinor returns the RallyAPIMinor field value if set, zero value otherwise.
func (o *BuildDefinitionRead200Response) GetRallyAPIMinor() string {
	if o == nil || IsNil(o.RallyAPIMinor) {
		var ret string
		return ret
	}
	return *o.RallyAPIMinor
}

// GetRallyAPIMinorOk returns a tuple with the RallyAPIMinor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BuildDefinitionRead200Response) GetRallyAPIMinorOk() (*string, bool) {
	if o == nil || IsNil(o.RallyAPIMinor) {
		return nil, false
	}
	return o.RallyAPIMinor, true
}

// HasRallyAPIMinor returns a boolean if a field has been set.
func (o *BuildDefinitionRead200Response) HasRallyAPIMinor() bool {
	if o != nil && !IsNil(o.RallyAPIMinor) {
		return true
	}

	return false
}

// SetRallyAPIMinor gets a reference to the given string and assigns it to the RallyAPIMinor field.
func (o *BuildDefinitionRead200Response) SetRallyAPIMinor(v string) {
	o.RallyAPIMinor = &v
}

// GetBuildDefinition returns the BuildDefinition field value if set, zero value otherwise.
func (o *BuildDefinitionRead200Response) GetBuildDefinition() BuildDefinition {
	if o == nil || IsNil(o.BuildDefinition) {
		var ret BuildDefinition
		return ret
	}
	return *o.BuildDefinition
}

// GetBuildDefinitionOk returns a tuple with the BuildDefinition field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BuildDefinitionRead200Response) GetBuildDefinitionOk() (*BuildDefinition, bool) {
	if o == nil || IsNil(o.BuildDefinition) {
		return nil, false
	}
	return o.BuildDefinition, true
}

// HasBuildDefinition returns a boolean if a field has been set.
func (o *BuildDefinitionRead200Response) HasBuildDefinition() bool {
	if o != nil && !IsNil(o.BuildDefinition) {
		return true
	}

	return false
}

// SetBuildDefinition gets a reference to the given BuildDefinition and assigns it to the BuildDefinition field.
func (o *BuildDefinitionRead200Response) SetBuildDefinition(v BuildDefinition) {
	o.BuildDefinition = &v
}

// GetWarnings returns the Warnings field value if set, zero value otherwise.
func (o *BuildDefinitionRead200Response) GetWarnings() []string {
	if o == nil || IsNil(o.Warnings) {
		var ret []string
		return ret
	}
	return o.Warnings
}

// GetWarningsOk returns a tuple with the Warnings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BuildDefinitionRead200Response) GetWarningsOk() ([]string, bool) {
	if o == nil || IsNil(o.Warnings) {
		return nil, false
	}
	return o.Warnings, true
}

// HasWarnings returns a boolean if a field has been set.
func (o *BuildDefinitionRead200Response) HasWarnings() bool {
	if o != nil && !IsNil(o.Warnings) {
		return true
	}

	return false
}

// SetWarnings gets a reference to the given []string and assigns it to the Warnings field.
func (o *BuildDefinitionRead200Response) SetWarnings(v []string) {
	o.Warnings = v
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *BuildDefinitionRead200Response) GetErrors() []string {
	if o == nil || IsNil(o.Errors) {
		var ret []string
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BuildDefinitionRead200Response) GetErrorsOk() ([]string, bool) {
	if o == nil || IsNil(o.Errors) {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *BuildDefinitionRead200Response) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []string and assigns it to the Errors field.
func (o *BuildDefinitionRead200Response) SetErrors(v []string) {
	o.Errors = v
}

func (o BuildDefinitionRead200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BuildDefinitionRead200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.RallyAPIMajor) {
		toSerialize["_rallyAPIMajor"] = o.RallyAPIMajor
	}
	if !IsNil(o.RallyAPIMinor) {
		toSerialize["_rallyAPIMinor"] = o.RallyAPIMinor
	}
	if !IsNil(o.BuildDefinition) {
		toSerialize["BuildDefinition"] = o.BuildDefinition
	}
	if !IsNil(o.Warnings) {
		toSerialize["Warnings"] = o.Warnings
	}
	if !IsNil(o.Errors) {
		toSerialize["Errors"] = o.Errors
	}
	return toSerialize, nil
}

type NullableBuildDefinitionRead200Response struct {
	value *BuildDefinitionRead200Response
	isSet bool
}

func (v NullableBuildDefinitionRead200Response) Get() *BuildDefinitionRead200Response {
	return v.value
}

func (v *NullableBuildDefinitionRead200Response) Set(val *BuildDefinitionRead200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableBuildDefinitionRead200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableBuildDefinitionRead200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBuildDefinitionRead200Response(val *BuildDefinitionRead200Response) *NullableBuildDefinitionRead200Response {
	return &NullableBuildDefinitionRead200Response{value: val, isSet: true}
}

func (v NullableBuildDefinitionRead200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBuildDefinitionRead200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
