/*
Rally WebService API

Rally Open API docs

API version: v2.0
Contact: support@rallydev.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the MilestoneMutation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MilestoneMutation{}

// MilestoneMutation Milestone
type MilestoneMutation struct {
	Milestone *MilestoneMutationMilestone `json:"Milestone,omitempty"`
}

// NewMilestoneMutation instantiates a new MilestoneMutation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMilestoneMutation() *MilestoneMutation {
	this := MilestoneMutation{}
	return &this
}

// NewMilestoneMutationWithDefaults instantiates a new MilestoneMutation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMilestoneMutationWithDefaults() *MilestoneMutation {
	this := MilestoneMutation{}
	return &this
}

// GetMilestone returns the Milestone field value if set, zero value otherwise.
func (o *MilestoneMutation) GetMilestone() MilestoneMutationMilestone {
	if o == nil || IsNil(o.Milestone) {
		var ret MilestoneMutationMilestone
		return ret
	}
	return *o.Milestone
}

// GetMilestoneOk returns a tuple with the Milestone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MilestoneMutation) GetMilestoneOk() (*MilestoneMutationMilestone, bool) {
	if o == nil || IsNil(o.Milestone) {
		return nil, false
	}
	return o.Milestone, true
}

// HasMilestone returns a boolean if a field has been set.
func (o *MilestoneMutation) HasMilestone() bool {
	if o != nil && !IsNil(o.Milestone) {
		return true
	}

	return false
}

// SetMilestone gets a reference to the given MilestoneMutationMilestone and assigns it to the Milestone field.
func (o *MilestoneMutation) SetMilestone(v MilestoneMutationMilestone) {
	o.Milestone = &v
}

func (o MilestoneMutation) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MilestoneMutation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Milestone) {
		toSerialize["Milestone"] = o.Milestone
	}
	return toSerialize, nil
}

type NullableMilestoneMutation struct {
	value *MilestoneMutation
	isSet bool
}

func (v NullableMilestoneMutation) Get() *MilestoneMutation {
	return v.value
}

func (v *NullableMilestoneMutation) Set(val *MilestoneMutation) {
	v.value = val
	v.isSet = true
}

func (v NullableMilestoneMutation) IsSet() bool {
	return v.isSet
}

func (v *NullableMilestoneMutation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMilestoneMutation(val *MilestoneMutation) *NullableMilestoneMutation {
	return &NullableMilestoneMutation{value: val, isSet: true}
}

func (v NullableMilestoneMutation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMilestoneMutation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
