/*
Rally WebService API

Rally Open API docs

API version: v2.0
Contact: support@rallydev.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AllowedAttributeValueRef type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AllowedAttributeValueRef{}

// AllowedAttributeValueRef Reference to AllowedAttributeValue
type AllowedAttributeValueRef struct {
	Ref string `json:"_ref"`
}

type _AllowedAttributeValueRef AllowedAttributeValueRef

// NewAllowedAttributeValueRef instantiates a new AllowedAttributeValueRef object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAllowedAttributeValueRef(ref string) *AllowedAttributeValueRef {
	this := AllowedAttributeValueRef{}
	this.Ref = ref
	return &this
}

// NewAllowedAttributeValueRefWithDefaults instantiates a new AllowedAttributeValueRef object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAllowedAttributeValueRefWithDefaults() *AllowedAttributeValueRef {
	this := AllowedAttributeValueRef{}
	return &this
}

// GetRef returns the Ref field value
func (o *AllowedAttributeValueRef) GetRef() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Ref
}

// GetRefOk returns a tuple with the Ref field value
// and a boolean to check if the value has been set.
func (o *AllowedAttributeValueRef) GetRefOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ref, true
}

// SetRef sets field value
func (o *AllowedAttributeValueRef) SetRef(v string) {
	o.Ref = v
}

func (o AllowedAttributeValueRef) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AllowedAttributeValueRef) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["_ref"] = o.Ref
	return toSerialize, nil
}

func (o *AllowedAttributeValueRef) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"_ref",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAllowedAttributeValueRef := _AllowedAttributeValueRef{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	
	err = decoder.Decode(&varAllowedAttributeValueRef)

	if err != nil {
		return err
	}

	*o = AllowedAttributeValueRef(varAllowedAttributeValueRef)

	return err
}

type NullableAllowedAttributeValueRef struct {
	value *AllowedAttributeValueRef
	isSet bool
}

func (v NullableAllowedAttributeValueRef) Get() *AllowedAttributeValueRef {
	return v.value
}

func (v *NullableAllowedAttributeValueRef) Set(val *AllowedAttributeValueRef) {
	v.value = val
	v.isSet = true
}

func (v NullableAllowedAttributeValueRef) IsSet() bool {
	return v.isSet
}

func (v *NullableAllowedAttributeValueRef) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAllowedAttributeValueRef(val *AllowedAttributeValueRef) *NullableAllowedAttributeValueRef {
	return &NullableAllowedAttributeValueRef{value: val, isSet: true}
}

func (v NullableAllowedAttributeValueRef) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAllowedAttributeValueRef) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


