/*
Rally WebService API

Rally Open API docs

API version: v2.0
Contact: support@rallydev.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the VSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric{}

// VSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric VSMProductAnalyticsMetric
type VSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric struct {
	// Active
	Active *bool `json:"Active,omitempty"`
	// Category
	Category *string `json:"Category,omitempty"`
	// Description
	Description *string `json:"Description,omitempty"`
	Measures *Collection `json:"Measures,omitempty"`
	// Name
	Name *string `json:"Name,omitempty"`
	Outcomes *Collection `json:"Outcomes,omitempty"`
	PortfolioItems *Collection `json:"PortfolioItems,omitempty"`
	Product *VSMProductRef `json:"Product,omitempty"`
	// Source Id
	SourceId *string `json:"SourceId,omitempty"`
	// Source Key
	SourceKey *string `json:"SourceKey,omitempty"`
	// Source System Meta Data
	SourceSystemMetaData *string `json:"SourceSystemMetaData,omitempty"`
	// Source Url
	SourceUrl *string `json:"SourceUrl,omitempty"`
	Targets *Collection `json:"Targets,omitempty"`
	// Unit
	Unit *string `json:"Unit,omitempty"`
	Workspace *WorkspaceRef `json:"Workspace,omitempty"`
	Warnings []string `json:"Warnings,omitempty"`
	Errors []string `json:"Errors,omitempty"`
}

// NewVSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric instantiates a new VSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric() *VSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric {
	this := VSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric{}
	return &this
}

// NewVSMProductAnalyticsMetricMutationVSMProductAnalyticsMetricWithDefaults instantiates a new VSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVSMProductAnalyticsMetricMutationVSMProductAnalyticsMetricWithDefaults() *VSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric {
	this := VSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric{}
	return &this
}

// GetActive returns the Active field value if set, zero value otherwise.
func (o *VSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric) GetActive() bool {
	if o == nil || IsNil(o.Active) {
		var ret bool
		return ret
	}
	return *o.Active
}

// GetActiveOk returns a tuple with the Active field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric) GetActiveOk() (*bool, bool) {
	if o == nil || IsNil(o.Active) {
		return nil, false
	}
	return o.Active, true
}

// HasActive returns a boolean if a field has been set.
func (o *VSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric) HasActive() bool {
	if o != nil && !IsNil(o.Active) {
		return true
	}

	return false
}

// SetActive gets a reference to the given bool and assigns it to the Active field.
func (o *VSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric) SetActive(v bool) {
	o.Active = &v
}

// GetCategory returns the Category field value if set, zero value otherwise.
func (o *VSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric) GetCategory() string {
	if o == nil || IsNil(o.Category) {
		var ret string
		return ret
	}
	return *o.Category
}

// GetCategoryOk returns a tuple with the Category field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric) GetCategoryOk() (*string, bool) {
	if o == nil || IsNil(o.Category) {
		return nil, false
	}
	return o.Category, true
}

// HasCategory returns a boolean if a field has been set.
func (o *VSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric) HasCategory() bool {
	if o != nil && !IsNil(o.Category) {
		return true
	}

	return false
}

// SetCategory gets a reference to the given string and assigns it to the Category field.
func (o *VSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric) SetCategory(v string) {
	o.Category = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *VSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *VSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *VSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric) SetDescription(v string) {
	o.Description = &v
}

// GetMeasures returns the Measures field value if set, zero value otherwise.
func (o *VSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric) GetMeasures() Collection {
	if o == nil || IsNil(o.Measures) {
		var ret Collection
		return ret
	}
	return *o.Measures
}

// GetMeasuresOk returns a tuple with the Measures field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric) GetMeasuresOk() (*Collection, bool) {
	if o == nil || IsNil(o.Measures) {
		return nil, false
	}
	return o.Measures, true
}

// HasMeasures returns a boolean if a field has been set.
func (o *VSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric) HasMeasures() bool {
	if o != nil && !IsNil(o.Measures) {
		return true
	}

	return false
}

// SetMeasures gets a reference to the given Collection and assigns it to the Measures field.
func (o *VSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric) SetMeasures(v Collection) {
	o.Measures = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *VSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *VSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *VSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric) SetName(v string) {
	o.Name = &v
}

// GetOutcomes returns the Outcomes field value if set, zero value otherwise.
func (o *VSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric) GetOutcomes() Collection {
	if o == nil || IsNil(o.Outcomes) {
		var ret Collection
		return ret
	}
	return *o.Outcomes
}

// GetOutcomesOk returns a tuple with the Outcomes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric) GetOutcomesOk() (*Collection, bool) {
	if o == nil || IsNil(o.Outcomes) {
		return nil, false
	}
	return o.Outcomes, true
}

// HasOutcomes returns a boolean if a field has been set.
func (o *VSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric) HasOutcomes() bool {
	if o != nil && !IsNil(o.Outcomes) {
		return true
	}

	return false
}

// SetOutcomes gets a reference to the given Collection and assigns it to the Outcomes field.
func (o *VSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric) SetOutcomes(v Collection) {
	o.Outcomes = &v
}

// GetPortfolioItems returns the PortfolioItems field value if set, zero value otherwise.
func (o *VSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric) GetPortfolioItems() Collection {
	if o == nil || IsNil(o.PortfolioItems) {
		var ret Collection
		return ret
	}
	return *o.PortfolioItems
}

// GetPortfolioItemsOk returns a tuple with the PortfolioItems field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric) GetPortfolioItemsOk() (*Collection, bool) {
	if o == nil || IsNil(o.PortfolioItems) {
		return nil, false
	}
	return o.PortfolioItems, true
}

// HasPortfolioItems returns a boolean if a field has been set.
func (o *VSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric) HasPortfolioItems() bool {
	if o != nil && !IsNil(o.PortfolioItems) {
		return true
	}

	return false
}

// SetPortfolioItems gets a reference to the given Collection and assigns it to the PortfolioItems field.
func (o *VSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric) SetPortfolioItems(v Collection) {
	o.PortfolioItems = &v
}

// GetProduct returns the Product field value if set, zero value otherwise.
func (o *VSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric) GetProduct() VSMProductRef {
	if o == nil || IsNil(o.Product) {
		var ret VSMProductRef
		return ret
	}
	return *o.Product
}

// GetProductOk returns a tuple with the Product field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric) GetProductOk() (*VSMProductRef, bool) {
	if o == nil || IsNil(o.Product) {
		return nil, false
	}
	return o.Product, true
}

// HasProduct returns a boolean if a field has been set.
func (o *VSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric) HasProduct() bool {
	if o != nil && !IsNil(o.Product) {
		return true
	}

	return false
}

// SetProduct gets a reference to the given VSMProductRef and assigns it to the Product field.
func (o *VSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric) SetProduct(v VSMProductRef) {
	o.Product = &v
}

// GetSourceId returns the SourceId field value if set, zero value otherwise.
func (o *VSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric) GetSourceId() string {
	if o == nil || IsNil(o.SourceId) {
		var ret string
		return ret
	}
	return *o.SourceId
}

// GetSourceIdOk returns a tuple with the SourceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric) GetSourceIdOk() (*string, bool) {
	if o == nil || IsNil(o.SourceId) {
		return nil, false
	}
	return o.SourceId, true
}

// HasSourceId returns a boolean if a field has been set.
func (o *VSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric) HasSourceId() bool {
	if o != nil && !IsNil(o.SourceId) {
		return true
	}

	return false
}

// SetSourceId gets a reference to the given string and assigns it to the SourceId field.
func (o *VSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric) SetSourceId(v string) {
	o.SourceId = &v
}

// GetSourceKey returns the SourceKey field value if set, zero value otherwise.
func (o *VSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric) GetSourceKey() string {
	if o == nil || IsNil(o.SourceKey) {
		var ret string
		return ret
	}
	return *o.SourceKey
}

// GetSourceKeyOk returns a tuple with the SourceKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric) GetSourceKeyOk() (*string, bool) {
	if o == nil || IsNil(o.SourceKey) {
		return nil, false
	}
	return o.SourceKey, true
}

// HasSourceKey returns a boolean if a field has been set.
func (o *VSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric) HasSourceKey() bool {
	if o != nil && !IsNil(o.SourceKey) {
		return true
	}

	return false
}

// SetSourceKey gets a reference to the given string and assigns it to the SourceKey field.
func (o *VSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric) SetSourceKey(v string) {
	o.SourceKey = &v
}

// GetSourceSystemMetaData returns the SourceSystemMetaData field value if set, zero value otherwise.
func (o *VSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric) GetSourceSystemMetaData() string {
	if o == nil || IsNil(o.SourceSystemMetaData) {
		var ret string
		return ret
	}
	return *o.SourceSystemMetaData
}

// GetSourceSystemMetaDataOk returns a tuple with the SourceSystemMetaData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric) GetSourceSystemMetaDataOk() (*string, bool) {
	if o == nil || IsNil(o.SourceSystemMetaData) {
		return nil, false
	}
	return o.SourceSystemMetaData, true
}

// HasSourceSystemMetaData returns a boolean if a field has been set.
func (o *VSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric) HasSourceSystemMetaData() bool {
	if o != nil && !IsNil(o.SourceSystemMetaData) {
		return true
	}

	return false
}

// SetSourceSystemMetaData gets a reference to the given string and assigns it to the SourceSystemMetaData field.
func (o *VSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric) SetSourceSystemMetaData(v string) {
	o.SourceSystemMetaData = &v
}

// GetSourceUrl returns the SourceUrl field value if set, zero value otherwise.
func (o *VSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric) GetSourceUrl() string {
	if o == nil || IsNil(o.SourceUrl) {
		var ret string
		return ret
	}
	return *o.SourceUrl
}

// GetSourceUrlOk returns a tuple with the SourceUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric) GetSourceUrlOk() (*string, bool) {
	if o == nil || IsNil(o.SourceUrl) {
		return nil, false
	}
	return o.SourceUrl, true
}

// HasSourceUrl returns a boolean if a field has been set.
func (o *VSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric) HasSourceUrl() bool {
	if o != nil && !IsNil(o.SourceUrl) {
		return true
	}

	return false
}

// SetSourceUrl gets a reference to the given string and assigns it to the SourceUrl field.
func (o *VSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric) SetSourceUrl(v string) {
	o.SourceUrl = &v
}

// GetTargets returns the Targets field value if set, zero value otherwise.
func (o *VSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric) GetTargets() Collection {
	if o == nil || IsNil(o.Targets) {
		var ret Collection
		return ret
	}
	return *o.Targets
}

// GetTargetsOk returns a tuple with the Targets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric) GetTargetsOk() (*Collection, bool) {
	if o == nil || IsNil(o.Targets) {
		return nil, false
	}
	return o.Targets, true
}

// HasTargets returns a boolean if a field has been set.
func (o *VSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric) HasTargets() bool {
	if o != nil && !IsNil(o.Targets) {
		return true
	}

	return false
}

// SetTargets gets a reference to the given Collection and assigns it to the Targets field.
func (o *VSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric) SetTargets(v Collection) {
	o.Targets = &v
}

// GetUnit returns the Unit field value if set, zero value otherwise.
func (o *VSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric) GetUnit() string {
	if o == nil || IsNil(o.Unit) {
		var ret string
		return ret
	}
	return *o.Unit
}

// GetUnitOk returns a tuple with the Unit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric) GetUnitOk() (*string, bool) {
	if o == nil || IsNil(o.Unit) {
		return nil, false
	}
	return o.Unit, true
}

// HasUnit returns a boolean if a field has been set.
func (o *VSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric) HasUnit() bool {
	if o != nil && !IsNil(o.Unit) {
		return true
	}

	return false
}

// SetUnit gets a reference to the given string and assigns it to the Unit field.
func (o *VSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric) SetUnit(v string) {
	o.Unit = &v
}

// GetWorkspace returns the Workspace field value if set, zero value otherwise.
func (o *VSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric) GetWorkspace() WorkspaceRef {
	if o == nil || IsNil(o.Workspace) {
		var ret WorkspaceRef
		return ret
	}
	return *o.Workspace
}

// GetWorkspaceOk returns a tuple with the Workspace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric) GetWorkspaceOk() (*WorkspaceRef, bool) {
	if o == nil || IsNil(o.Workspace) {
		return nil, false
	}
	return o.Workspace, true
}

// HasWorkspace returns a boolean if a field has been set.
func (o *VSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric) HasWorkspace() bool {
	if o != nil && !IsNil(o.Workspace) {
		return true
	}

	return false
}

// SetWorkspace gets a reference to the given WorkspaceRef and assigns it to the Workspace field.
func (o *VSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric) SetWorkspace(v WorkspaceRef) {
	o.Workspace = &v
}

// GetWarnings returns the Warnings field value if set, zero value otherwise.
func (o *VSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric) GetWarnings() []string {
	if o == nil || IsNil(o.Warnings) {
		var ret []string
		return ret
	}
	return o.Warnings
}

// GetWarningsOk returns a tuple with the Warnings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric) GetWarningsOk() ([]string, bool) {
	if o == nil || IsNil(o.Warnings) {
		return nil, false
	}
	return o.Warnings, true
}

// HasWarnings returns a boolean if a field has been set.
func (o *VSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric) HasWarnings() bool {
	if o != nil && !IsNil(o.Warnings) {
		return true
	}

	return false
}

// SetWarnings gets a reference to the given []string and assigns it to the Warnings field.
func (o *VSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric) SetWarnings(v []string) {
	o.Warnings = v
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *VSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric) GetErrors() []string {
	if o == nil || IsNil(o.Errors) {
		var ret []string
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric) GetErrorsOk() ([]string, bool) {
	if o == nil || IsNil(o.Errors) {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *VSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []string and assigns it to the Errors field.
func (o *VSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric) SetErrors(v []string) {
	o.Errors = v
}

func (o VSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Active) {
		toSerialize["Active"] = o.Active
	}
	if !IsNil(o.Category) {
		toSerialize["Category"] = o.Category
	}
	if !IsNil(o.Description) {
		toSerialize["Description"] = o.Description
	}
	if !IsNil(o.Measures) {
		toSerialize["Measures"] = o.Measures
	}
	if !IsNil(o.Name) {
		toSerialize["Name"] = o.Name
	}
	if !IsNil(o.Outcomes) {
		toSerialize["Outcomes"] = o.Outcomes
	}
	if !IsNil(o.PortfolioItems) {
		toSerialize["PortfolioItems"] = o.PortfolioItems
	}
	if !IsNil(o.Product) {
		toSerialize["Product"] = o.Product
	}
	if !IsNil(o.SourceId) {
		toSerialize["SourceId"] = o.SourceId
	}
	if !IsNil(o.SourceKey) {
		toSerialize["SourceKey"] = o.SourceKey
	}
	if !IsNil(o.SourceSystemMetaData) {
		toSerialize["SourceSystemMetaData"] = o.SourceSystemMetaData
	}
	if !IsNil(o.SourceUrl) {
		toSerialize["SourceUrl"] = o.SourceUrl
	}
	if !IsNil(o.Targets) {
		toSerialize["Targets"] = o.Targets
	}
	if !IsNil(o.Unit) {
		toSerialize["Unit"] = o.Unit
	}
	if !IsNil(o.Workspace) {
		toSerialize["Workspace"] = o.Workspace
	}
	if !IsNil(o.Warnings) {
		toSerialize["Warnings"] = o.Warnings
	}
	if !IsNil(o.Errors) {
		toSerialize["Errors"] = o.Errors
	}
	return toSerialize, nil
}

type NullableVSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric struct {
	value *VSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric
	isSet bool
}

func (v NullableVSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric) Get() *VSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric {
	return v.value
}

func (v *NullableVSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric) Set(val *VSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric) {
	v.value = val
	v.isSet = true
}

func (v NullableVSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric) IsSet() bool {
	return v.isSet
}

func (v *NullableVSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric(val *VSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric) *NullableVSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric {
	return &NullableVSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric{value: val, isSet: true}
}

func (v NullableVSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVSMProductAnalyticsMetricMutationVSMProductAnalyticsMetric) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


