/*
Rally WebService API

Rally Open API docs

API version: v2.0
Contact: support@rallydev.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the FlowStateMutation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FlowStateMutation{}

// FlowStateMutation FlowState
type FlowStateMutation struct {
	FlowState *FlowStateMutationFlowState `json:"FlowState,omitempty"`
}

// NewFlowStateMutation instantiates a new FlowStateMutation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFlowStateMutation() *FlowStateMutation {
	this := FlowStateMutation{}
	return &this
}

// NewFlowStateMutationWithDefaults instantiates a new FlowStateMutation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFlowStateMutationWithDefaults() *FlowStateMutation {
	this := FlowStateMutation{}
	return &this
}

// GetFlowState returns the FlowState field value if set, zero value otherwise.
func (o *FlowStateMutation) GetFlowState() FlowStateMutationFlowState {
	if o == nil || IsNil(o.FlowState) {
		var ret FlowStateMutationFlowState
		return ret
	}
	return *o.FlowState
}

// GetFlowStateOk returns a tuple with the FlowState field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FlowStateMutation) GetFlowStateOk() (*FlowStateMutationFlowState, bool) {
	if o == nil || IsNil(o.FlowState) {
		return nil, false
	}
	return o.FlowState, true
}

// HasFlowState returns a boolean if a field has been set.
func (o *FlowStateMutation) HasFlowState() bool {
	if o != nil && !IsNil(o.FlowState) {
		return true
	}

	return false
}

// SetFlowState gets a reference to the given FlowStateMutationFlowState and assigns it to the FlowState field.
func (o *FlowStateMutation) SetFlowState(v FlowStateMutationFlowState) {
	o.FlowState = &v
}

func (o FlowStateMutation) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FlowStateMutation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.FlowState) {
		toSerialize["FlowState"] = o.FlowState
	}
	return toSerialize, nil
}

type NullableFlowStateMutation struct {
	value *FlowStateMutation
	isSet bool
}

func (v NullableFlowStateMutation) Get() *FlowStateMutation {
	return v.value
}

func (v *NullableFlowStateMutation) Set(val *FlowStateMutation) {
	v.value = val
	v.isSet = true
}

func (v NullableFlowStateMutation) IsSet() bool {
	return v.isSet
}

func (v *NullableFlowStateMutation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFlowStateMutation(val *FlowStateMutation) *NullableFlowStateMutation {
	return &NullableFlowStateMutation{value: val, isSet: true}
}

func (v NullableFlowStateMutation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFlowStateMutation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


