/*
Rally WebService API

Rally Open API docs

API version: v2.0
Contact: support@rallydev.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the User type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &User{}

// User User
type User struct {
	// Account Locked Until
	AccountLockedUntil *string `json:"AccountLockedUntil,omitempty"`
	ArtifactsCreated *Collection `json:"ArtifactsCreated,omitempty"`
	ArtifactsOwned *Collection `json:"ArtifactsOwned,omitempty"`
	// Cost Center
	CostCenter *string `json:"CostCenter,omitempty"`
	// Creation Date
	CreationDate *string `json:"CreationDate,omitempty"`
	// Date Format
	DateFormat *string `json:"DateFormat,omitempty"`
	// Date Time Format
	DateTimeFormat *string `json:"DateTimeFormat,omitempty"`
	// Default Detail Page To Viewing Mode
	DefaultDetailPageToViewingMode *bool `json:"DefaultDetailPageToViewingMode,omitempty"`
	DefaultProject *ProjectRef `json:"DefaultProject,omitempty"`
	// Deleted
	Deleted *bool `json:"Deleted,omitempty"`
	// Department
	Department *string `json:"Department,omitempty"`
	// Disabled
	Disabled *bool `json:"Disabled,omitempty"`
	// Display Name
	DisplayName *string `json:"DisplayName,omitempty"`
	// Email Address
	EmailAddress *string `json:"EmailAddress,omitempty"`
	// Email Notification Enabled
	EmailNotificationEnabled *bool `json:"EmailNotificationEnabled,omitempty"`
	// First Name
	FirstName *string `json:"FirstName,omitempty"`
	// Investment Admin
	InvestmentAdmin *bool `json:"InvestmentAdmin,omitempty"`
	// Is Provisioning User
	IsProvisioningUser *bool `json:"IsProvisioningUser,omitempty"`
	// Is SLM Admin
	IsSLMAdmin *bool `json:"IsSLMAdmin,omitempty"`
	// Landing Page
	LandingPage *string `json:"LandingPage,omitempty"`
	// Language
	Language *string `json:"Language,omitempty"`
	// Last Active Date
	LastActiveDate *string `json:"LastActiveDate,omitempty"`
	// Last Login Date
	LastLoginDate *string `json:"LastLoginDate,omitempty"`
	// Last Name
	LastName *string `json:"LastName,omitempty"`
	// Last Password Update Date
	LastPasswordUpdateDate *string `json:"LastPasswordUpdateDate,omitempty"`
	// Last System Time Zone Name
	LastSystemTimeZoneName *string `json:"LastSystemTimeZoneName,omitempty"`
	// Ldap Uuid
	LdapUuid *string `json:"LdapUuid,omitempty"`
	// Locale
	Locale *string `json:"Locale,omitempty"`
	// Middle Name
	MiddleName *string `json:"MiddleName,omitempty"`
	// Network ID
	NetworkID *string `json:"NetworkID,omitempty"`
	// Object ID
	ObjectID *int64 `json:"ObjectID,omitempty"`
	// ObjectUUID
	ObjectUUID *string `json:"ObjectUUID,omitempty"`
	// Office Location
	OfficeLocation *string `json:"OfficeLocation,omitempty"`
	// Okr Admin
	OkrAdmin *bool `json:"OkrAdmin,omitempty"`
	// Onprem Ldap Username
	OnpremLdapUsername *string `json:"OnpremLdapUsername,omitempty"`
	// Password Expires
	PasswordExpires *int64 `json:"PasswordExpires,omitempty"`
	// Phone
	Phone *string `json:"Phone,omitempty"`
	// Planner
	Planner *bool `json:"Planner,omitempty"`
	ProfileImage *ProfileImageRef `json:"ProfileImage,omitempty"`
	// Project Scope Down
	ProjectScopeDown *bool `json:"ProjectScopeDown,omitempty"`
	// Project Scope Up
	ProjectScopeUp *bool `json:"ProjectScopeUp,omitempty"`
	RevisionHistory *RevisionHistoryRef `json:"RevisionHistory,omitempty"`
	// Role
	Role *string `json:"Role,omitempty"`
	// Session Timeout Warning
	SessionTimeoutWarning *bool `json:"SessionTimeoutWarning,omitempty"`
	// Short Display Name
	ShortDisplayName *string `json:"ShortDisplayName,omitempty"`
	Subscription *SubscriptionRef `json:"Subscription,omitempty"`
	// Subscription Admin
	SubscriptionAdmin *bool `json:"SubscriptionAdmin,omitempty"`
	// Subscription ID
	SubscriptionID *int64 `json:"SubscriptionID,omitempty"`
	// Subscription Permission
	SubscriptionPermission *string `json:"SubscriptionPermission,omitempty"`
	TeamMemberships *Collection `json:"TeamMemberships,omitempty"`
	// Timebox Admin
	TimeboxAdmin *bool `json:"TimeboxAdmin,omitempty"`
	// User Name
	UserName *string `json:"UserName,omitempty"`
	UserPermissions *Collection `json:"UserPermissions,omitempty"`
	UserProfile *UserProfileRef `json:"UserProfile,omitempty"`
	// VersionId
	VersionId *string `json:"VersionId,omitempty"`
	// Vsi Admin
	VsiAdmin *bool `json:"VsiAdmin,omitempty"`
	// Workspace Permission
	WorkspacePermission *string `json:"WorkspacePermission,omitempty"`
	// Zuul ID
	ZuulID *string `json:"ZuulID,omitempty"`
	// Business Unit
	CBusinessUnit *string `json:"c_BusinessUnit,omitempty"`
	// session Timeout
	SessionTimeout *int64 `json:"sessionTimeout,omitempty"`
	// subscriptionOid
	SubscriptionOid *int64 `json:"subscriptionOid,omitempty"`
	Warnings []string `json:"Warnings,omitempty"`
	Errors []string `json:"Errors,omitempty"`
}

// NewUser instantiates a new User object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUser() *User {
	this := User{}
	var costCenter string = "None"
	this.CostCenter = &costCenter
	var department string = "None"
	this.Department = &department
	var officeLocation string = "None"
	this.OfficeLocation = &officeLocation
	var role string = "None"
	this.Role = &role
	return &this
}

// NewUserWithDefaults instantiates a new User object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserWithDefaults() *User {
	this := User{}
	var costCenter string = "None"
	this.CostCenter = &costCenter
	var department string = "None"
	this.Department = &department
	var officeLocation string = "None"
	this.OfficeLocation = &officeLocation
	var role string = "None"
	this.Role = &role
	return &this
}

// GetAccountLockedUntil returns the AccountLockedUntil field value if set, zero value otherwise.
func (o *User) GetAccountLockedUntil() string {
	if o == nil || IsNil(o.AccountLockedUntil) {
		var ret string
		return ret
	}
	return *o.AccountLockedUntil
}

// GetAccountLockedUntilOk returns a tuple with the AccountLockedUntil field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetAccountLockedUntilOk() (*string, bool) {
	if o == nil || IsNil(o.AccountLockedUntil) {
		return nil, false
	}
	return o.AccountLockedUntil, true
}

// HasAccountLockedUntil returns a boolean if a field has been set.
func (o *User) HasAccountLockedUntil() bool {
	if o != nil && !IsNil(o.AccountLockedUntil) {
		return true
	}

	return false
}

// SetAccountLockedUntil gets a reference to the given string and assigns it to the AccountLockedUntil field.
func (o *User) SetAccountLockedUntil(v string) {
	o.AccountLockedUntil = &v
}

// GetArtifactsCreated returns the ArtifactsCreated field value if set, zero value otherwise.
func (o *User) GetArtifactsCreated() Collection {
	if o == nil || IsNil(o.ArtifactsCreated) {
		var ret Collection
		return ret
	}
	return *o.ArtifactsCreated
}

// GetArtifactsCreatedOk returns a tuple with the ArtifactsCreated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetArtifactsCreatedOk() (*Collection, bool) {
	if o == nil || IsNil(o.ArtifactsCreated) {
		return nil, false
	}
	return o.ArtifactsCreated, true
}

// HasArtifactsCreated returns a boolean if a field has been set.
func (o *User) HasArtifactsCreated() bool {
	if o != nil && !IsNil(o.ArtifactsCreated) {
		return true
	}

	return false
}

// SetArtifactsCreated gets a reference to the given Collection and assigns it to the ArtifactsCreated field.
func (o *User) SetArtifactsCreated(v Collection) {
	o.ArtifactsCreated = &v
}

// GetArtifactsOwned returns the ArtifactsOwned field value if set, zero value otherwise.
func (o *User) GetArtifactsOwned() Collection {
	if o == nil || IsNil(o.ArtifactsOwned) {
		var ret Collection
		return ret
	}
	return *o.ArtifactsOwned
}

// GetArtifactsOwnedOk returns a tuple with the ArtifactsOwned field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetArtifactsOwnedOk() (*Collection, bool) {
	if o == nil || IsNil(o.ArtifactsOwned) {
		return nil, false
	}
	return o.ArtifactsOwned, true
}

// HasArtifactsOwned returns a boolean if a field has been set.
func (o *User) HasArtifactsOwned() bool {
	if o != nil && !IsNil(o.ArtifactsOwned) {
		return true
	}

	return false
}

// SetArtifactsOwned gets a reference to the given Collection and assigns it to the ArtifactsOwned field.
func (o *User) SetArtifactsOwned(v Collection) {
	o.ArtifactsOwned = &v
}

// GetCostCenter returns the CostCenter field value if set, zero value otherwise.
func (o *User) GetCostCenter() string {
	if o == nil || IsNil(o.CostCenter) {
		var ret string
		return ret
	}
	return *o.CostCenter
}

// GetCostCenterOk returns a tuple with the CostCenter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetCostCenterOk() (*string, bool) {
	if o == nil || IsNil(o.CostCenter) {
		return nil, false
	}
	return o.CostCenter, true
}

// HasCostCenter returns a boolean if a field has been set.
func (o *User) HasCostCenter() bool {
	if o != nil && !IsNil(o.CostCenter) {
		return true
	}

	return false
}

// SetCostCenter gets a reference to the given string and assigns it to the CostCenter field.
func (o *User) SetCostCenter(v string) {
	o.CostCenter = &v
}

// GetCreationDate returns the CreationDate field value if set, zero value otherwise.
func (o *User) GetCreationDate() string {
	if o == nil || IsNil(o.CreationDate) {
		var ret string
		return ret
	}
	return *o.CreationDate
}

// GetCreationDateOk returns a tuple with the CreationDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetCreationDateOk() (*string, bool) {
	if o == nil || IsNil(o.CreationDate) {
		return nil, false
	}
	return o.CreationDate, true
}

// HasCreationDate returns a boolean if a field has been set.
func (o *User) HasCreationDate() bool {
	if o != nil && !IsNil(o.CreationDate) {
		return true
	}

	return false
}

// SetCreationDate gets a reference to the given string and assigns it to the CreationDate field.
func (o *User) SetCreationDate(v string) {
	o.CreationDate = &v
}

// GetDateFormat returns the DateFormat field value if set, zero value otherwise.
func (o *User) GetDateFormat() string {
	if o == nil || IsNil(o.DateFormat) {
		var ret string
		return ret
	}
	return *o.DateFormat
}

// GetDateFormatOk returns a tuple with the DateFormat field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetDateFormatOk() (*string, bool) {
	if o == nil || IsNil(o.DateFormat) {
		return nil, false
	}
	return o.DateFormat, true
}

// HasDateFormat returns a boolean if a field has been set.
func (o *User) HasDateFormat() bool {
	if o != nil && !IsNil(o.DateFormat) {
		return true
	}

	return false
}

// SetDateFormat gets a reference to the given string and assigns it to the DateFormat field.
func (o *User) SetDateFormat(v string) {
	o.DateFormat = &v
}

// GetDateTimeFormat returns the DateTimeFormat field value if set, zero value otherwise.
func (o *User) GetDateTimeFormat() string {
	if o == nil || IsNil(o.DateTimeFormat) {
		var ret string
		return ret
	}
	return *o.DateTimeFormat
}

// GetDateTimeFormatOk returns a tuple with the DateTimeFormat field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetDateTimeFormatOk() (*string, bool) {
	if o == nil || IsNil(o.DateTimeFormat) {
		return nil, false
	}
	return o.DateTimeFormat, true
}

// HasDateTimeFormat returns a boolean if a field has been set.
func (o *User) HasDateTimeFormat() bool {
	if o != nil && !IsNil(o.DateTimeFormat) {
		return true
	}

	return false
}

// SetDateTimeFormat gets a reference to the given string and assigns it to the DateTimeFormat field.
func (o *User) SetDateTimeFormat(v string) {
	o.DateTimeFormat = &v
}

// GetDefaultDetailPageToViewingMode returns the DefaultDetailPageToViewingMode field value if set, zero value otherwise.
func (o *User) GetDefaultDetailPageToViewingMode() bool {
	if o == nil || IsNil(o.DefaultDetailPageToViewingMode) {
		var ret bool
		return ret
	}
	return *o.DefaultDetailPageToViewingMode
}

// GetDefaultDetailPageToViewingModeOk returns a tuple with the DefaultDetailPageToViewingMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetDefaultDetailPageToViewingModeOk() (*bool, bool) {
	if o == nil || IsNil(o.DefaultDetailPageToViewingMode) {
		return nil, false
	}
	return o.DefaultDetailPageToViewingMode, true
}

// HasDefaultDetailPageToViewingMode returns a boolean if a field has been set.
func (o *User) HasDefaultDetailPageToViewingMode() bool {
	if o != nil && !IsNil(o.DefaultDetailPageToViewingMode) {
		return true
	}

	return false
}

// SetDefaultDetailPageToViewingMode gets a reference to the given bool and assigns it to the DefaultDetailPageToViewingMode field.
func (o *User) SetDefaultDetailPageToViewingMode(v bool) {
	o.DefaultDetailPageToViewingMode = &v
}

// GetDefaultProject returns the DefaultProject field value if set, zero value otherwise.
func (o *User) GetDefaultProject() ProjectRef {
	if o == nil || IsNil(o.DefaultProject) {
		var ret ProjectRef
		return ret
	}
	return *o.DefaultProject
}

// GetDefaultProjectOk returns a tuple with the DefaultProject field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetDefaultProjectOk() (*ProjectRef, bool) {
	if o == nil || IsNil(o.DefaultProject) {
		return nil, false
	}
	return o.DefaultProject, true
}

// HasDefaultProject returns a boolean if a field has been set.
func (o *User) HasDefaultProject() bool {
	if o != nil && !IsNil(o.DefaultProject) {
		return true
	}

	return false
}

// SetDefaultProject gets a reference to the given ProjectRef and assigns it to the DefaultProject field.
func (o *User) SetDefaultProject(v ProjectRef) {
	o.DefaultProject = &v
}

// GetDeleted returns the Deleted field value if set, zero value otherwise.
func (o *User) GetDeleted() bool {
	if o == nil || IsNil(o.Deleted) {
		var ret bool
		return ret
	}
	return *o.Deleted
}

// GetDeletedOk returns a tuple with the Deleted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetDeletedOk() (*bool, bool) {
	if o == nil || IsNil(o.Deleted) {
		return nil, false
	}
	return o.Deleted, true
}

// HasDeleted returns a boolean if a field has been set.
func (o *User) HasDeleted() bool {
	if o != nil && !IsNil(o.Deleted) {
		return true
	}

	return false
}

// SetDeleted gets a reference to the given bool and assigns it to the Deleted field.
func (o *User) SetDeleted(v bool) {
	o.Deleted = &v
}

// GetDepartment returns the Department field value if set, zero value otherwise.
func (o *User) GetDepartment() string {
	if o == nil || IsNil(o.Department) {
		var ret string
		return ret
	}
	return *o.Department
}

// GetDepartmentOk returns a tuple with the Department field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetDepartmentOk() (*string, bool) {
	if o == nil || IsNil(o.Department) {
		return nil, false
	}
	return o.Department, true
}

// HasDepartment returns a boolean if a field has been set.
func (o *User) HasDepartment() bool {
	if o != nil && !IsNil(o.Department) {
		return true
	}

	return false
}

// SetDepartment gets a reference to the given string and assigns it to the Department field.
func (o *User) SetDepartment(v string) {
	o.Department = &v
}

// GetDisabled returns the Disabled field value if set, zero value otherwise.
func (o *User) GetDisabled() bool {
	if o == nil || IsNil(o.Disabled) {
		var ret bool
		return ret
	}
	return *o.Disabled
}

// GetDisabledOk returns a tuple with the Disabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetDisabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Disabled) {
		return nil, false
	}
	return o.Disabled, true
}

// HasDisabled returns a boolean if a field has been set.
func (o *User) HasDisabled() bool {
	if o != nil && !IsNil(o.Disabled) {
		return true
	}

	return false
}

// SetDisabled gets a reference to the given bool and assigns it to the Disabled field.
func (o *User) SetDisabled(v bool) {
	o.Disabled = &v
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise.
func (o *User) GetDisplayName() string {
	if o == nil || IsNil(o.DisplayName) {
		var ret string
		return ret
	}
	return *o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetDisplayNameOk() (*string, bool) {
	if o == nil || IsNil(o.DisplayName) {
		return nil, false
	}
	return o.DisplayName, true
}

// HasDisplayName returns a boolean if a field has been set.
func (o *User) HasDisplayName() bool {
	if o != nil && !IsNil(o.DisplayName) {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given string and assigns it to the DisplayName field.
func (o *User) SetDisplayName(v string) {
	o.DisplayName = &v
}

// GetEmailAddress returns the EmailAddress field value if set, zero value otherwise.
func (o *User) GetEmailAddress() string {
	if o == nil || IsNil(o.EmailAddress) {
		var ret string
		return ret
	}
	return *o.EmailAddress
}

// GetEmailAddressOk returns a tuple with the EmailAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetEmailAddressOk() (*string, bool) {
	if o == nil || IsNil(o.EmailAddress) {
		return nil, false
	}
	return o.EmailAddress, true
}

// HasEmailAddress returns a boolean if a field has been set.
func (o *User) HasEmailAddress() bool {
	if o != nil && !IsNil(o.EmailAddress) {
		return true
	}

	return false
}

// SetEmailAddress gets a reference to the given string and assigns it to the EmailAddress field.
func (o *User) SetEmailAddress(v string) {
	o.EmailAddress = &v
}

// GetEmailNotificationEnabled returns the EmailNotificationEnabled field value if set, zero value otherwise.
func (o *User) GetEmailNotificationEnabled() bool {
	if o == nil || IsNil(o.EmailNotificationEnabled) {
		var ret bool
		return ret
	}
	return *o.EmailNotificationEnabled
}

// GetEmailNotificationEnabledOk returns a tuple with the EmailNotificationEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetEmailNotificationEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.EmailNotificationEnabled) {
		return nil, false
	}
	return o.EmailNotificationEnabled, true
}

// HasEmailNotificationEnabled returns a boolean if a field has been set.
func (o *User) HasEmailNotificationEnabled() bool {
	if o != nil && !IsNil(o.EmailNotificationEnabled) {
		return true
	}

	return false
}

// SetEmailNotificationEnabled gets a reference to the given bool and assigns it to the EmailNotificationEnabled field.
func (o *User) SetEmailNotificationEnabled(v bool) {
	o.EmailNotificationEnabled = &v
}

// GetFirstName returns the FirstName field value if set, zero value otherwise.
func (o *User) GetFirstName() string {
	if o == nil || IsNil(o.FirstName) {
		var ret string
		return ret
	}
	return *o.FirstName
}

// GetFirstNameOk returns a tuple with the FirstName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetFirstNameOk() (*string, bool) {
	if o == nil || IsNil(o.FirstName) {
		return nil, false
	}
	return o.FirstName, true
}

// HasFirstName returns a boolean if a field has been set.
func (o *User) HasFirstName() bool {
	if o != nil && !IsNil(o.FirstName) {
		return true
	}

	return false
}

// SetFirstName gets a reference to the given string and assigns it to the FirstName field.
func (o *User) SetFirstName(v string) {
	o.FirstName = &v
}

// GetInvestmentAdmin returns the InvestmentAdmin field value if set, zero value otherwise.
func (o *User) GetInvestmentAdmin() bool {
	if o == nil || IsNil(o.InvestmentAdmin) {
		var ret bool
		return ret
	}
	return *o.InvestmentAdmin
}

// GetInvestmentAdminOk returns a tuple with the InvestmentAdmin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetInvestmentAdminOk() (*bool, bool) {
	if o == nil || IsNil(o.InvestmentAdmin) {
		return nil, false
	}
	return o.InvestmentAdmin, true
}

// HasInvestmentAdmin returns a boolean if a field has been set.
func (o *User) HasInvestmentAdmin() bool {
	if o != nil && !IsNil(o.InvestmentAdmin) {
		return true
	}

	return false
}

// SetInvestmentAdmin gets a reference to the given bool and assigns it to the InvestmentAdmin field.
func (o *User) SetInvestmentAdmin(v bool) {
	o.InvestmentAdmin = &v
}

// GetIsProvisioningUser returns the IsProvisioningUser field value if set, zero value otherwise.
func (o *User) GetIsProvisioningUser() bool {
	if o == nil || IsNil(o.IsProvisioningUser) {
		var ret bool
		return ret
	}
	return *o.IsProvisioningUser
}

// GetIsProvisioningUserOk returns a tuple with the IsProvisioningUser field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetIsProvisioningUserOk() (*bool, bool) {
	if o == nil || IsNil(o.IsProvisioningUser) {
		return nil, false
	}
	return o.IsProvisioningUser, true
}

// HasIsProvisioningUser returns a boolean if a field has been set.
func (o *User) HasIsProvisioningUser() bool {
	if o != nil && !IsNil(o.IsProvisioningUser) {
		return true
	}

	return false
}

// SetIsProvisioningUser gets a reference to the given bool and assigns it to the IsProvisioningUser field.
func (o *User) SetIsProvisioningUser(v bool) {
	o.IsProvisioningUser = &v
}

// GetIsSLMAdmin returns the IsSLMAdmin field value if set, zero value otherwise.
func (o *User) GetIsSLMAdmin() bool {
	if o == nil || IsNil(o.IsSLMAdmin) {
		var ret bool
		return ret
	}
	return *o.IsSLMAdmin
}

// GetIsSLMAdminOk returns a tuple with the IsSLMAdmin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetIsSLMAdminOk() (*bool, bool) {
	if o == nil || IsNil(o.IsSLMAdmin) {
		return nil, false
	}
	return o.IsSLMAdmin, true
}

// HasIsSLMAdmin returns a boolean if a field has been set.
func (o *User) HasIsSLMAdmin() bool {
	if o != nil && !IsNil(o.IsSLMAdmin) {
		return true
	}

	return false
}

// SetIsSLMAdmin gets a reference to the given bool and assigns it to the IsSLMAdmin field.
func (o *User) SetIsSLMAdmin(v bool) {
	o.IsSLMAdmin = &v
}

// GetLandingPage returns the LandingPage field value if set, zero value otherwise.
func (o *User) GetLandingPage() string {
	if o == nil || IsNil(o.LandingPage) {
		var ret string
		return ret
	}
	return *o.LandingPage
}

// GetLandingPageOk returns a tuple with the LandingPage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetLandingPageOk() (*string, bool) {
	if o == nil || IsNil(o.LandingPage) {
		return nil, false
	}
	return o.LandingPage, true
}

// HasLandingPage returns a boolean if a field has been set.
func (o *User) HasLandingPage() bool {
	if o != nil && !IsNil(o.LandingPage) {
		return true
	}

	return false
}

// SetLandingPage gets a reference to the given string and assigns it to the LandingPage field.
func (o *User) SetLandingPage(v string) {
	o.LandingPage = &v
}

// GetLanguage returns the Language field value if set, zero value otherwise.
func (o *User) GetLanguage() string {
	if o == nil || IsNil(o.Language) {
		var ret string
		return ret
	}
	return *o.Language
}

// GetLanguageOk returns a tuple with the Language field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetLanguageOk() (*string, bool) {
	if o == nil || IsNil(o.Language) {
		return nil, false
	}
	return o.Language, true
}

// HasLanguage returns a boolean if a field has been set.
func (o *User) HasLanguage() bool {
	if o != nil && !IsNil(o.Language) {
		return true
	}

	return false
}

// SetLanguage gets a reference to the given string and assigns it to the Language field.
func (o *User) SetLanguage(v string) {
	o.Language = &v
}

// GetLastActiveDate returns the LastActiveDate field value if set, zero value otherwise.
func (o *User) GetLastActiveDate() string {
	if o == nil || IsNil(o.LastActiveDate) {
		var ret string
		return ret
	}
	return *o.LastActiveDate
}

// GetLastActiveDateOk returns a tuple with the LastActiveDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetLastActiveDateOk() (*string, bool) {
	if o == nil || IsNil(o.LastActiveDate) {
		return nil, false
	}
	return o.LastActiveDate, true
}

// HasLastActiveDate returns a boolean if a field has been set.
func (o *User) HasLastActiveDate() bool {
	if o != nil && !IsNil(o.LastActiveDate) {
		return true
	}

	return false
}

// SetLastActiveDate gets a reference to the given string and assigns it to the LastActiveDate field.
func (o *User) SetLastActiveDate(v string) {
	o.LastActiveDate = &v
}

// GetLastLoginDate returns the LastLoginDate field value if set, zero value otherwise.
func (o *User) GetLastLoginDate() string {
	if o == nil || IsNil(o.LastLoginDate) {
		var ret string
		return ret
	}
	return *o.LastLoginDate
}

// GetLastLoginDateOk returns a tuple with the LastLoginDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetLastLoginDateOk() (*string, bool) {
	if o == nil || IsNil(o.LastLoginDate) {
		return nil, false
	}
	return o.LastLoginDate, true
}

// HasLastLoginDate returns a boolean if a field has been set.
func (o *User) HasLastLoginDate() bool {
	if o != nil && !IsNil(o.LastLoginDate) {
		return true
	}

	return false
}

// SetLastLoginDate gets a reference to the given string and assigns it to the LastLoginDate field.
func (o *User) SetLastLoginDate(v string) {
	o.LastLoginDate = &v
}

// GetLastName returns the LastName field value if set, zero value otherwise.
func (o *User) GetLastName() string {
	if o == nil || IsNil(o.LastName) {
		var ret string
		return ret
	}
	return *o.LastName
}

// GetLastNameOk returns a tuple with the LastName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetLastNameOk() (*string, bool) {
	if o == nil || IsNil(o.LastName) {
		return nil, false
	}
	return o.LastName, true
}

// HasLastName returns a boolean if a field has been set.
func (o *User) HasLastName() bool {
	if o != nil && !IsNil(o.LastName) {
		return true
	}

	return false
}

// SetLastName gets a reference to the given string and assigns it to the LastName field.
func (o *User) SetLastName(v string) {
	o.LastName = &v
}

// GetLastPasswordUpdateDate returns the LastPasswordUpdateDate field value if set, zero value otherwise.
func (o *User) GetLastPasswordUpdateDate() string {
	if o == nil || IsNil(o.LastPasswordUpdateDate) {
		var ret string
		return ret
	}
	return *o.LastPasswordUpdateDate
}

// GetLastPasswordUpdateDateOk returns a tuple with the LastPasswordUpdateDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetLastPasswordUpdateDateOk() (*string, bool) {
	if o == nil || IsNil(o.LastPasswordUpdateDate) {
		return nil, false
	}
	return o.LastPasswordUpdateDate, true
}

// HasLastPasswordUpdateDate returns a boolean if a field has been set.
func (o *User) HasLastPasswordUpdateDate() bool {
	if o != nil && !IsNil(o.LastPasswordUpdateDate) {
		return true
	}

	return false
}

// SetLastPasswordUpdateDate gets a reference to the given string and assigns it to the LastPasswordUpdateDate field.
func (o *User) SetLastPasswordUpdateDate(v string) {
	o.LastPasswordUpdateDate = &v
}

// GetLastSystemTimeZoneName returns the LastSystemTimeZoneName field value if set, zero value otherwise.
func (o *User) GetLastSystemTimeZoneName() string {
	if o == nil || IsNil(o.LastSystemTimeZoneName) {
		var ret string
		return ret
	}
	return *o.LastSystemTimeZoneName
}

// GetLastSystemTimeZoneNameOk returns a tuple with the LastSystemTimeZoneName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetLastSystemTimeZoneNameOk() (*string, bool) {
	if o == nil || IsNil(o.LastSystemTimeZoneName) {
		return nil, false
	}
	return o.LastSystemTimeZoneName, true
}

// HasLastSystemTimeZoneName returns a boolean if a field has been set.
func (o *User) HasLastSystemTimeZoneName() bool {
	if o != nil && !IsNil(o.LastSystemTimeZoneName) {
		return true
	}

	return false
}

// SetLastSystemTimeZoneName gets a reference to the given string and assigns it to the LastSystemTimeZoneName field.
func (o *User) SetLastSystemTimeZoneName(v string) {
	o.LastSystemTimeZoneName = &v
}

// GetLdapUuid returns the LdapUuid field value if set, zero value otherwise.
func (o *User) GetLdapUuid() string {
	if o == nil || IsNil(o.LdapUuid) {
		var ret string
		return ret
	}
	return *o.LdapUuid
}

// GetLdapUuidOk returns a tuple with the LdapUuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetLdapUuidOk() (*string, bool) {
	if o == nil || IsNil(o.LdapUuid) {
		return nil, false
	}
	return o.LdapUuid, true
}

// HasLdapUuid returns a boolean if a field has been set.
func (o *User) HasLdapUuid() bool {
	if o != nil && !IsNil(o.LdapUuid) {
		return true
	}

	return false
}

// SetLdapUuid gets a reference to the given string and assigns it to the LdapUuid field.
func (o *User) SetLdapUuid(v string) {
	o.LdapUuid = &v
}

// GetLocale returns the Locale field value if set, zero value otherwise.
func (o *User) GetLocale() string {
	if o == nil || IsNil(o.Locale) {
		var ret string
		return ret
	}
	return *o.Locale
}

// GetLocaleOk returns a tuple with the Locale field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetLocaleOk() (*string, bool) {
	if o == nil || IsNil(o.Locale) {
		return nil, false
	}
	return o.Locale, true
}

// HasLocale returns a boolean if a field has been set.
func (o *User) HasLocale() bool {
	if o != nil && !IsNil(o.Locale) {
		return true
	}

	return false
}

// SetLocale gets a reference to the given string and assigns it to the Locale field.
func (o *User) SetLocale(v string) {
	o.Locale = &v
}

// GetMiddleName returns the MiddleName field value if set, zero value otherwise.
func (o *User) GetMiddleName() string {
	if o == nil || IsNil(o.MiddleName) {
		var ret string
		return ret
	}
	return *o.MiddleName
}

// GetMiddleNameOk returns a tuple with the MiddleName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetMiddleNameOk() (*string, bool) {
	if o == nil || IsNil(o.MiddleName) {
		return nil, false
	}
	return o.MiddleName, true
}

// HasMiddleName returns a boolean if a field has been set.
func (o *User) HasMiddleName() bool {
	if o != nil && !IsNil(o.MiddleName) {
		return true
	}

	return false
}

// SetMiddleName gets a reference to the given string and assigns it to the MiddleName field.
func (o *User) SetMiddleName(v string) {
	o.MiddleName = &v
}

// GetNetworkID returns the NetworkID field value if set, zero value otherwise.
func (o *User) GetNetworkID() string {
	if o == nil || IsNil(o.NetworkID) {
		var ret string
		return ret
	}
	return *o.NetworkID
}

// GetNetworkIDOk returns a tuple with the NetworkID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetNetworkIDOk() (*string, bool) {
	if o == nil || IsNil(o.NetworkID) {
		return nil, false
	}
	return o.NetworkID, true
}

// HasNetworkID returns a boolean if a field has been set.
func (o *User) HasNetworkID() bool {
	if o != nil && !IsNil(o.NetworkID) {
		return true
	}

	return false
}

// SetNetworkID gets a reference to the given string and assigns it to the NetworkID field.
func (o *User) SetNetworkID(v string) {
	o.NetworkID = &v
}

// GetObjectID returns the ObjectID field value if set, zero value otherwise.
func (o *User) GetObjectID() int64 {
	if o == nil || IsNil(o.ObjectID) {
		var ret int64
		return ret
	}
	return *o.ObjectID
}

// GetObjectIDOk returns a tuple with the ObjectID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetObjectIDOk() (*int64, bool) {
	if o == nil || IsNil(o.ObjectID) {
		return nil, false
	}
	return o.ObjectID, true
}

// HasObjectID returns a boolean if a field has been set.
func (o *User) HasObjectID() bool {
	if o != nil && !IsNil(o.ObjectID) {
		return true
	}

	return false
}

// SetObjectID gets a reference to the given int64 and assigns it to the ObjectID field.
func (o *User) SetObjectID(v int64) {
	o.ObjectID = &v
}

// GetObjectUUID returns the ObjectUUID field value if set, zero value otherwise.
func (o *User) GetObjectUUID() string {
	if o == nil || IsNil(o.ObjectUUID) {
		var ret string
		return ret
	}
	return *o.ObjectUUID
}

// GetObjectUUIDOk returns a tuple with the ObjectUUID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetObjectUUIDOk() (*string, bool) {
	if o == nil || IsNil(o.ObjectUUID) {
		return nil, false
	}
	return o.ObjectUUID, true
}

// HasObjectUUID returns a boolean if a field has been set.
func (o *User) HasObjectUUID() bool {
	if o != nil && !IsNil(o.ObjectUUID) {
		return true
	}

	return false
}

// SetObjectUUID gets a reference to the given string and assigns it to the ObjectUUID field.
func (o *User) SetObjectUUID(v string) {
	o.ObjectUUID = &v
}

// GetOfficeLocation returns the OfficeLocation field value if set, zero value otherwise.
func (o *User) GetOfficeLocation() string {
	if o == nil || IsNil(o.OfficeLocation) {
		var ret string
		return ret
	}
	return *o.OfficeLocation
}

// GetOfficeLocationOk returns a tuple with the OfficeLocation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetOfficeLocationOk() (*string, bool) {
	if o == nil || IsNil(o.OfficeLocation) {
		return nil, false
	}
	return o.OfficeLocation, true
}

// HasOfficeLocation returns a boolean if a field has been set.
func (o *User) HasOfficeLocation() bool {
	if o != nil && !IsNil(o.OfficeLocation) {
		return true
	}

	return false
}

// SetOfficeLocation gets a reference to the given string and assigns it to the OfficeLocation field.
func (o *User) SetOfficeLocation(v string) {
	o.OfficeLocation = &v
}

// GetOkrAdmin returns the OkrAdmin field value if set, zero value otherwise.
func (o *User) GetOkrAdmin() bool {
	if o == nil || IsNil(o.OkrAdmin) {
		var ret bool
		return ret
	}
	return *o.OkrAdmin
}

// GetOkrAdminOk returns a tuple with the OkrAdmin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetOkrAdminOk() (*bool, bool) {
	if o == nil || IsNil(o.OkrAdmin) {
		return nil, false
	}
	return o.OkrAdmin, true
}

// HasOkrAdmin returns a boolean if a field has been set.
func (o *User) HasOkrAdmin() bool {
	if o != nil && !IsNil(o.OkrAdmin) {
		return true
	}

	return false
}

// SetOkrAdmin gets a reference to the given bool and assigns it to the OkrAdmin field.
func (o *User) SetOkrAdmin(v bool) {
	o.OkrAdmin = &v
}

// GetOnpremLdapUsername returns the OnpremLdapUsername field value if set, zero value otherwise.
func (o *User) GetOnpremLdapUsername() string {
	if o == nil || IsNil(o.OnpremLdapUsername) {
		var ret string
		return ret
	}
	return *o.OnpremLdapUsername
}

// GetOnpremLdapUsernameOk returns a tuple with the OnpremLdapUsername field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetOnpremLdapUsernameOk() (*string, bool) {
	if o == nil || IsNil(o.OnpremLdapUsername) {
		return nil, false
	}
	return o.OnpremLdapUsername, true
}

// HasOnpremLdapUsername returns a boolean if a field has been set.
func (o *User) HasOnpremLdapUsername() bool {
	if o != nil && !IsNil(o.OnpremLdapUsername) {
		return true
	}

	return false
}

// SetOnpremLdapUsername gets a reference to the given string and assigns it to the OnpremLdapUsername field.
func (o *User) SetOnpremLdapUsername(v string) {
	o.OnpremLdapUsername = &v
}

// GetPasswordExpires returns the PasswordExpires field value if set, zero value otherwise.
func (o *User) GetPasswordExpires() int64 {
	if o == nil || IsNil(o.PasswordExpires) {
		var ret int64
		return ret
	}
	return *o.PasswordExpires
}

// GetPasswordExpiresOk returns a tuple with the PasswordExpires field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetPasswordExpiresOk() (*int64, bool) {
	if o == nil || IsNil(o.PasswordExpires) {
		return nil, false
	}
	return o.PasswordExpires, true
}

// HasPasswordExpires returns a boolean if a field has been set.
func (o *User) HasPasswordExpires() bool {
	if o != nil && !IsNil(o.PasswordExpires) {
		return true
	}

	return false
}

// SetPasswordExpires gets a reference to the given int64 and assigns it to the PasswordExpires field.
func (o *User) SetPasswordExpires(v int64) {
	o.PasswordExpires = &v
}

// GetPhone returns the Phone field value if set, zero value otherwise.
func (o *User) GetPhone() string {
	if o == nil || IsNil(o.Phone) {
		var ret string
		return ret
	}
	return *o.Phone
}

// GetPhoneOk returns a tuple with the Phone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetPhoneOk() (*string, bool) {
	if o == nil || IsNil(o.Phone) {
		return nil, false
	}
	return o.Phone, true
}

// HasPhone returns a boolean if a field has been set.
func (o *User) HasPhone() bool {
	if o != nil && !IsNil(o.Phone) {
		return true
	}

	return false
}

// SetPhone gets a reference to the given string and assigns it to the Phone field.
func (o *User) SetPhone(v string) {
	o.Phone = &v
}

// GetPlanner returns the Planner field value if set, zero value otherwise.
func (o *User) GetPlanner() bool {
	if o == nil || IsNil(o.Planner) {
		var ret bool
		return ret
	}
	return *o.Planner
}

// GetPlannerOk returns a tuple with the Planner field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetPlannerOk() (*bool, bool) {
	if o == nil || IsNil(o.Planner) {
		return nil, false
	}
	return o.Planner, true
}

// HasPlanner returns a boolean if a field has been set.
func (o *User) HasPlanner() bool {
	if o != nil && !IsNil(o.Planner) {
		return true
	}

	return false
}

// SetPlanner gets a reference to the given bool and assigns it to the Planner field.
func (o *User) SetPlanner(v bool) {
	o.Planner = &v
}

// GetProfileImage returns the ProfileImage field value if set, zero value otherwise.
func (o *User) GetProfileImage() ProfileImageRef {
	if o == nil || IsNil(o.ProfileImage) {
		var ret ProfileImageRef
		return ret
	}
	return *o.ProfileImage
}

// GetProfileImageOk returns a tuple with the ProfileImage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetProfileImageOk() (*ProfileImageRef, bool) {
	if o == nil || IsNil(o.ProfileImage) {
		return nil, false
	}
	return o.ProfileImage, true
}

// HasProfileImage returns a boolean if a field has been set.
func (o *User) HasProfileImage() bool {
	if o != nil && !IsNil(o.ProfileImage) {
		return true
	}

	return false
}

// SetProfileImage gets a reference to the given ProfileImageRef and assigns it to the ProfileImage field.
func (o *User) SetProfileImage(v ProfileImageRef) {
	o.ProfileImage = &v
}

// GetProjectScopeDown returns the ProjectScopeDown field value if set, zero value otherwise.
func (o *User) GetProjectScopeDown() bool {
	if o == nil || IsNil(o.ProjectScopeDown) {
		var ret bool
		return ret
	}
	return *o.ProjectScopeDown
}

// GetProjectScopeDownOk returns a tuple with the ProjectScopeDown field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetProjectScopeDownOk() (*bool, bool) {
	if o == nil || IsNil(o.ProjectScopeDown) {
		return nil, false
	}
	return o.ProjectScopeDown, true
}

// HasProjectScopeDown returns a boolean if a field has been set.
func (o *User) HasProjectScopeDown() bool {
	if o != nil && !IsNil(o.ProjectScopeDown) {
		return true
	}

	return false
}

// SetProjectScopeDown gets a reference to the given bool and assigns it to the ProjectScopeDown field.
func (o *User) SetProjectScopeDown(v bool) {
	o.ProjectScopeDown = &v
}

// GetProjectScopeUp returns the ProjectScopeUp field value if set, zero value otherwise.
func (o *User) GetProjectScopeUp() bool {
	if o == nil || IsNil(o.ProjectScopeUp) {
		var ret bool
		return ret
	}
	return *o.ProjectScopeUp
}

// GetProjectScopeUpOk returns a tuple with the ProjectScopeUp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetProjectScopeUpOk() (*bool, bool) {
	if o == nil || IsNil(o.ProjectScopeUp) {
		return nil, false
	}
	return o.ProjectScopeUp, true
}

// HasProjectScopeUp returns a boolean if a field has been set.
func (o *User) HasProjectScopeUp() bool {
	if o != nil && !IsNil(o.ProjectScopeUp) {
		return true
	}

	return false
}

// SetProjectScopeUp gets a reference to the given bool and assigns it to the ProjectScopeUp field.
func (o *User) SetProjectScopeUp(v bool) {
	o.ProjectScopeUp = &v
}

// GetRevisionHistory returns the RevisionHistory field value if set, zero value otherwise.
func (o *User) GetRevisionHistory() RevisionHistoryRef {
	if o == nil || IsNil(o.RevisionHistory) {
		var ret RevisionHistoryRef
		return ret
	}
	return *o.RevisionHistory
}

// GetRevisionHistoryOk returns a tuple with the RevisionHistory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetRevisionHistoryOk() (*RevisionHistoryRef, bool) {
	if o == nil || IsNil(o.RevisionHistory) {
		return nil, false
	}
	return o.RevisionHistory, true
}

// HasRevisionHistory returns a boolean if a field has been set.
func (o *User) HasRevisionHistory() bool {
	if o != nil && !IsNil(o.RevisionHistory) {
		return true
	}

	return false
}

// SetRevisionHistory gets a reference to the given RevisionHistoryRef and assigns it to the RevisionHistory field.
func (o *User) SetRevisionHistory(v RevisionHistoryRef) {
	o.RevisionHistory = &v
}

// GetRole returns the Role field value if set, zero value otherwise.
func (o *User) GetRole() string {
	if o == nil || IsNil(o.Role) {
		var ret string
		return ret
	}
	return *o.Role
}

// GetRoleOk returns a tuple with the Role field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetRoleOk() (*string, bool) {
	if o == nil || IsNil(o.Role) {
		return nil, false
	}
	return o.Role, true
}

// HasRole returns a boolean if a field has been set.
func (o *User) HasRole() bool {
	if o != nil && !IsNil(o.Role) {
		return true
	}

	return false
}

// SetRole gets a reference to the given string and assigns it to the Role field.
func (o *User) SetRole(v string) {
	o.Role = &v
}

// GetSessionTimeoutWarning returns the SessionTimeoutWarning field value if set, zero value otherwise.
func (o *User) GetSessionTimeoutWarning() bool {
	if o == nil || IsNil(o.SessionTimeoutWarning) {
		var ret bool
		return ret
	}
	return *o.SessionTimeoutWarning
}

// GetSessionTimeoutWarningOk returns a tuple with the SessionTimeoutWarning field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetSessionTimeoutWarningOk() (*bool, bool) {
	if o == nil || IsNil(o.SessionTimeoutWarning) {
		return nil, false
	}
	return o.SessionTimeoutWarning, true
}

// HasSessionTimeoutWarning returns a boolean if a field has been set.
func (o *User) HasSessionTimeoutWarning() bool {
	if o != nil && !IsNil(o.SessionTimeoutWarning) {
		return true
	}

	return false
}

// SetSessionTimeoutWarning gets a reference to the given bool and assigns it to the SessionTimeoutWarning field.
func (o *User) SetSessionTimeoutWarning(v bool) {
	o.SessionTimeoutWarning = &v
}

// GetShortDisplayName returns the ShortDisplayName field value if set, zero value otherwise.
func (o *User) GetShortDisplayName() string {
	if o == nil || IsNil(o.ShortDisplayName) {
		var ret string
		return ret
	}
	return *o.ShortDisplayName
}

// GetShortDisplayNameOk returns a tuple with the ShortDisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetShortDisplayNameOk() (*string, bool) {
	if o == nil || IsNil(o.ShortDisplayName) {
		return nil, false
	}
	return o.ShortDisplayName, true
}

// HasShortDisplayName returns a boolean if a field has been set.
func (o *User) HasShortDisplayName() bool {
	if o != nil && !IsNil(o.ShortDisplayName) {
		return true
	}

	return false
}

// SetShortDisplayName gets a reference to the given string and assigns it to the ShortDisplayName field.
func (o *User) SetShortDisplayName(v string) {
	o.ShortDisplayName = &v
}

// GetSubscription returns the Subscription field value if set, zero value otherwise.
func (o *User) GetSubscription() SubscriptionRef {
	if o == nil || IsNil(o.Subscription) {
		var ret SubscriptionRef
		return ret
	}
	return *o.Subscription
}

// GetSubscriptionOk returns a tuple with the Subscription field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetSubscriptionOk() (*SubscriptionRef, bool) {
	if o == nil || IsNil(o.Subscription) {
		return nil, false
	}
	return o.Subscription, true
}

// HasSubscription returns a boolean if a field has been set.
func (o *User) HasSubscription() bool {
	if o != nil && !IsNil(o.Subscription) {
		return true
	}

	return false
}

// SetSubscription gets a reference to the given SubscriptionRef and assigns it to the Subscription field.
func (o *User) SetSubscription(v SubscriptionRef) {
	o.Subscription = &v
}

// GetSubscriptionAdmin returns the SubscriptionAdmin field value if set, zero value otherwise.
func (o *User) GetSubscriptionAdmin() bool {
	if o == nil || IsNil(o.SubscriptionAdmin) {
		var ret bool
		return ret
	}
	return *o.SubscriptionAdmin
}

// GetSubscriptionAdminOk returns a tuple with the SubscriptionAdmin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetSubscriptionAdminOk() (*bool, bool) {
	if o == nil || IsNil(o.SubscriptionAdmin) {
		return nil, false
	}
	return o.SubscriptionAdmin, true
}

// HasSubscriptionAdmin returns a boolean if a field has been set.
func (o *User) HasSubscriptionAdmin() bool {
	if o != nil && !IsNil(o.SubscriptionAdmin) {
		return true
	}

	return false
}

// SetSubscriptionAdmin gets a reference to the given bool and assigns it to the SubscriptionAdmin field.
func (o *User) SetSubscriptionAdmin(v bool) {
	o.SubscriptionAdmin = &v
}

// GetSubscriptionID returns the SubscriptionID field value if set, zero value otherwise.
func (o *User) GetSubscriptionID() int64 {
	if o == nil || IsNil(o.SubscriptionID) {
		var ret int64
		return ret
	}
	return *o.SubscriptionID
}

// GetSubscriptionIDOk returns a tuple with the SubscriptionID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetSubscriptionIDOk() (*int64, bool) {
	if o == nil || IsNil(o.SubscriptionID) {
		return nil, false
	}
	return o.SubscriptionID, true
}

// HasSubscriptionID returns a boolean if a field has been set.
func (o *User) HasSubscriptionID() bool {
	if o != nil && !IsNil(o.SubscriptionID) {
		return true
	}

	return false
}

// SetSubscriptionID gets a reference to the given int64 and assigns it to the SubscriptionID field.
func (o *User) SetSubscriptionID(v int64) {
	o.SubscriptionID = &v
}

// GetSubscriptionPermission returns the SubscriptionPermission field value if set, zero value otherwise.
func (o *User) GetSubscriptionPermission() string {
	if o == nil || IsNil(o.SubscriptionPermission) {
		var ret string
		return ret
	}
	return *o.SubscriptionPermission
}

// GetSubscriptionPermissionOk returns a tuple with the SubscriptionPermission field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetSubscriptionPermissionOk() (*string, bool) {
	if o == nil || IsNil(o.SubscriptionPermission) {
		return nil, false
	}
	return o.SubscriptionPermission, true
}

// HasSubscriptionPermission returns a boolean if a field has been set.
func (o *User) HasSubscriptionPermission() bool {
	if o != nil && !IsNil(o.SubscriptionPermission) {
		return true
	}

	return false
}

// SetSubscriptionPermission gets a reference to the given string and assigns it to the SubscriptionPermission field.
func (o *User) SetSubscriptionPermission(v string) {
	o.SubscriptionPermission = &v
}

// GetTeamMemberships returns the TeamMemberships field value if set, zero value otherwise.
func (o *User) GetTeamMemberships() Collection {
	if o == nil || IsNil(o.TeamMemberships) {
		var ret Collection
		return ret
	}
	return *o.TeamMemberships
}

// GetTeamMembershipsOk returns a tuple with the TeamMemberships field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetTeamMembershipsOk() (*Collection, bool) {
	if o == nil || IsNil(o.TeamMemberships) {
		return nil, false
	}
	return o.TeamMemberships, true
}

// HasTeamMemberships returns a boolean if a field has been set.
func (o *User) HasTeamMemberships() bool {
	if o != nil && !IsNil(o.TeamMemberships) {
		return true
	}

	return false
}

// SetTeamMemberships gets a reference to the given Collection and assigns it to the TeamMemberships field.
func (o *User) SetTeamMemberships(v Collection) {
	o.TeamMemberships = &v
}

// GetTimeboxAdmin returns the TimeboxAdmin field value if set, zero value otherwise.
func (o *User) GetTimeboxAdmin() bool {
	if o == nil || IsNil(o.TimeboxAdmin) {
		var ret bool
		return ret
	}
	return *o.TimeboxAdmin
}

// GetTimeboxAdminOk returns a tuple with the TimeboxAdmin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetTimeboxAdminOk() (*bool, bool) {
	if o == nil || IsNil(o.TimeboxAdmin) {
		return nil, false
	}
	return o.TimeboxAdmin, true
}

// HasTimeboxAdmin returns a boolean if a field has been set.
func (o *User) HasTimeboxAdmin() bool {
	if o != nil && !IsNil(o.TimeboxAdmin) {
		return true
	}

	return false
}

// SetTimeboxAdmin gets a reference to the given bool and assigns it to the TimeboxAdmin field.
func (o *User) SetTimeboxAdmin(v bool) {
	o.TimeboxAdmin = &v
}

// GetUserName returns the UserName field value if set, zero value otherwise.
func (o *User) GetUserName() string {
	if o == nil || IsNil(o.UserName) {
		var ret string
		return ret
	}
	return *o.UserName
}

// GetUserNameOk returns a tuple with the UserName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetUserNameOk() (*string, bool) {
	if o == nil || IsNil(o.UserName) {
		return nil, false
	}
	return o.UserName, true
}

// HasUserName returns a boolean if a field has been set.
func (o *User) HasUserName() bool {
	if o != nil && !IsNil(o.UserName) {
		return true
	}

	return false
}

// SetUserName gets a reference to the given string and assigns it to the UserName field.
func (o *User) SetUserName(v string) {
	o.UserName = &v
}

// GetUserPermissions returns the UserPermissions field value if set, zero value otherwise.
func (o *User) GetUserPermissions() Collection {
	if o == nil || IsNil(o.UserPermissions) {
		var ret Collection
		return ret
	}
	return *o.UserPermissions
}

// GetUserPermissionsOk returns a tuple with the UserPermissions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetUserPermissionsOk() (*Collection, bool) {
	if o == nil || IsNil(o.UserPermissions) {
		return nil, false
	}
	return o.UserPermissions, true
}

// HasUserPermissions returns a boolean if a field has been set.
func (o *User) HasUserPermissions() bool {
	if o != nil && !IsNil(o.UserPermissions) {
		return true
	}

	return false
}

// SetUserPermissions gets a reference to the given Collection and assigns it to the UserPermissions field.
func (o *User) SetUserPermissions(v Collection) {
	o.UserPermissions = &v
}

// GetUserProfile returns the UserProfile field value if set, zero value otherwise.
func (o *User) GetUserProfile() UserProfileRef {
	if o == nil || IsNil(o.UserProfile) {
		var ret UserProfileRef
		return ret
	}
	return *o.UserProfile
}

// GetUserProfileOk returns a tuple with the UserProfile field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetUserProfileOk() (*UserProfileRef, bool) {
	if o == nil || IsNil(o.UserProfile) {
		return nil, false
	}
	return o.UserProfile, true
}

// HasUserProfile returns a boolean if a field has been set.
func (o *User) HasUserProfile() bool {
	if o != nil && !IsNil(o.UserProfile) {
		return true
	}

	return false
}

// SetUserProfile gets a reference to the given UserProfileRef and assigns it to the UserProfile field.
func (o *User) SetUserProfile(v UserProfileRef) {
	o.UserProfile = &v
}

// GetVersionId returns the VersionId field value if set, zero value otherwise.
func (o *User) GetVersionId() string {
	if o == nil || IsNil(o.VersionId) {
		var ret string
		return ret
	}
	return *o.VersionId
}

// GetVersionIdOk returns a tuple with the VersionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetVersionIdOk() (*string, bool) {
	if o == nil || IsNil(o.VersionId) {
		return nil, false
	}
	return o.VersionId, true
}

// HasVersionId returns a boolean if a field has been set.
func (o *User) HasVersionId() bool {
	if o != nil && !IsNil(o.VersionId) {
		return true
	}

	return false
}

// SetVersionId gets a reference to the given string and assigns it to the VersionId field.
func (o *User) SetVersionId(v string) {
	o.VersionId = &v
}

// GetVsiAdmin returns the VsiAdmin field value if set, zero value otherwise.
func (o *User) GetVsiAdmin() bool {
	if o == nil || IsNil(o.VsiAdmin) {
		var ret bool
		return ret
	}
	return *o.VsiAdmin
}

// GetVsiAdminOk returns a tuple with the VsiAdmin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetVsiAdminOk() (*bool, bool) {
	if o == nil || IsNil(o.VsiAdmin) {
		return nil, false
	}
	return o.VsiAdmin, true
}

// HasVsiAdmin returns a boolean if a field has been set.
func (o *User) HasVsiAdmin() bool {
	if o != nil && !IsNil(o.VsiAdmin) {
		return true
	}

	return false
}

// SetVsiAdmin gets a reference to the given bool and assigns it to the VsiAdmin field.
func (o *User) SetVsiAdmin(v bool) {
	o.VsiAdmin = &v
}

// GetWorkspacePermission returns the WorkspacePermission field value if set, zero value otherwise.
func (o *User) GetWorkspacePermission() string {
	if o == nil || IsNil(o.WorkspacePermission) {
		var ret string
		return ret
	}
	return *o.WorkspacePermission
}

// GetWorkspacePermissionOk returns a tuple with the WorkspacePermission field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetWorkspacePermissionOk() (*string, bool) {
	if o == nil || IsNil(o.WorkspacePermission) {
		return nil, false
	}
	return o.WorkspacePermission, true
}

// HasWorkspacePermission returns a boolean if a field has been set.
func (o *User) HasWorkspacePermission() bool {
	if o != nil && !IsNil(o.WorkspacePermission) {
		return true
	}

	return false
}

// SetWorkspacePermission gets a reference to the given string and assigns it to the WorkspacePermission field.
func (o *User) SetWorkspacePermission(v string) {
	o.WorkspacePermission = &v
}

// GetZuulID returns the ZuulID field value if set, zero value otherwise.
func (o *User) GetZuulID() string {
	if o == nil || IsNil(o.ZuulID) {
		var ret string
		return ret
	}
	return *o.ZuulID
}

// GetZuulIDOk returns a tuple with the ZuulID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetZuulIDOk() (*string, bool) {
	if o == nil || IsNil(o.ZuulID) {
		return nil, false
	}
	return o.ZuulID, true
}

// HasZuulID returns a boolean if a field has been set.
func (o *User) HasZuulID() bool {
	if o != nil && !IsNil(o.ZuulID) {
		return true
	}

	return false
}

// SetZuulID gets a reference to the given string and assigns it to the ZuulID field.
func (o *User) SetZuulID(v string) {
	o.ZuulID = &v
}

// GetCBusinessUnit returns the CBusinessUnit field value if set, zero value otherwise.
func (o *User) GetCBusinessUnit() string {
	if o == nil || IsNil(o.CBusinessUnit) {
		var ret string
		return ret
	}
	return *o.CBusinessUnit
}

// GetCBusinessUnitOk returns a tuple with the CBusinessUnit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetCBusinessUnitOk() (*string, bool) {
	if o == nil || IsNil(o.CBusinessUnit) {
		return nil, false
	}
	return o.CBusinessUnit, true
}

// HasCBusinessUnit returns a boolean if a field has been set.
func (o *User) HasCBusinessUnit() bool {
	if o != nil && !IsNil(o.CBusinessUnit) {
		return true
	}

	return false
}

// SetCBusinessUnit gets a reference to the given string and assigns it to the CBusinessUnit field.
func (o *User) SetCBusinessUnit(v string) {
	o.CBusinessUnit = &v
}

// GetSessionTimeout returns the SessionTimeout field value if set, zero value otherwise.
func (o *User) GetSessionTimeout() int64 {
	if o == nil || IsNil(o.SessionTimeout) {
		var ret int64
		return ret
	}
	return *o.SessionTimeout
}

// GetSessionTimeoutOk returns a tuple with the SessionTimeout field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetSessionTimeoutOk() (*int64, bool) {
	if o == nil || IsNil(o.SessionTimeout) {
		return nil, false
	}
	return o.SessionTimeout, true
}

// HasSessionTimeout returns a boolean if a field has been set.
func (o *User) HasSessionTimeout() bool {
	if o != nil && !IsNil(o.SessionTimeout) {
		return true
	}

	return false
}

// SetSessionTimeout gets a reference to the given int64 and assigns it to the SessionTimeout field.
func (o *User) SetSessionTimeout(v int64) {
	o.SessionTimeout = &v
}

// GetSubscriptionOid returns the SubscriptionOid field value if set, zero value otherwise.
func (o *User) GetSubscriptionOid() int64 {
	if o == nil || IsNil(o.SubscriptionOid) {
		var ret int64
		return ret
	}
	return *o.SubscriptionOid
}

// GetSubscriptionOidOk returns a tuple with the SubscriptionOid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetSubscriptionOidOk() (*int64, bool) {
	if o == nil || IsNil(o.SubscriptionOid) {
		return nil, false
	}
	return o.SubscriptionOid, true
}

// HasSubscriptionOid returns a boolean if a field has been set.
func (o *User) HasSubscriptionOid() bool {
	if o != nil && !IsNil(o.SubscriptionOid) {
		return true
	}

	return false
}

// SetSubscriptionOid gets a reference to the given int64 and assigns it to the SubscriptionOid field.
func (o *User) SetSubscriptionOid(v int64) {
	o.SubscriptionOid = &v
}

// GetWarnings returns the Warnings field value if set, zero value otherwise.
func (o *User) GetWarnings() []string {
	if o == nil || IsNil(o.Warnings) {
		var ret []string
		return ret
	}
	return o.Warnings
}

// GetWarningsOk returns a tuple with the Warnings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetWarningsOk() ([]string, bool) {
	if o == nil || IsNil(o.Warnings) {
		return nil, false
	}
	return o.Warnings, true
}

// HasWarnings returns a boolean if a field has been set.
func (o *User) HasWarnings() bool {
	if o != nil && !IsNil(o.Warnings) {
		return true
	}

	return false
}

// SetWarnings gets a reference to the given []string and assigns it to the Warnings field.
func (o *User) SetWarnings(v []string) {
	o.Warnings = v
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *User) GetErrors() []string {
	if o == nil || IsNil(o.Errors) {
		var ret []string
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetErrorsOk() ([]string, bool) {
	if o == nil || IsNil(o.Errors) {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *User) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []string and assigns it to the Errors field.
func (o *User) SetErrors(v []string) {
	o.Errors = v
}

func (o User) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o User) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AccountLockedUntil) {
		toSerialize["AccountLockedUntil"] = o.AccountLockedUntil
	}
	if !IsNil(o.ArtifactsCreated) {
		toSerialize["ArtifactsCreated"] = o.ArtifactsCreated
	}
	if !IsNil(o.ArtifactsOwned) {
		toSerialize["ArtifactsOwned"] = o.ArtifactsOwned
	}
	if !IsNil(o.CostCenter) {
		toSerialize["CostCenter"] = o.CostCenter
	}
	if !IsNil(o.CreationDate) {
		toSerialize["CreationDate"] = o.CreationDate
	}
	if !IsNil(o.DateFormat) {
		toSerialize["DateFormat"] = o.DateFormat
	}
	if !IsNil(o.DateTimeFormat) {
		toSerialize["DateTimeFormat"] = o.DateTimeFormat
	}
	if !IsNil(o.DefaultDetailPageToViewingMode) {
		toSerialize["DefaultDetailPageToViewingMode"] = o.DefaultDetailPageToViewingMode
	}
	if !IsNil(o.DefaultProject) {
		toSerialize["DefaultProject"] = o.DefaultProject
	}
	if !IsNil(o.Deleted) {
		toSerialize["Deleted"] = o.Deleted
	}
	if !IsNil(o.Department) {
		toSerialize["Department"] = o.Department
	}
	if !IsNil(o.Disabled) {
		toSerialize["Disabled"] = o.Disabled
	}
	if !IsNil(o.DisplayName) {
		toSerialize["DisplayName"] = o.DisplayName
	}
	if !IsNil(o.EmailAddress) {
		toSerialize["EmailAddress"] = o.EmailAddress
	}
	if !IsNil(o.EmailNotificationEnabled) {
		toSerialize["EmailNotificationEnabled"] = o.EmailNotificationEnabled
	}
	if !IsNil(o.FirstName) {
		toSerialize["FirstName"] = o.FirstName
	}
	if !IsNil(o.InvestmentAdmin) {
		toSerialize["InvestmentAdmin"] = o.InvestmentAdmin
	}
	if !IsNil(o.IsProvisioningUser) {
		toSerialize["IsProvisioningUser"] = o.IsProvisioningUser
	}
	if !IsNil(o.IsSLMAdmin) {
		toSerialize["IsSLMAdmin"] = o.IsSLMAdmin
	}
	if !IsNil(o.LandingPage) {
		toSerialize["LandingPage"] = o.LandingPage
	}
	if !IsNil(o.Language) {
		toSerialize["Language"] = o.Language
	}
	if !IsNil(o.LastActiveDate) {
		toSerialize["LastActiveDate"] = o.LastActiveDate
	}
	if !IsNil(o.LastLoginDate) {
		toSerialize["LastLoginDate"] = o.LastLoginDate
	}
	if !IsNil(o.LastName) {
		toSerialize["LastName"] = o.LastName
	}
	if !IsNil(o.LastPasswordUpdateDate) {
		toSerialize["LastPasswordUpdateDate"] = o.LastPasswordUpdateDate
	}
	if !IsNil(o.LastSystemTimeZoneName) {
		toSerialize["LastSystemTimeZoneName"] = o.LastSystemTimeZoneName
	}
	if !IsNil(o.LdapUuid) {
		toSerialize["LdapUuid"] = o.LdapUuid
	}
	if !IsNil(o.Locale) {
		toSerialize["Locale"] = o.Locale
	}
	if !IsNil(o.MiddleName) {
		toSerialize["MiddleName"] = o.MiddleName
	}
	if !IsNil(o.NetworkID) {
		toSerialize["NetworkID"] = o.NetworkID
	}
	if !IsNil(o.ObjectID) {
		toSerialize["ObjectID"] = o.ObjectID
	}
	if !IsNil(o.ObjectUUID) {
		toSerialize["ObjectUUID"] = o.ObjectUUID
	}
	if !IsNil(o.OfficeLocation) {
		toSerialize["OfficeLocation"] = o.OfficeLocation
	}
	if !IsNil(o.OkrAdmin) {
		toSerialize["OkrAdmin"] = o.OkrAdmin
	}
	if !IsNil(o.OnpremLdapUsername) {
		toSerialize["OnpremLdapUsername"] = o.OnpremLdapUsername
	}
	if !IsNil(o.PasswordExpires) {
		toSerialize["PasswordExpires"] = o.PasswordExpires
	}
	if !IsNil(o.Phone) {
		toSerialize["Phone"] = o.Phone
	}
	if !IsNil(o.Planner) {
		toSerialize["Planner"] = o.Planner
	}
	if !IsNil(o.ProfileImage) {
		toSerialize["ProfileImage"] = o.ProfileImage
	}
	if !IsNil(o.ProjectScopeDown) {
		toSerialize["ProjectScopeDown"] = o.ProjectScopeDown
	}
	if !IsNil(o.ProjectScopeUp) {
		toSerialize["ProjectScopeUp"] = o.ProjectScopeUp
	}
	if !IsNil(o.RevisionHistory) {
		toSerialize["RevisionHistory"] = o.RevisionHistory
	}
	if !IsNil(o.Role) {
		toSerialize["Role"] = o.Role
	}
	if !IsNil(o.SessionTimeoutWarning) {
		toSerialize["SessionTimeoutWarning"] = o.SessionTimeoutWarning
	}
	if !IsNil(o.ShortDisplayName) {
		toSerialize["ShortDisplayName"] = o.ShortDisplayName
	}
	if !IsNil(o.Subscription) {
		toSerialize["Subscription"] = o.Subscription
	}
	if !IsNil(o.SubscriptionAdmin) {
		toSerialize["SubscriptionAdmin"] = o.SubscriptionAdmin
	}
	if !IsNil(o.SubscriptionID) {
		toSerialize["SubscriptionID"] = o.SubscriptionID
	}
	if !IsNil(o.SubscriptionPermission) {
		toSerialize["SubscriptionPermission"] = o.SubscriptionPermission
	}
	if !IsNil(o.TeamMemberships) {
		toSerialize["TeamMemberships"] = o.TeamMemberships
	}
	if !IsNil(o.TimeboxAdmin) {
		toSerialize["TimeboxAdmin"] = o.TimeboxAdmin
	}
	if !IsNil(o.UserName) {
		toSerialize["UserName"] = o.UserName
	}
	if !IsNil(o.UserPermissions) {
		toSerialize["UserPermissions"] = o.UserPermissions
	}
	if !IsNil(o.UserProfile) {
		toSerialize["UserProfile"] = o.UserProfile
	}
	if !IsNil(o.VersionId) {
		toSerialize["VersionId"] = o.VersionId
	}
	if !IsNil(o.VsiAdmin) {
		toSerialize["VsiAdmin"] = o.VsiAdmin
	}
	if !IsNil(o.WorkspacePermission) {
		toSerialize["WorkspacePermission"] = o.WorkspacePermission
	}
	if !IsNil(o.ZuulID) {
		toSerialize["ZuulID"] = o.ZuulID
	}
	if !IsNil(o.CBusinessUnit) {
		toSerialize["c_BusinessUnit"] = o.CBusinessUnit
	}
	if !IsNil(o.SessionTimeout) {
		toSerialize["sessionTimeout"] = o.SessionTimeout
	}
	if !IsNil(o.SubscriptionOid) {
		toSerialize["subscriptionOid"] = o.SubscriptionOid
	}
	if !IsNil(o.Warnings) {
		toSerialize["Warnings"] = o.Warnings
	}
	if !IsNil(o.Errors) {
		toSerialize["Errors"] = o.Errors
	}
	return toSerialize, nil
}

type NullableUser struct {
	value *User
	isSet bool
}

func (v NullableUser) Get() *User {
	return v.value
}

func (v *NullableUser) Set(val *User) {
	v.value = val
	v.isSet = true
}

func (v NullableUser) IsSet() bool {
	return v.isSet
}

func (v *NullableUser) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUser(val *User) *NullableUser {
	return &NullableUser{value: val, isSet: true}
}

func (v NullableUser) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUser) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


