/*
Rally WebService API

Rally Open API docs

API version: v2.0
Contact: support@rallydev.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the HierarchicalRequirementPredecessorRelationshipMutationHierarchicalRequirementPredecessorRelationship type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HierarchicalRequirementPredecessorRelationshipMutationHierarchicalRequirementPredecessorRelationship{}

// HierarchicalRequirementPredecessorRelationshipMutationHierarchicalRequirementPredecessorRelationship HierarchicalRequirementPredecessorRelationship
type HierarchicalRequirementPredecessorRelationshipMutationHierarchicalRequirementPredecessorRelationship struct {
	Predecessor *HierarchicalRequirementRef `json:"Predecessor,omitempty"`
	Successor *HierarchicalRequirementRef `json:"Successor,omitempty"`
	Workspace *WorkspaceRef `json:"Workspace,omitempty"`
	Warnings []string `json:"Warnings,omitempty"`
	Errors []string `json:"Errors,omitempty"`
}

// NewHierarchicalRequirementPredecessorRelationshipMutationHierarchicalRequirementPredecessorRelationship instantiates a new HierarchicalRequirementPredecessorRelationshipMutationHierarchicalRequirementPredecessorRelationship object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHierarchicalRequirementPredecessorRelationshipMutationHierarchicalRequirementPredecessorRelationship() *HierarchicalRequirementPredecessorRelationshipMutationHierarchicalRequirementPredecessorRelationship {
	this := HierarchicalRequirementPredecessorRelationshipMutationHierarchicalRequirementPredecessorRelationship{}
	return &this
}

// NewHierarchicalRequirementPredecessorRelationshipMutationHierarchicalRequirementPredecessorRelationshipWithDefaults instantiates a new HierarchicalRequirementPredecessorRelationshipMutationHierarchicalRequirementPredecessorRelationship object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHierarchicalRequirementPredecessorRelationshipMutationHierarchicalRequirementPredecessorRelationshipWithDefaults() *HierarchicalRequirementPredecessorRelationshipMutationHierarchicalRequirementPredecessorRelationship {
	this := HierarchicalRequirementPredecessorRelationshipMutationHierarchicalRequirementPredecessorRelationship{}
	return &this
}

// GetPredecessor returns the Predecessor field value if set, zero value otherwise.
func (o *HierarchicalRequirementPredecessorRelationshipMutationHierarchicalRequirementPredecessorRelationship) GetPredecessor() HierarchicalRequirementRef {
	if o == nil || IsNil(o.Predecessor) {
		var ret HierarchicalRequirementRef
		return ret
	}
	return *o.Predecessor
}

// GetPredecessorOk returns a tuple with the Predecessor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HierarchicalRequirementPredecessorRelationshipMutationHierarchicalRequirementPredecessorRelationship) GetPredecessorOk() (*HierarchicalRequirementRef, bool) {
	if o == nil || IsNil(o.Predecessor) {
		return nil, false
	}
	return o.Predecessor, true
}

// HasPredecessor returns a boolean if a field has been set.
func (o *HierarchicalRequirementPredecessorRelationshipMutationHierarchicalRequirementPredecessorRelationship) HasPredecessor() bool {
	if o != nil && !IsNil(o.Predecessor) {
		return true
	}

	return false
}

// SetPredecessor gets a reference to the given HierarchicalRequirementRef and assigns it to the Predecessor field.
func (o *HierarchicalRequirementPredecessorRelationshipMutationHierarchicalRequirementPredecessorRelationship) SetPredecessor(v HierarchicalRequirementRef) {
	o.Predecessor = &v
}

// GetSuccessor returns the Successor field value if set, zero value otherwise.
func (o *HierarchicalRequirementPredecessorRelationshipMutationHierarchicalRequirementPredecessorRelationship) GetSuccessor() HierarchicalRequirementRef {
	if o == nil || IsNil(o.Successor) {
		var ret HierarchicalRequirementRef
		return ret
	}
	return *o.Successor
}

// GetSuccessorOk returns a tuple with the Successor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HierarchicalRequirementPredecessorRelationshipMutationHierarchicalRequirementPredecessorRelationship) GetSuccessorOk() (*HierarchicalRequirementRef, bool) {
	if o == nil || IsNil(o.Successor) {
		return nil, false
	}
	return o.Successor, true
}

// HasSuccessor returns a boolean if a field has been set.
func (o *HierarchicalRequirementPredecessorRelationshipMutationHierarchicalRequirementPredecessorRelationship) HasSuccessor() bool {
	if o != nil && !IsNil(o.Successor) {
		return true
	}

	return false
}

// SetSuccessor gets a reference to the given HierarchicalRequirementRef and assigns it to the Successor field.
func (o *HierarchicalRequirementPredecessorRelationshipMutationHierarchicalRequirementPredecessorRelationship) SetSuccessor(v HierarchicalRequirementRef) {
	o.Successor = &v
}

// GetWorkspace returns the Workspace field value if set, zero value otherwise.
func (o *HierarchicalRequirementPredecessorRelationshipMutationHierarchicalRequirementPredecessorRelationship) GetWorkspace() WorkspaceRef {
	if o == nil || IsNil(o.Workspace) {
		var ret WorkspaceRef
		return ret
	}
	return *o.Workspace
}

// GetWorkspaceOk returns a tuple with the Workspace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HierarchicalRequirementPredecessorRelationshipMutationHierarchicalRequirementPredecessorRelationship) GetWorkspaceOk() (*WorkspaceRef, bool) {
	if o == nil || IsNil(o.Workspace) {
		return nil, false
	}
	return o.Workspace, true
}

// HasWorkspace returns a boolean if a field has been set.
func (o *HierarchicalRequirementPredecessorRelationshipMutationHierarchicalRequirementPredecessorRelationship) HasWorkspace() bool {
	if o != nil && !IsNil(o.Workspace) {
		return true
	}

	return false
}

// SetWorkspace gets a reference to the given WorkspaceRef and assigns it to the Workspace field.
func (o *HierarchicalRequirementPredecessorRelationshipMutationHierarchicalRequirementPredecessorRelationship) SetWorkspace(v WorkspaceRef) {
	o.Workspace = &v
}

// GetWarnings returns the Warnings field value if set, zero value otherwise.
func (o *HierarchicalRequirementPredecessorRelationshipMutationHierarchicalRequirementPredecessorRelationship) GetWarnings() []string {
	if o == nil || IsNil(o.Warnings) {
		var ret []string
		return ret
	}
	return o.Warnings
}

// GetWarningsOk returns a tuple with the Warnings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HierarchicalRequirementPredecessorRelationshipMutationHierarchicalRequirementPredecessorRelationship) GetWarningsOk() ([]string, bool) {
	if o == nil || IsNil(o.Warnings) {
		return nil, false
	}
	return o.Warnings, true
}

// HasWarnings returns a boolean if a field has been set.
func (o *HierarchicalRequirementPredecessorRelationshipMutationHierarchicalRequirementPredecessorRelationship) HasWarnings() bool {
	if o != nil && !IsNil(o.Warnings) {
		return true
	}

	return false
}

// SetWarnings gets a reference to the given []string and assigns it to the Warnings field.
func (o *HierarchicalRequirementPredecessorRelationshipMutationHierarchicalRequirementPredecessorRelationship) SetWarnings(v []string) {
	o.Warnings = v
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *HierarchicalRequirementPredecessorRelationshipMutationHierarchicalRequirementPredecessorRelationship) GetErrors() []string {
	if o == nil || IsNil(o.Errors) {
		var ret []string
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HierarchicalRequirementPredecessorRelationshipMutationHierarchicalRequirementPredecessorRelationship) GetErrorsOk() ([]string, bool) {
	if o == nil || IsNil(o.Errors) {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *HierarchicalRequirementPredecessorRelationshipMutationHierarchicalRequirementPredecessorRelationship) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []string and assigns it to the Errors field.
func (o *HierarchicalRequirementPredecessorRelationshipMutationHierarchicalRequirementPredecessorRelationship) SetErrors(v []string) {
	o.Errors = v
}

func (o HierarchicalRequirementPredecessorRelationshipMutationHierarchicalRequirementPredecessorRelationship) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HierarchicalRequirementPredecessorRelationshipMutationHierarchicalRequirementPredecessorRelationship) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Predecessor) {
		toSerialize["Predecessor"] = o.Predecessor
	}
	if !IsNil(o.Successor) {
		toSerialize["Successor"] = o.Successor
	}
	if !IsNil(o.Workspace) {
		toSerialize["Workspace"] = o.Workspace
	}
	if !IsNil(o.Warnings) {
		toSerialize["Warnings"] = o.Warnings
	}
	if !IsNil(o.Errors) {
		toSerialize["Errors"] = o.Errors
	}
	return toSerialize, nil
}

type NullableHierarchicalRequirementPredecessorRelationshipMutationHierarchicalRequirementPredecessorRelationship struct {
	value *HierarchicalRequirementPredecessorRelationshipMutationHierarchicalRequirementPredecessorRelationship
	isSet bool
}

func (v NullableHierarchicalRequirementPredecessorRelationshipMutationHierarchicalRequirementPredecessorRelationship) Get() *HierarchicalRequirementPredecessorRelationshipMutationHierarchicalRequirementPredecessorRelationship {
	return v.value
}

func (v *NullableHierarchicalRequirementPredecessorRelationshipMutationHierarchicalRequirementPredecessorRelationship) Set(val *HierarchicalRequirementPredecessorRelationshipMutationHierarchicalRequirementPredecessorRelationship) {
	v.value = val
	v.isSet = true
}

func (v NullableHierarchicalRequirementPredecessorRelationshipMutationHierarchicalRequirementPredecessorRelationship) IsSet() bool {
	return v.isSet
}

func (v *NullableHierarchicalRequirementPredecessorRelationshipMutationHierarchicalRequirementPredecessorRelationship) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHierarchicalRequirementPredecessorRelationshipMutationHierarchicalRequirementPredecessorRelationship(val *HierarchicalRequirementPredecessorRelationshipMutationHierarchicalRequirementPredecessorRelationship) *NullableHierarchicalRequirementPredecessorRelationshipMutationHierarchicalRequirementPredecessorRelationship {
	return &NullableHierarchicalRequirementPredecessorRelationshipMutationHierarchicalRequirementPredecessorRelationship{value: val, isSet: true}
}

func (v NullableHierarchicalRequirementPredecessorRelationshipMutationHierarchicalRequirementPredecessorRelationship) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHierarchicalRequirementPredecessorRelationshipMutationHierarchicalRequirementPredecessorRelationship) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


